Repository canonical/snapcraft.io, pull requests merged in 2018-03, with the labels that each got.

#333 Add both Developer contact and website fields
  modules/public/views.py
  modules/publisher/views.py
  static/sass/_snapcraft_market.scss
  templates/publisher/market.html
  templates/snap-details.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1, Review: UX +1

#352 Fix error no HTTP-AGENT in header
  modules/public/views.py
Labels: Review: Code +1, Review: QA +1

#332 public sentry
  app.py
  templates/publisher/market.html
  templates/publisher/measure.html
  templates/snap-details.html
Labels: Review: Code +1, Review: QA +1

#353 Fix no results problem on search
  modules/public/views.py
Labels: Review: Code +1, Review: QA +1

#355 Redirect /snaps to /store
  app.py
Labels: Review: Code +1, Review: QA +1

#361 Fixes JS error when removing non-existent nofitication.
  static/js/publisher/market/market.js
Labels: Review: Code +1, Review: QA +1

#341 Delete screenshots
  modules/publisher/api.py
  modules/publisher/views.py
  static/js/publisher/market/market.js
  static/sass/_snapcraft_market_screenshots.scss
  templates/publisher/market.html
Labels: Review: Code +1, Review: Design needed, Review: QA +1, Review: UX +1

#366 Enable prometheus metrics for flask requests
  .gitignore
  .sass-lint.yml
  app.py
  package.json
  requirements.txt
  run
Labels: Review: Code +1, Review: QA +1

#370 Add babel to rollup
  .babelrc
  package.json
  rollup.config.js
  yarn.lock
Labels: Review: Code +1, Review: QA +1

#357 Updated active devices colour scale
  static/js/publisher/metrics/colorScale.js
  static/js/publisher/metrics/config.js
  static/js/publisher/metrics/graphs/activeDevices.js
  static/sass/_snapcraft_metrics.scss
Labels: Review: Code +1, Review: Design +1, Review: QA +1, Review: UX +1

#367 Jest JavaScript testing
  .babelrc
  .eslintrc.js
  package.json
  static/js/publisher/market/market.js
  static/js/publisher/market/market.test.js
  yarn.lock
Labels: Review: Code +1, Review: QA +1

#373 Remove flask dependency api layer
  app.py
  modules/public/api.py
  modules/public/views.py
  templates/404.html
  tests.py
Labels: Review: Code +1, Review: QA +1

#377 Updates footer design
  static/sass/_snapcraft_custom-typography.scss
  static/sass/_snapcraft_footer.scss
  static/sass/styles.scss
  templates/_footer.html
  templates/_layout.html
  templates/index.html
Labels: Review: Code +1, Review: QA +1

#375 Market page screenshots fixes
  static/js/publisher/market/market.js
  static/js/publisher/market/market.test.js
  static/js/publisher/market/screenshots.js
  static/js/publisher/market/screenshots.test.js
  static/js/publisher/publisher.js
  templates/publisher/market.html
Labels: Review: Code +1, Review: QA +1

#374 Updated 404 page
  static/confused-hex.svg
  static/sass/_snapcraft_404.scss
  static/sass/styles.scss
  templates/404.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1, Review: UX +1

#385 Show blank graphs and message when lacking data.
  modules/publisher/views.py
  static/js/publisher/metrics/axis.js
  static/js/publisher/metrics/graphs/activeDevices.js
  static/sass/_snapcraft_metrics.scss
  templates/publisher/measure.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1, Review: UX +1

#395 Account dedupe and use of correct fields
  modules/publisher/views.py
  templates/account.html
  tests.py
Labels: Review: Code needed, Review: QA needed, Review: UX +1

#345 New consistent header
  static/sass/_snapcraft_banner.scss
  static/sass/_snapcraft_p-navigation.scss
  static/sass/styles.scss
  templates/_header.html
  templates/index.html
  templates/search.html
  templates/store.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1, Review: UX +1

#403 Removes unnecessary spacing from footer links in Firefox
  static/sass/_snapcraft_footer.scss
Labels: Review: Code +1, Review: QA +1

#407 Fixes dark hover on mobile navigation
  static/sass/_snapcraft_p-navigation.scss
Labels: Review: Code +1, Review: QA +1

#408 Ensure br's don't have the * + * spacing applied
  static/sass/_snapcraft_custom-typography.scss
  templates/snap-details.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#376 Handle errors public api calls
  app.py
  modules/cache.py
  modules/exceptions.py
  modules/public/api.py
  modules/public/views.py
  templates/404.html
  templates/index.html
  templates/snap-details.html
  templates/store.html
Labels: Review: Code needed, Review: QA needed

#378 Remove logic from views
  modules/public/logic.py
  modules/public/views.py
Labels: Review: Code needed, Review: QA needed

#300 Create username if user doesn't have one on snap store
  app.py
  modules/authentication.py
  modules/publisher/api.py
  modules/publisher/views.py
  static/sass/styles.scss
  templates/developer_programme_agreement.html
  templates/username.html
Labels: Review: Code +1, Review: Design +1, Review: QA needed

#415 Fix wrong import publisher metrics
  modules/publisher/views.py
Labels: Review: Code +1, Review: QA +1

#418 Fixes typo on front page
  templates/index.html
Labels: Review: Code +1, Review: QA +1

#420 Reordered SASS to remove linting warnings
  static/sass/_patterns_inline-list--compact.scss
  static/sass/_patterns_maas_modal.scss
  static/sass/_patterns_media-object--large.scss
  static/sass/_snapcraft_metrics.scss
  static/sass/_snapcraft_snap-list.scss
Labels: Review: Code +1

#423 Extend timeout to 3 seconds
  modules/cache.py
Labels: Review: Code +1, Review: QA +1

#426 Removed user facing content from homepage
  templates/index.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#422 Use talisker
  .gitignore
  .sass-lint.yml
  Dockerfile
  app.py
  package.json
  requirements.txt
  run
Labels: Review: Code +1, Review: QA +1

#419 CLI install command
  package.json
  static/sass/_patterns_media-object.scss
  static/sass/_snapcraft_snap-details.scss
  static/sass/styles.scss
  templates/snap-details.html
  yarn.lock
Labels: Review: Code +1, Review: Design +1, Review: QA +1, Review: UX +1

#430 Remove flask session in api
  modules/publisher/api.py
  modules/publisher/views.py
Labels: Review: Code needed, Review: QA needed

#434 Add DEVEL to .env variables
  .env
Labels: Review: Code +1, Review: QA +1

#439 Fixes typo in install instructions HTML
  templates/snap-details.html
Labels: Review: Code +1, Review: QA +1

#416 Market page - only save changed fields
  static/js/publisher/market/market.js
  static/js/publisher/market/market.test.js
  static/js/publisher/market/screenshots.js
  static/js/publisher/market/screenshots.test.js
  static/js/publisher/market/state.js
  static/js/publisher/market/state.test.js
  templates/publisher/market.html
Labels: Review: Code +1, Review: QA +1

#433 Smaller headings
  static/sass/_snapcraft_metrics.scss
  static/sass/_snapcraft_p-tabs.scss
  static/sass/styles.scss
  templates/publisher/market.html
  templates/publisher/measure.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1, Review: UX +1

#444 Fixes screenshots JS errors from sentry
  static/js/public/snap-details/screenshots.js
Labels: Priority: High, Review: Code +1, Review: QA +1, Type: Bug

#442 Defend against undefined vars
  templates/snap-details.html
Labels: Review: Code +1, Review: QA +1

#451 Update search results
  static/sass/_patterns_media-object.scss
  templates/search.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#431 Move flask.abort from API module
  modules/publisher/api.py
  modules/publisher/views.py
Labels: Review: Code +1, Review: QA +1

#454 Adds missing market fields when there are post errors
  modules/publisher/views.py
Labels: Review: Code +1, Review: QA +1

#458 Fix width of empty screenshots box on market page
  templates/publisher/market.html
Labels: Review: Code +1, Review: QA +1

#460 Adds basic Vanilla style validation to market input fields
  static/js/publisher/market/market.js
  static/sass/styles.scss
  templates/publisher/market.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#461 Polyfill for Array.from and Element.closest
  static/js/polyfills.js
  static/js/public/public.js
  static/js/public/snap-details/screenshots.js
  static/js/publisher/publisher.js
Labels: Review: Code +1, Review: QA +1

#435 Remove flask dependency from validation
  modules/authentication.py
  modules/exceptions.py
  modules/publisher/api.py
  modules/publisher/views.py
  tests.py
Labels: Review: Code needed, Review: QA +1

#453 Tests account detail page
  modules/publisher/views.py
  package.json
  requirements.txt
  tests_basic.py
  tests_public.py
  tests_publisher.py
Labels: Review: Code +1

#463 Test username endpoint
  modules/publisher/views.py
  tests_publisher.py
Labels: Review: Code +1

#464 Add integration tests for /account/agreement
  modules/publisher/views.py
  tests_publisher.py
Labels: Review: Code needed

#462 Public metrics toggles
  app.py
  modules/publisher/views.py
  static/js/publisher/market/market.js
  static/js/publisher/market/publicMetrics.js
  static/js/publisher/market/state.js
  templates/publisher/market.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#466 Add custom User-Agent headers for the storefront
  .env
  modules/cache.py
Labels: Review: Code +1, Review: QA +1

#468 Don't display map when 'NO DATA'
  modules/public/logic.py
  templates/snap-details.html
Labels: Review: Code +1, Review: QA +1

#467 Show validation errors next to input fields
  modules/publisher/views.py
  static/js/publisher/market/market.js
  templates/publisher/market.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1
