Repository canonical/snapcraft.io, pull requests merged in 2018-08, with the labels that each got.

#960 Further fixes for innerHTML and more logging
  static/js/public/snap-details/channelMap.js
  templates/store/snap-details.html
Labels: Review: Code +1

#958 Show --classic on snap details
  static/js/public/snap-details/channelMap.js
  templates/store/snap-details/_channel_map.html
  tests/store/tests_public_logic.py
  webapp/store/logic.py
  webapp/store/views.py
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#961 conflict_on_update for binary-metadata
  tests/publisher/snaps/tests_post_binary_metadata.py
  webapp/api/dashboard.py
Labels: Review: Code +1

#963 get the right blog posts and set the right titles
  webapp/api/blog.py
  webapp/blog/views.py
Labels: Review: Code +1, Review: QA +1

#965 Remove copydocs metadata where it's not needed
  templates/publisher/_publisher_layout.html
  templates/publisher/account-details.html
  templates/publisher/account-snaps.html
  templates/publisher/developer_programme_agreement.html
  templates/publisher/listing.html
  templates/publisher/metrics.html
  templates/publisher/register-snap.html
  templates/publisher/release-history.html
  templates/publisher/username.html
  templates/store/search.html
  templates/store/snap-details.html
Labels: Review: Code +1, Review: QA +1

#972 Declare category_results before use
  webapp/store/views.py
Labels: Review: Code +1, Review: QA +1

#926 0 search results
  static/sass/_search-form.scss
  templates/store/search.html
Labels: Review: Code +1, Review: QA +1

#992 remove whitespace from brand-store nav
  templates/_header-brandstore.html
Labels: Review: Code +1, Review: QA +1

#974 If no_redirect set on logout, don't logout of bsi and go straight to snapcraft.io homepage
  .env
  templates/_header.html
  tests/publisher/tests_account_logout.py
  webapp/config.py
  webapp/handlers.py
  webapp/login/views.py
Labels: Review: Code +1, Review: QA +1

#957 Add build.snapcraft.io homepage to snapcraft.io/build
  static/sass/_snapcraft_custom-typography.scss
  static/sass/_snapcraft_p-build.scss
  static/sass/styles.scss
  templates/_header.html
  templates/snapcraft/build.html
  webapp/snapcraft/views.py
  webapp/template_utils.py
Labels: Review: Code +1, Review: Design +1, Review: QA +1, Review: UX +1

#991 Add caching layer to blog
  .gitignore
  package.json
  requirements.txt
  tests/blog/tests_index.py
  webapp/app.py
  webapp/blog/__init__.py
  webapp/blog/views.py
  webapp/extensions.py
Labels: Review: Code needed, Review: QA needed

#997 Return 404 if no channel map
  webapp/store/views.py
Labels: Review: Code +1, Review: QA +1

#973 Add undo release button
  static/js/publisher/release/revisionsTable.js
  static/sass/_snapcraft_release.scss
  templates/publisher/_header.html
  templates/publisher/release-history.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#999 Fixed LimeNET command instructions on homepage
  templates/brand-store/store.html
Labels: Review: Code +1, Review: QA +1

#1001 Use releases v2 API instead of revision history
  static/js/publisher/release.js
  static/js/publisher/release/revisionsList.js
  static/js/publisher/release/revisionsTable.js
  templates/publisher/release-history.html
  tests/publisher/snaps/tests_revision.py
  webapp/api/dashboard.py
  webapp/publisher/snaps/views.py
Labels: Review: Code +1, Review: QA +1

#1003 Rename entrypoint; update production image
  Dockerfile
  entrypoint
  entrypoint.sh
  package.json
Labels: Review: Code +1, Review: QA +1

#1012 Fix release date
  static/js/publisher/release/revisionsList.js
Labels: Review: Code +1, Review: QA +1

#1009 Add copydocs to build and blog pages
  templates/blog/article.html
  templates/blog/index.html
  templates/snapcraft/build.html
Labels: Review: Code +1, Review: QA +1

#1002 Hide public metrics on brand stores
  templates/store/snap-details.html
  webapp/store/views.py
Labels: Review: Code needed, Review: QA +1

#1016 Default WEBAPP=snapcraft
  Dockerfile
Labels: Review: Code needed, Review: QA needed

#1022 Escape only html tags in description
  webapp/store/logic.py
Labels: Review: Code +1, Review: QA +1

#994 IoT page
  static/sass/_patterns_card.scss
  static/sass/_patterns_case-study.scss
  static/sass/_patterns_snap-row.scss
  static/sass/styles.scss
  templates/_header.html
  templates/store/categories/iot.html
  webapp/snapcraft/views.py
  webapp/template_utils.py
Labels: Review: Code +1, Review: Design +1, Review: QA +1, Review: UX +1

#1024 Fixed width nav
  templates/_header.html
Labels: Review: Code +1, Review: QA +1

#1026 Highlight item selected on navigation
  static/sass/_snapcraft_p-navigation.scss
Labels: Review: Design +1, Review: UX +1

#1041 Broken link to Fingbox CS on the IoT page
  templates/store/categories/iot.html
Labels: Priority: High, Review: Code +1

#1045 Fix entrypoint logic
  entrypoint
Labels: Review: Code +1

#1046 On map error, throw a useful error
  static/js/public/snap-details/map.js
Labels: Review: Code +1, Review: QA needed

#1047 Fail fast on not having d3 defined
  static/js/public/snap-details/map.js
Labels: Review: Code +1

#1027 Add blog posts to snap details pages
  static/js/public/public.js
  static/js/public/snap-details/blog-posts.js
  static/sass/_patterns_card.scss
  templates/blog/index.html
  templates/partials/blog-card--minimal.html
  templates/partials/blog-card.html
  templates/store/snap-details.html
  webapp/api/blog.py
  webapp/blog/logic.py
  webapp/blog/views.py
Labels: Review: Code +1, Review: Design +1, Review: QA needed, Review: UX +1

#1048 Get channel maps data into releases template
  static/js/publisher/release.js
  templates/publisher/release-history.html
  tests/publisher/snaps/tests_revision.py
  webapp/publisher/snaps/views.py
Labels: Review: Code +1, Review: QA +1

#1050 Use es6 includes for d3 and momentjs
  .gitignore
  package.json
  rollup.config.js
  static/js/public/snap-details/map.js
  static/js/publisher/metrics/axis.js
  static/js/publisher/metrics/graphs/activeDevices.js
  static/js/publisher/metrics/metrics.js
  static/js/publisher/metrics/tooltips.js
  templates/publisher/developer_programme_agreement.html
  templates/publisher/metrics.html
  templates/store/snap-details.html
  yarn.lock
Labels: Review: Code +1, Review: QA +1

#1049 Blog series
  static/js/public/public.js
  static/js/public/snap-details/blog-posts.js
  static/sass/_patterns_blog-list.scss
  static/sass/_patterns_blog-post.scss
  static/sass/styles.scss
  templates/blog/article.html
  webapp/api/blog.py
  webapp/blog/views.py
Labels: Review: Code +1, Review: Design +1, Review: QA +1, Review: UX +1

#1011 Move different flex grid styles into one pattern
  static/sass/_base_image-grid.scss
  static/sass/_patterns_featured-snaps.scss
  static/sass/_patterns_fluid-grid.scss
  static/sass/_patterns_logo-links.scss
  static/sass/_patterns_logo-list.scss
  static/sass/styles.scss
  templates/brand-store/store.html
  templates/index.html
  templates/snapcraft/build.html
Labels: Review: Code +1, Review: QA +1
