Repository canonical/snapcraft.io, pull requests merged in 2018-05, with the labels that each got.

#615 Use function to catch exceptions API calls
  modules/publisher/views.py
Labels: Review: Code +1, Review: QA +1

#624 Remove logic listing page
  modules/publisher/logic.py
  modules/publisher/views.py
  tests/tests_publisher_logic.py
Labels: Review: Code +1, Review: QA +1

#623 Focusable screenshots in listing form
  static/js/publisher/market/screenshots.js
  static/js/publisher/market/screenshots.test.js
  static/sass/_snapcraft_market_screenshots.scss
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#626 Remove logic POST listing
  modules/publisher/logic.py
  modules/publisher/views.py
Labels: Review: Code +1, Review: QA +1

#627 Add channel graph to metrics
  modules/publisher/logic.py
  templates/publisher/metrics.html
Labels: Review: Code +1, Review: QA +1

#628 Remove - from distro labels
  modules/public/logic.py
  templates/snap-details.html
  tests/tests_public_logic.py
Labels: Review: Code +1, Review: QA +1

#629 Add exceptions for username and agreement
  modules/exceptions.py
  modules/publisher/api.py
  modules/publisher/views.py
Labels: Review: Code +1, Review: QA +1

#621 Metrics classes
  modules/metrics/helper.py
  modules/metrics/metrics.py
  modules/public/logic.py
  modules/public/views.py
  modules/publisher/logic.py
  modules/publisher/views.py
  tests/tests_metrics.py
  tests/tests_public_logic.py
Labels: Review: Code +1, Review: QA +1

#636 Make sure nodejs shows up on the store
  modules/public/api.py
  modules/public/logic.py
  modules/public/views.py
  templates/snap-details.html
Labels: Review: Code +1, Review: QA +1

#597 Improved first snap experience
  modules/publisher/logic.py
  modules/publisher/views.py
  static/sass/_snapcraft_snap-list.scss
  templates/publisher/account-snaps.html
  tests/tests_account_snaps.py
  tests/tests_publisher_logic.py
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#641 Update channel map layout
  static/sass/_snapcraft_details_heading.scss
  templates/snap-details/_channel_map.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#648 Close channel map when clicking outside or on Escape
  static/js/public/snap-details/channelMap.js
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#634 Add register name endpoint with basic template
  app.py
  modules/publisher/api.py
  modules/publisher/views.py
  templates/publisher/register-name.html
  tests/tests_register_name.py
Labels: Review: Code +1, Review: QA +1

#650 Make snapracft as a module
  Dockerfile
  package.json
  tests/endpoint_testing.py
  tests/tests_basic.py
  tests/tests_metrics.py
  tests/tests_public.py
  tests/tests_public_logic.py
  tests/tests_publisher.py
  tests/tests_publisher_logic.py
  webapp/__init__.py
  webapp/app.py
  webapp/authentication.py
  webapp/cache.py
  webapp/decorators.py
  webapp/exceptions.py
  webapp/helpers.py
  webapp/macaroon.py
  webapp/metrics/helper.py
  webapp/metrics/metrics.py
  webapp/public/__init__.py
  webapp/public/api.py
  webapp/public/logic.py
  webapp/public/views.py
  webapp/publisher/__init__.py
  webapp/publisher/api.py
  webapp/publisher/logic.py
  webapp/publisher/views.py
  webapp/template_functions.py
Labels: Review: Code needed, Review: QA needed

#654 Updatate Flask 1.0.2
  .env
  requirements.txt
Labels: Review: QA +1

#656 Updated styling for snap details page
  templates/snap-details.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#653 Adds install tab to channel map overlay
  static/js/public/snap-details/channelMap.js
  static/sass/_snapcraft_details_heading.scss
  templates/snap-details.html
  templates/snap-details/_channel_map.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#659 Reduce spacing at the top my snaps page
  templates/publisher/account-snaps.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#663 Updated beta bar notification copy
  templates/publisher/_beta-notification.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#664 Add spinner to save button (when saving)
  static/js/publisher/market/market.js
  static/sass/_patterns_button_spinner.scss
  static/sass/styles.scss
  templates/publisher/listing.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1, Review: UX +1

#640 Moves “My snaps” and adds “Build with GitHub” to account menu
  static/sass/_snapcraft_p-navigation.scss
  templates/_header.html
  templates/account.html
  templates/publisher/account-snaps.html
  webapp/public/views.py
  webapp/publisher/views.py
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#667 Make Install more prominent and remove duplication #666
  static/js/public/snap-details/channelMap.js
  static/sass/_snapcraft_details_heading.scss
  templates/snap-details.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1, Review: UX +1

#670 Add style to reserve name templates
  templates/publisher/register-name.html
  tests/tests_register_name.py
  webapp/app.py
  webapp/publisher/views.py
Labels: Review: Code +1, Review: QA +1

#657 Updated testimonial design on homepage
  static/sass/_patterns_testimonial.scss
  templates/index.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#683 Small tidy up for unnecessary hrs on snap pages
  templates/snap-details.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#682 Vertically align developer contact fields
  templates/publisher/listing.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1, Review: UX +1

#685 Use snapstoreapi module, remove code duplication
  requirements.txt
  tests/endpoint_testing.py
  tests/tests_publisher.py
  webapp/app.py
  webapp/authentication.py
  webapp/cache.py
  webapp/decorators.py
  webapp/exceptions.py
  webapp/public/api.py
  webapp/public/views.py
  webapp/publisher/api.py
  webapp/publisher/views.py
Labels: Review: Code +1, Review: QA +1

#687 Small fixes for s.io
  tests/tests_basic.py
  webapp/publisher/views.py
Labels: Review: Code +1, Review: QA +1

#690 Updated SEO titles and descriptions
  templates/snap-details.html
  templates/store.html
Labels: Review: Code +1, Review: QA +1

#689 Limit intent GA to first click
  static/js/public/snap-details/channelMap.js
Labels: Review: Code +1, Review: QA +1

#694 Upgrade api to version 0.3
  requirements.txt
Labels: Review: Code +1, Review: QA +1

#686 Improve request name view
  templates/publisher/register-name.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1
