Repository canonical/snapcraft.io, pull requests merged in 2018-06, with the labels that each got.

#707 Create blog blueprint
  templates/blog/index.html
  tests/blog/__init__.py
  tests/blog/tests_index.py
  webapp/app.py
  webapp/blog/blog.py
Labels: Review: Code needed, Review: QA needed

#705 Toggle snap privacy on listing page
  static/js/publisher/market/market.js
  static/js/publisher/market/state.js
  templates/publisher/listing.html
  webapp/publisher/logic.py
  webapp/publisher/views.py
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#706 Highlight store on snap and search page navigation
  static/sass/_snapcraft_p-navigation.scss
  templates/_header.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#711 Get list of articles from API
  templates/blog/index.html
  tests/blog/tests_index.py
  webapp/blog/api.py
  webapp/blog/blog.py
Labels: Review: Code +1, Review: QA +1

#708 Better experience for contact inputs
  static/js/base/polyfills.js
  static/js/publisher/market/market.js
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#712 Add article endpoint
  templates/blog/post.html
  tests/blog/tests_index.py
  webapp/blog/api.py
  webapp/blog/blog.py
Labels: Review: Code +1, Review: QA +1

#713 Add store blueprint
  webapp/app.py
  webapp/public/views.py
Labels: Review: Code +1, Review: QA +1

#709 Order tracks on channel map
  static/js/public/snap-details/channelMap.js
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#715 Add publisher blueprint
  tests/tests_agreement.py
  tests/tests_publisher.py
  tests/tests_register_name.py
  tests/tests_username.py
  webapp/app.py
  webapp/publisher/views.py
Labels: Review: Code needed, Review: QA +1

#718 Small fixes for blueprints
  templates/blog/index.html
  templates/blog/post.html
  templates/promoted.html
  webapp/app.py
  webapp/blog/views.py
  webapp/public/views.py
  webapp/publisher/views.py
Labels: Review: Code +1, Review: QA +1

#721 Create login blueprint
  webapp/app.py
  webapp/login/macaroon.py
  webapp/login/views.py
Labels: Review: Code +1, Review: QA +1

#724 Use factories to launch snapcraft
  .env
  package.json
  tests/blog/tests_index.py
  tests/endpoint_testing.py
  tests/tests_public.py
  tests/tests_publisher.py
  webapp/app.py
  webapp/config.py
  webapp/handlers.py
  webapp/public/views.py
Labels: Review: Code +1, Review: QA +1

#714 Only use lightbox if on a larger screen
  static/js/libs/mobile.js
  static/js/public/snap-details/screenshots.js
Labels: Review: Code +1, Review: QA +1

#726 Create publisher snaps blueprint
  tests/tests_publisher.py
  tests/tests_publisher_logic.py
  webapp/app.py
  webapp/publisher/snaps/logic.py
  webapp/publisher/snaps/views.py
  webapp/publisher/views.py
Labels: Review: Code +1, Review: QA +1

#723 Blog articles list
  static/sass/_patterns_card.scss
  static/sass/_patterns_testimonial.scss
  static/sass/_snapcraft_distro-chart.scss
  static/sass/_snapcraft_p-beta-notification.scss
  static/sass/_snapcraft_snap-list.scss
  static/sass/_utilities_crop.scss
  static/sass/styles.scss
  templates/blog/index.html
  tests/blog/tests_index.py
  webapp/blog/api.py
  webapp/blog/logic.py
  webapp/blog/views.py
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#717 Prevent 'store' being highlighted in nav when on publisher pages
  templates/_header.html
  webapp/handlers.py
  webapp/template_utils.py
Labels: Review: Code +1, Review: QA +1

#736 Add rss feeds for blog
  tests/blog/tests_index.py
  webapp/blog/api.py
  webapp/blog/logic.py
  webapp/blog/views.py
Labels: Review: Code +1, Review: QA +1

#734 Blog article
  static/sass/_patterns_blog-post.scss
  static/sass/styles.scss
  templates/_layout.html
  templates/blog/article.html
  templates/blog/index.html
  templates/blog/post.html
  tests/blog/tests_index.py
  webapp/blog/api.py
  webapp/blog/logic.py
  webapp/blog/views.py
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#739 Add brandstore configuration
  .env
  templates/404.html
  templates/_layout-brandstore.html
  templates/blog/article.html
  templates/blog/index.html
  templates/index.html
  templates/publisher/account-details.html
  templates/publisher/account-snaps.html
  templates/publisher/listing.html
  templates/publisher/metrics.html
  templates/publisher/register-name.html
  templates/search.html
  templates/snap-details.html
  templates/store.html
  templates/username.html
  webapp/app.py
  webapp/config.py
  webapp/configs/snapcraft.py
  webapp/handlers.py
Labels: Review: Code needed, Review: QA needed

#738 Update dockerfile
  Dockerfile
Labels: Review: Code +1, Review: QA +1

#735 Add quick CircleCI config
  .circleci/config.yml
Labels: Review: Code needed

#741 Convert gunicorn worked to a async gevent worker
  package.json
  requirements.txt
Labels: Review: Code +1, Review: QA +1

#740 Add webapp environment variable to dockerfile
  Dockerfile
Labels: Review: Code +1, Review: QA +1

#744 Add demo brand store header
  templates/_header-brandstore.html
  templates/_layout-brandstore.html
Labels: Review: Code +1, Review: QA +1

#745 Add feature flag for blog endpoints
  .env
  webapp/app.py
  webapp/configs/snapcraft.py
Labels: Review: Code +1

#765 Move back api module to s.io
  requirements.txt
  tests/endpoint_testing.py
  tests/tests_publisher.py
  webapp/api/blog.py
  webapp/api/cache.py
  webapp/api/dashboard.py
  webapp/api/exceptions.py
  webapp/api/public.py
  webapp/authentication.py
  webapp/blog/views.py
  webapp/configs/brand.py
  webapp/configs/lime.py
  webapp/decorators.py
  webapp/handlers.py
  webapp/login/views.py
  webapp/public/views.py
  webapp/publisher/snaps/views.py
  webapp/publisher/views.py
  webapp/snapcraft/views.py
Labels: Review: Code +1, Review: QA +1

#767 Update run script and dockerfile to use Bionic
  Dockerfile
  run
Labels: Review: Code +1, Review: QA +1

#691 Homepage updates
  static/sass/_patterns_logo-links.scss
  static/sass/_patterns_logo-list.scss
  static/sass/styles.scss
  templates/index.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#743 Better registration
  templates/publisher/account-snaps.html
  templates/publisher/register-name.html
  webapp/publisher/views.py
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#771 Vanilla home page updates
  static/sass/_patterns_logo-list.scss
  templates/index.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#766 Fix icon size and rotation when dropdown is open
  static/sass/_snapcraft_p-navigation.scss
Labels: Review: Code +1, Review: Design needed, Review: QA +1

#770 Equal footer padding above and below
  static/sass/_snapcraft_footer.scss
Labels: Review: Code +1, Review: QA +1

#774 Revert run script upgrade
  Dockerfile
  run
Labels: Review: Code +1, Review: QA +1

#781 Adds missing URLs to featured snaps links
  templates/index.html
  templates/store.html
Labels: Review: Code +1, Review: QA +1

#782 Update spacing of snap details heading
  static/sass/_snapcraft_details_heading.scss
Labels: Review: Code +1, Review: QA +1

#788 Fix key-value table borders
  static/sass/_patterns_table-key-value.scss
Labels: Review: Code +1, Review: QA +1

#789 Fixes spacing on snap details page
  static/js/public/snap-details/screenshots.js
  templates/snap-details.html
Labels: Review: Code +1, Review: QA +1

#790 My snaps tidy-up
  static/sass/_snapcraft_snap-list.scss
  templates/publisher/account-snaps.html
Labels: Review: Code +1, Review: QA +1

#786 Update to latest run with unset array fix
  Dockerfile
  run
Labels: Review: Code +1, Review: QA +1

#791 Fix spacing of install/channels overlay
  static/sass/_snapcraft_details_heading.scss
  templates/snap-details/_channel_map.html
Labels: Review: Code +1, Review: QA +1

#792 Fixes selected navigation styles (on mobile)
  static/sass/_snapcraft_p-navigation.scss
  templates/_header.html
Labels: Review: Code +1, Review: QA +1

#776 Single column checkboxes
  templates/publisher/listing.html
Labels: Review: Code +1, Review: QA +1

#795 Update blog tag id
  webapp/api/blog.py
Labels: Review: Code +1, Review: QA +1

#796 Workaround for incorrect img alignment
  static/sass/styles.scss
Labels: Review: Code +1, Review: QA +1

#797 Snap listing redo
  static/sass/_patterns_nested-inputs.scss
  static/sass/_snapcraft_market.scss
  static/sass/_snapcraft_p-tabs.scss
  static/sass/styles.scss
  templates/publisher/_header.html
  templates/publisher/listing.html
Labels: Review: Code +1, Review: QA +1

#800 Adds some spacing to metrics page
  templates/publisher/metrics.html
Labels: Review: Code +1, Review: QA +1

#672 Updates snapcraft.io Vanilla to 1.7.1
  package.json
  static/js/public/snap-details/screenshots.js
  static/sass/_base_image-grid.scss
  static/sass/_patterns_featured-snaps.scss
  static/sass/_patterns_logo-list.scss
  static/sass/_patterns_nested-inputs.scss
  static/sass/_patterns_table-key-value.scss
  static/sass/_search-form.scss
  static/sass/_snapcraft_details_heading.scss
  static/sass/_snapcraft_footer.scss
  static/sass/_snapcraft_market.scss
  static/sass/_snapcraft_market_screenshots.scss
  static/sass/_snapcraft_p-navigation.scss
  static/sass/_snapcraft_p-tabs.scss
  static/sass/_snapcraft_snap-list.scss
  static/sass/styles.scss
  templates/_header.html
  templates/index.html
  templates/publisher/_beta-notification.html
  templates/publisher/_header.html
  templates/publisher/account-snaps.html
  templates/publisher/listing.html
  templates/publisher/metrics.html
  templates/search.html
  templates/snap-details.html
  templates/snap-details/_channel_map.html
  templates/store.html
  yarn.lock
Labels: Review: QA +1

#773 Add store conf to have specific ubuntustore
  .env
  webapp/api/public.py
  webapp/app.py
  webapp/config.py
  webapp/configs/brand.py
  webapp/configs/snapcraft.py
  webapp/public/views.py
  webapp/snapcraft/views.py
Labels: Review: Code +1, Review: QA +1

#804 Add tests job to circle ci configuration
  .circleci/config.yml
  tests/blog/tests_index.py
  tests/endpoint_testing.py
  tests/tests_public.py
  tests/tests_publisher.py
Labels: Review: Code +1, Review: QA +1

#807 Remove travis.yaml
  .travis.yml
Labels: Review: Code +1, Review: QA +1

#808 Run script Yarn permissions
  run
Labels: Review: Code needed, Review: QA needed

#809 Raise exception if `WEBAPP` is not defined
  .circleci/config.yml
  .env
  webapp/config.py
Labels: Review: Code needed

#810 Add revision history endpoint
  templates/publisher/release-history.html
  tests/tests_revision.py
  webapp/api/dashboard.py
  webapp/publisher/snaps/views.py
Labels: Review: Code +1, Review: QA +1

#802 Final pieces for v1 of verified publishers
  webapp/api/public.py
  webapp/public/views.py
Labels: Review: Code +1, Review: QA +1

#812 Update readme to create brand stores
  README.md
Labels: Review: Code +1, Review: QA +1

#818 Added privacy notice link to developer agreement
  templates/developer_programme_agreement.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#821 React test setup with vanilla-framework-react
  .babelrc
  .eslintrc.js
  package.json
  rollup.config.js
  static/js/publisher/release.js
  static/js/publisher/release/app.js
  templates/publisher/release-history.html
  yarn.lock
Labels: Review: Code +1, Review: QA +1

#822 Add releases page with table of revisions
  package.json
  rollup.config.js
  static/js/publisher/release.js
  static/js/publisher/release/app.js
  static/js/publisher/release/revisionsList.js
  templates/publisher/_header.html
  templates/publisher/release-history.html
  yarn.lock
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#827 Message on homepage
  templates/index.html
Labels: Review: Code needed, Review: QA needed, Review: UX +1
