Repository canonical/snapcraft.io, pull requests merged in 2018-11, with the labels that each got.

#1253 Upgrade requests to v2.20.0
  requirements.txt
Labels: Review: QA +1

#1262 Restructure directories, updated content of package step
  static/js/public/first-snap-flow.js
  static/js/public/public.js
  static/sass/_patterns_logo-links.scss
  templates/first-snap/package.html
  tests/first_snap/tests_views.py
  webapp/first_snap/content/python/build.yaml
  webapp/first_snap/content/python/package.yaml
  webapp/first_snap/content/python/test.yaml
  webapp/first_snap/views.py
Labels: Review: Code +1, Review: QA +1

#1263 Fsf ga snap
  static/js/public/first-snap-flow.js
  webapp/publisher/snaps/views.py
Labels: Review: Code +1, Review: QA +1

#1264 Rename release endpoint to releases
  static/js/publisher/release/releasesController.js
  templates/publisher/_header.html
  templates/publisher/account-snaps.html
  tests/publisher/snaps/tests_post_close_channel.py
  tests/publisher/snaps/tests_post_release.py
  tests/publisher/snaps/tests_revision.py
  webapp/publisher/snaps/views.py
Labels: Review: Code +1, Review: QA +1

#1257 Filter revisions table based on arch clicked
  static/js/publisher/release/releasesController.js
  static/js/publisher/release/revisionsList.js
  static/js/publisher/release/revisionsTable.js
  static/sass/_snapcraft_release.scss
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#1280 Move from gevent to sync workers
  entrypoint
Labels: Review: Code +1, Review: QA +1

#1273 Fix truncating version number in releases table
  static/js/publisher/release/revisionsTable.js
  static/sass/_snapcraft_release.scss
Labels: Review: Code +1, Review: QA +1

#1275 Fixes getting the name of tracked channel
  static/js/publisher/release/releasesController.js
Labels: Review: Code +1, Review: QA +1

#1259 Move crsf exemption
  webapp/app.py
  webapp/decorators.py
  webapp/login/views.py
Labels: Review: Code +1, Review: QA +1

#1282 Refactoring release UI components
  static/js/publisher/release/releasesController.js
  static/js/publisher/release/revisionsList.js
  static/js/publisher/release/revisionsTable.js
Labels: Review: Code +1, Review: QA +1

#1283 Fix missing links and icons iot page
  templates/store/categories/iot.html
Labels: Review: Code +1, Review: QA +1

#1281 Add global ga-tracking
  static/js/base/base.js
  static/js/base/ga.js
  static/js/public/snap-details/channelMap.js
  templates/_layout-brandstore.html
  templates/_layout.html
Labels: Review: Code +1, Review: QA +1

#1288 Fix Privacy Notice URL when signing up for developer account.
  templates/publisher/developer_programme_agreement.html
Labels: Review: Code +1

#1290 Extend search to wide architectures
  webapp/api/store.py
Labels: Review: Code +1, Review: QA +1

#1279 Updated python flow
  static/js/public/first-snap-flow.js
  static/sass/_snapcraft_p-notifications.scss
  templates/first-snap/_install-macos.html
  templates/first-snap/build.html
  templates/first-snap/install-snapcraft.html
  templates/first-snap/language.html
  templates/first-snap/package.html
  templates/first-snap/push.html
  templates/first-snap/test.html
  templates/home/_fsf_python.html
  templates/index.html
  templates/partials/fsf_language.html
  templates/publisher/_header.html
  templates/publisher/listing.html
  tests/publisher/snaps/tests_listing.py
  webapp/first_snap/content/python/build.yaml
  webapp/first_snap/content/python/package.yaml
  webapp/first_snap/content/python/test.yaml
  webapp/first_snap/logic.py
  webapp/publisher/snaps/views.py
Labels: Review: Code +1, Review: QA needed

#1291 Updated store and snap details pages
  templates/brand-store/store.html
  templates/store/snap-details.html
  templates/store/store.html
Labels: Review: Code +1, Review: QA +1

#1294 Updated offlineimap instructions
  webapp/first_snap/content/python/build.yaml
Labels: Review: Code +1

#1292 Fix missing attribute when no response from api
  tests/store/tests_details.py
  webapp/api/store.py
  webapp/app.py
  webapp/store/views.py
Labels: Review: Code +1, Review: QA +1

#1293 Return last cached api call on error
  webapp/api/requests.py
Labels: Review: Code +1, Review: QA +1

#1300 Workaround LP: #1802899
  webapp/first_snap/content/python/package.yaml
Labels: Review: Code +1, Review: QA +1

#1286 Shows release history when channel/arch cell is clicked in release UI
  static/js/publisher/release.js
  static/js/publisher/release/releasesController.js
  static/js/publisher/release/revisionsList.js
  static/js/publisher/release/revisionsTable.js
  static/sass/_snapcraft_release.scss
  tests/publisher/snaps/tests_revision.py
  webapp/api/dashboard.py
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#1299 Redirect blog.ubuntu.com URL forms to the blog
  tests/blog/tests_index.py
  webapp/blog/views.py
Labels: Review: Code needed, Review: QA needed

#1284 Publicise your snap
  static/images/badges/de/snap-store-black.svg
  static/images/badges/de/snap-store-white.svg
  static/images/badges/en/snap-store-black.svg
  static/images/badges/en/snap-store-white.svg
  static/images/badges/es/snap-store-black.svg
  static/images/badges/es/snap-store-white.svg
  static/images/badges/fr/snap-store-black.svg
  static/images/badges/fr/snap-store-white.svg
  static/images/badges/jp/snap-store-black.svg
  static/images/badges/jp/snap-store-white.svg
  static/images/badges/ru/snap-store-black.svg
  static/images/badges/ru/snap-store-white.svg
  static/images/badges/tw/snap-store-black.svg
  static/images/badges/tw/snap-store-white.svg
  static/js/publisher/publicise.js
  static/js/publisher/publisher.js
  static/sass/_snapcraft-publicise.scss
  static/sass/_snapcraft_p-tabs.scss
  static/sass/styles.scss
  templates/publisher/_header.html
  templates/publisher/publicise.html
  tests/publisher/snaps/tests_get_metrics.py
  tests/publisher/snaps/tests_publicise.py
  webapp/publisher/snaps/views.py
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#1301 Add a Go first-snap guide
  templates/home/_fsf_go.html
  templates/partials/fsf_language.html
  webapp/first_snap/content/golang/build.yaml
  webapp/first_snap/content/golang/package.yaml
  webapp/first_snap/content/golang/test.yaml
Labels: Review: Code +1, Review: QA +1

#1307 Update release UI layout
  static/js/publisher/release/releasesController.js
  static/js/publisher/release/releasesOverlay.js
  static/js/publisher/release/revisionsTable.js
  static/sass/_snapcraft_release.scss
  templates/publisher/release-history.html
Labels: Review: Code +1, Review: QA +1

#1310 Ensure the last point on the graph is accessible
  static/js/publisher/metrics/graphs/activeDevices.js
Labels: Review: Code +1, Review: QA +1

#1311 Get metrics 1 day and 3 hours previously
  webapp/metrics/helper.py
Labels: Review: Code +1, Review: QA +1

#1314 Update ES, set asset version number as variable
  static/images/badges/es/snap-store-black.svg
  static/images/badges/es/snap-store-white.svg
  templates/publisher/publicise.html
  webapp/publisher/snaps/views.py
Labels: Review: Code +1, Review: QA +1

#1318 Included links to legal information and data privacy in the footer
  templates/_footer.html
Labels: Review: Code +1, Review: QA +1

#1319 Disabled full screen button on listing page when there are no screenshot
  static/js/publisher/market/screenshots.js
Labels: Review: Code +1, Review: QA +1

#1315 Release UI - expandable history panel
  static/js/publisher/release/historyPanel.js
  static/js/publisher/release/releasesController.js
  static/js/publisher/release/releasesTable.js
  static/js/publisher/release/revisionsList.js
  static/sass/_snapcraft_release.scss
Labels: Review: Code +1, Review: Design +1, Review: QA +1, Review: UX +1

#1316 Updated copy for FSF / Apple touch icon
  templates/_layout.html
  templates/first-snap/package.html
  templates/home/_fsf_go.html
  templates/home/_fsf_python.html
  webapp/first_snap/content/golang/package.yaml
  webapp/first_snap/content/python/package.yaml
Labels: Review: Code needed, Review: QA +1, Review: UX +1

#1334 Optimise gifs
  static/js/public/snap-details/screenshots.js
  static/js/publisher/market/lightbox.js
  static/sass/_patterns_carousel.scss
  templates/store/snap-details.html
Labels: Review: Code +1, Review: QA +1

#1320 Use cloudinary for blog post images
  tests/blog/tests_index.py
  webapp/blog/logic.py
  webapp/blog/views.py
Labels: Review: Code +1, Review: QA +1

#1328 Release UI - visual updates
  static/js/publisher/release/contextualMenu.js
  static/js/publisher/release/releasesTable.js
  static/sass/_snapcraft_release.scss
Labels: Review: Code +1, Review: Design +1, Review: QA +1, Review: UX +1

#1337 Adds releases history JSON endpoint
  tests/publisher/snaps/test_release_history_json.py
  tests/publisher/snaps/tests_revision.py
  webapp/api/dashboard.py
  webapp/publisher/snaps/views.py
Labels: Review: Code needed, Review: QA needed

#1340 Remove unnecessary broken SCSS
  static/sass/_patterns_carousel.scss
Labels: Review: Code +1, Review: QA +1

#1344 Update revisions list after the release
  static/js/publisher/release.js
  static/js/publisher/release/historyPanel.js
  static/js/publisher/release/releasesController.js
  static/js/publisher/release/releasesState.js
  static/js/publisher/release/releasesTable.js
  static/js/publisher/release/revisionsList.js
Labels: Review: Code +1, Review: QA +1

#1353 Correctly counts pending releases (skips already released revisions)
  static/js/publisher/release/releasesController.js
Labels: Review: Code +1, Review: QA +1

#1354 Fix badges
  README.md
Labels: Review: Code +1

#1349 Tweaks markup for Snap Store buttons
  templates/publisher/publicise.html
Labels: Review: Code +1, Review: QA +1

#1351 Shows only unreleased revisions when 'Add revision' is clicked
  static/js/publisher/release/historyPanel.js
  static/js/publisher/release/releasesState.js
  static/js/publisher/release/releasesTable.js
  static/js/publisher/release/revisionsList.js
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#1361 Shows pending releases in history
  static/js/publisher/release/historyPanel.js
  static/js/publisher/release/releasesState.js
  static/js/publisher/release/releasesTable.js
  static/js/publisher/release/revisionsList.js
  static/sass/_snapcraft_release.scss
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#1363 Show all uploaded architectures in releases table
  static/js/publisher/release/releasesController.js
  static/js/publisher/release/releasesState.js
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#1339 Added snippet for uk experiment
  templates/index.html
Labels: Review: Code needed, Review: QA needed

#1368 Remove experiment and add directly to template
  templates/index.html
Labels: Review: Code needed, Review: QA needed

#1369 Fix promoting channel over already pending release
  static/js/publisher/release/releasesController.js
  static/js/publisher/release/releasesState.js
Labels: Review: Code +1, Review: QA +1

#1370 Update macaroon package
  webapp/authentication.py
Labels: Review: Code +1, Review: QA +1

#1366 Make the Python pitch more concise
  templates/home/_fsf_python.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#1372 Use pipes instead of chevrons for the fsf descriptions
  templates/home/_fsf_go.html
  templates/home/_fsf_node.html
  templates/home/_fsf_pre-built.html
  templates/home/_fsf_python.html
  templates/home/_fsf_ruby.html
  webapp/first_snap/content/golang/package.yaml
  webapp/first_snap/content/python/package.yaml
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#1374 Unclosed script tag
  templates/index.html
Labels: Review: Code needed

#1376 Update channel map to incorporate default track + safest risk level + version
  templates/store/snap-details.html
  tests/store/tests_public_logic.py
  webapp/store/logic.py
  webapp/store/views.py
Labels: Review: Code +1, Review: QA +1

#1381 Configure jest to collect coverage data
  .gitignore
  package.json
Labels: Review: Code +1, Review: QA +1

#1375 Release UI - introduce Redux to keep the revisions list
  .babelrc
  .eslintrc.js
  package.json
  static/js/publisher/release.js
  static/js/publisher/release/historyPanel.js
  static/js/publisher/release/reducers/index.js
  static/js/publisher/release/releasesController.js
  static/js/publisher/release/releasesTable.js
  static/js/publisher/release/revisionsList.js
  yarn.lock
Labels: Review: Code +1, Review: QA +1

#1371 Remove auto-formatting in pre-commit hook, only lint to fail on error
  package.json
  yarn.lock
Labels: Review: Code +1, Review: QA +1

#1382 Remove useless character
  templates/publisher/publicise.html
Labels: Review: Code +1, Review: QA +1
