Repository canonical/snapcraft.io, pull requests merged in 2018-09, with the labels that each got.

#1053 Use real channel map data
  static/js/publisher/release.js
  static/js/publisher/release/revisionsTable.js
Labels: Review: Code +1, Review: QA +1

#1063 Only initialize blog series if element is present
  templates/blog/article.html
  webapp/blog/logic.py
  webapp/blog/views.py
Labels: Review: Code +1, Review: QA +1

#1065 Add hook precommit
  .circleci/config.yml
  package.json
  requirements.txt
  tests/blog/tests_index.py
  tests/metrics/tests_metrics.py
  tests/publisher/endpoint_testing.py
  tests/publisher/snaps/tests_get_metrics.py
  tests/publisher/snaps/tests_listing.py
  tests/publisher/snaps/tests_post_binary_metadata.py
  tests/publisher/snaps/tests_post_listing.py
  tests/publisher/snaps/tests_revision.py
  tests/publisher/tests_account_details.py
  tests/publisher/tests_account_logout.py
  tests/publisher/tests_account_snaps.py
  tests/publisher/tests_agreement.py
  tests/publisher/tests_publisher.py
  tests/publisher/tests_publisher_logic.py
  tests/publisher/tests_register_name.py
  tests/publisher/tests_username.py
  tests/snapcraft/tests_public.py
  tests/store/tests_public_logic.py
  tests/tests_requests.py
  tests/tests_requests_cache.py
  webapp/api/__init__.py
  webapp/api/blog.py
  webapp/api/dashboard.py
  webapp/api/exceptions.py
  webapp/api/requests.py
  webapp/api/store.py
  webapp/app.py
  webapp/authentication.py
  webapp/blog/logic.py
  webapp/blog/views.py
  webapp/config.py
  webapp/configs/limenet.py
  webapp/configs/snapcraft.py
  webapp/decorators.py
  webapp/handlers.py
  webapp/login/macaroon.py
  webapp/login/views.py
  webapp/metrics/helper.py
  webapp/metrics/metrics.py
  webapp/publisher/snaps/logic.py
  webapp/publisher/snaps/views.py
  webapp/publisher/views.py
  webapp/snapcraft/views.py
  webapp/store/logic.py
  webapp/store/views.py
  webapp/template_utils.py
  yarn.lock
Labels: Review: QA +1

#1062 d3 version of account metrics
  package.json
  rollup.config.js
  static/js/publisher/metrics/graphs/activeDevices.js
  static/js/publisher/metrics/graphs/helpers.js
  static/js/publisher/metrics/metrics.js
  static/js/publisher/metrics/tooltips.js
  static/sass/_snapcraft_metrics.scss
  templates/publisher/metrics.html
  webapp/metrics/helper.py
  yarn.lock
Labels: Review: Code +1, Review: QA +1

#1061 Use licenses from spdx github
  .gitignore
  package.json
  tests/publisher/endpoint_testing.py
  tests/publisher/snaps/tests_listing.py
  webapp/helpers.py
  webapp/publisher/snaps/views.py
Labels: Review: Code +1, Review: QA +1

#1068 Don't show related posts if there are none
  static/js/public/snap-details/blog-posts.js
Labels: Review: Code +1, Review: QA +1

#1060 Add release post endpoint
  tests/publisher/endpoint_testing.py
  tests/publisher/snaps/tests_post_release.py
  webapp/api/dashboard.py
  webapp/publisher/snaps/views.py
Labels: Review: Code +1, Review: QA +1

#1066 Blog categories
  .env
  static/sass/_patterns_card.scss
  templates/blog/index.html
  templates/partials/blog-card.html
  tests/blog/tests_index.py
  webapp/api/blog.py
  webapp/blog/logic.py
  webapp/blog/views.py
  webapp/config.py
  webapp/configs/snapcraft.py
Labels: Review: Code needed, Review: QA needed, Review: UX +1

#1075 Add scope=wide for featured snaps
  webapp/api/store.py
Labels: Review: Code +1, Review: QA +1

#1070 Don't show images on blog list page
  tests/blog/tests_index.py
  webapp/blog/views.py
Labels: Review: Code +1, Review: QA +1

#1078 Redirect if user has no usernames
  webapp/login/views.py
Labels: Review: Code +1, Review: QA +1

#1081 Remove RELEASE_UI_ENABLED feature flag
  .env
  static/js/publisher/release/revisionsTable.js
  templates/publisher/release-history.html
  webapp/configs/snapcraft.py
  webapp/publisher/snaps/views.py
Labels: Review: Code needed, Review: QA needed

#1083 Ignore branch releases
  static/js/publisher/release.js
Labels: Review: Code +1, Review: QA +1

#1088 Updated copy and copydoc link on store page
  templates/partials/search-bar.html
  templates/store/search.html
  templates/store/store.html
Labels: Review: Code +1, Review: QA +1

#1064 Job link
  static/sass/_global-nav.scss
  static/sass/styles.scss
  templates/_header.html
  templates/partials/hiring-banner.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#1086 Add missing custom licenses
  webapp/helpers.py
Labels: Review: Code +1, Review: QA +1

#1093 Metrics selector fix
  static/js/publisher/metrics/graphs/activeDevices.js
  templates/publisher/metrics.html
Labels: Review: Code +1, Review: QA +1

#1091 Add nps notification
  static/sass/_snapcraft_p-notifications.scss
  static/sass/styles.scss
  templates/index.html
  webapp/snapcraft/views.py
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#1106 Remove feature snaps api call from homepage
  tests/snapcraft/tests_public.py
  webapp/snapcraft/views.py
Labels: Review: Code +1, Review: QA +1

#1085 Release unreleased revisions
  static/js/publisher/release.js
  static/js/publisher/release/releasesController.js
  static/js/publisher/release/revisionsList.js
  static/js/publisher/release/revisionsTable.js
  static/sass/_snapcraft_release.scss
  templates/publisher/release-history.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#1108 Use rollup watch
  package.json
  rollup.config.js
Labels: Review: Code +1, Review: QA +1

#1101 Massive redirects
  tests/publisher/snaps/tests_get_metrics.py
  tests/publisher/snaps/tests_listing.py
  tests/publisher/snaps/tests_post_binary_metadata.py
  tests/publisher/snaps/tests_post_listing.py
  tests/publisher/snaps/tests_post_release.py
  tests/publisher/snaps/tests_revision.py
  tests/publisher/tests_account_snaps.py
  tests/publisher/tests_publisher.py
  tests/publisher/tests_register_name.py
  webapp/app.py
  webapp/publisher/snaps/views.py
  webapp/publisher/views.py
  webapp/store/views.py
Labels: Review: Code +1, Review: QA +1

#1114 Add username listing page
  templates/publisher/listing.html
  templates/store/_category-partial.html
  tests/publisher/snaps/tests_listing.py
  webapp/publisher/snaps/views.py
Labels: Review: Code needed, Review: QA needed

#1105 Fixed styling for global nav
  static/sass/_global-nav.scss
  static/sass/_snapcraft_p-navigation.scss
  static/sass/styles.scss
Labels: Review: Code +1, Review: Design +1

#1118 Add username on error
  tests/publisher/snaps/tests_post_listing.py
  webapp/publisher/snaps/views.py
Labels: Review: Code +1, Review: QA +1

#1121 Enable access log and remove sentry dependency
  entrypoint
  webapp/app.py
  webapp/extensions.py
Labels: Review: Code +1, Review: QA +1

#1122 Optimise the blog page and generated CSS
  package.json
  static/sass/_snapcraft_p-verified.scss
  templates/_layout-brandstore.html
  templates/_layout.html
  templates/partials/blog-card.html
  webapp/blog/views.py
Labels: Review: Code +1, Review: QA +1

#1117 Don't download licenses if file already here
  package.json
Labels: Review: Code +1, Review: QA +1

#1120 Release UI: promote channel
  static/js/publisher/release/promoteButton.js
  static/js/publisher/release/releasesController.js
  static/js/publisher/release/revisionsList.js
  static/js/publisher/release/revisionsTable.js
  static/sass/_snapcraft_release.scss
Labels: Review: Code +1, Review: QA +1

#1129 Ensure images fit on /blog
  static/sass/_utilities_crop.scss
Labels: Review: Code +1, Review: QA +1

#1127 Ensure correct nav is highlighted for the new endpoints
  webapp/template_utils.py
Labels: Review: Code +1, Review: QA +1

#1139 Rollup upgrade
  package.json
  yarn.lock
Labels: Review: Code +1, Review: QA +1

#1143 Add API v2 staging URLs to README
  README.md
Labels: Review: Code +1, Review: QA +1

#1146 Add missing metadata to templates
  tests/publisher/snaps/tests_listing.py
  tests/publisher/snaps/tests_post_listing.py
  tests/publisher/snaps/tests_post_settings.py
  tests/publisher/snaps/tests_settings.py
  webapp/publisher/snaps/views.py
Labels: Review: Code +1, Review: QA +1

#1150 Replace momentjs with date-fns
  package.json
  rollup.config.js
  static/js/public/snap-details/channelMap.js
  static/js/publisher/release/revisionsList.js
  yarn.lock
Labels: Review: Code +1, Review: QA +1

#1152 Ensure the settings revert button works
  templates/publisher/settings.html
Labels: Review: Code +1, Review: QA +1

#1154 Add robots.txt endpoint
  webapp/snapcraft/views.py
Labels: Review: Code +1, Review: QA +1
