Repository canonical/snapcraft.io, pull requests merged in 2019-04, with the labels that each got.

#1760 Move snap owner banner to the top of the page
  templates/store/snap-details.html
Labels: Review: Code needed, Review: QA +1

#1764 Correctly check published status in revision not snap data
  templates/publisher/account-snaps.html
Labels: Review: Code +1, Review: QA +1

#1769 Manage fileInput inputs outside of react lifecycle. Don't clear on ch…
  static/js/publisher/form/fileInput.js
  static/js/publisher/form/media.js
Labels: Review: Code +1, Review: QA +1

#1768 Fix multiple code on a line
  tests/tests_markdown_parser.py
  webapp/markdown.py
Labels: Review: Code +1, Review: QA +1

#1757 Drag to upload files
  static/js/publisher/form/fileInput.js
  static/js/publisher/form/fileInput.test.js
  static/js/publisher/form/media.js
  static/js/publisher/form/media.test.js
  static/sass/_snapcraft_market.scss
  static/sass/_snapcraft_market_screenshots.scss
  static/sass/_snapcraft_p-file-input.scss
  static/sass/styles.scss
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#1778 Allow banners
  static/js/libs/fileValidation.js
  static/js/libs/fileValidation.test.js
Labels: Review: Code +1, Review: QA +1

#1792 Better blog post filtering
  tests/blog/tests_logic.py
  webapp/blog/logic.py
  webapp/blog/views.py
Labels: Review: Code +1, Review: QA +1

#1793 Update route mappings for new endpoints
  tests/tests_templates_utils.py
  webapp/template_utils.py
Labels: Review: Code +1, Review: QA +1

#1795 Icon to react component
  static/js/libs/fileValidation.js
  static/js/libs/fileValidation.test.js
  static/js/publisher/form.js
  static/js/publisher/form.test.js
  static/js/publisher/form/fileInput.js
  static/js/publisher/form/icon.js
  static/js/publisher/form/icon.test.js
  static/js/publisher/market/initIcon.js
  static/js/publisher/market/initIcon.test.js
  static/js/publisher/market/restrictions.js
  static/sass/_snapcraft_market.scss
  static/sass/_snapcraft_market_screenshots.scss
  static/sass/_snapcraft_p-file-input.scss
  templates/publisher/listing.html
  webapp/publisher/snaps/logic.py
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#1800 Upgrade node-sass
  package.json
  yarn.lock
Labels: Review: Code +1, Review: QA +1

#1796 Detect OS in first snap flow install step
  static/js/public/first-snap-flow.js
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#1794 Move 'Continue' button in FSF language selector
  templates/home/_fsf_c.html
  templates/home/_fsf_electron.html
  templates/home/_fsf_go.html
  templates/home/_fsf_java.html
  templates/home/_fsf_moos.html
  templates/home/_fsf_node.html
  templates/home/_fsf_pre-built.html
  templates/home/_fsf_python.html
  templates/home/_fsf_ros.html
  templates/home/_fsf_ros2.html
  templates/home/_fsf_ruby.html
  templates/home/_fsf_rust.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#1797 Don't loop asciinema on details pages
  templates/partials/_video.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#1804 Show latest release in snap list
  templates/publisher/account-snaps.html
  tests/publisher/tests_account_snaps.py
  tests/publisher/tests_api_snaps.py
  tests/publisher/tests_publisher_logic.py
  webapp/publisher/snaps/logic.py
Labels: Review: Code +1, Review: QA +1

#1806 Add publisher screenshots to first snap flow publish step
  templates/first-snap/push.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#1809 Newsletter signup on blog
  static/js/libs/formHelpers.js
  static/js/public/newsletter.js
  static/js/public/public.js
  static/js/public/snap-details/reportSnap.js
  static/sass/_patterns_card.scss
  templates/blog/article.html
  templates/blog/index.html
  templates/partials/_newsletter-signup.html
  tests/blog/tests_index.py
  webapp/api/blog.py
  webapp/blog/views.py
  webapp/handlers.py
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#1811 Add accordion to first snap flow publish step
  static/js/public/accordion.js
  static/js/public/public.js
  static/sass/_patterns_first-snap-flow.scss
  static/sass/styles.scss
  templates/first-snap/push.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#1824 Update repository links with new organisation
  README.md
  static/sass/_patterns_card.scss
  static/sass/_patterns_maas_modal.scss
  static/sass/_utilities_crop.scss
  templates/503.html
  templates/50X.html
  templates/_footer.html
  webapp/metrics/helper.py
  webpack.config.js
Labels: Review: Code +1

#1828 more snaps on brand store
  static/sass/_snapcraft-p_grid.scss
  static/sass/styles.scss
  templates/brand-store/store.html
  webapp/configs/limenet.py
  webapp/configs/sdrsatcom.py
  webapp/store/views.py
Labels: Review: Code +1, Review: QA +1

#1826 Include safest risk in default track channel on SVG badge
  webapp/store/snap_details_views.py
Labels: Review: Code +1, Review: QA +1

#1829 Add JSON endpoint to register snap name
  tests/publisher/tests_register_name_json.py
  webapp/publisher/snaps/views.py
Labels: Review: Code +1

#1830 Fixed ordering on snaps with dotted version numbers
  static/js/publisher/release/components/releasesHeading.js
Labels: Review: Code +1, Review: QA +1

#1847 Add service name in logs to help logging parsing
  webapp/app.py
Labels: Review: Code +1, Review: QA +1

#1852 Updated KDE contact details
  webapp/store/content/publishers/kde.yaml
Labels: Review: Code +1, Review: QA +1

#1855 Removed livestream notification
  codecov.yaml
  requirements.txt
  templates/index.html
  templates/partials/livestream-notification.html
  templates/partials/search-bar.html
  webapp/handlers.py
  webapp/template_utils.py
Labels: Review: Code +1

#1859 MOOS FSF changes after old pr closed and Kyle approved moosdb example
  templates/home/_fsf_moos.html
  templates/partials/fsf_language.html
  webapp/first_snap/content/moos/build.yaml
  webapp/first_snap/content/moos/package.yaml
  webapp/first_snap/content/moos/test.yaml
Labels: Review: Code needed, Review: QA +1

#1862 Updated index homepage with links to relevant snaps from logos
  templates/index.html
Labels: Review: Code +1, Review: QA +1

#1866 Updated showcase to millions image
  templates/index.html
Labels: Review: Design +1, Review: QA +1

#1696 Upload and edit banners
  static/js/libs/fileValidation.js
  static/js/libs/fileValidation.test.js
  static/js/publisher/form.js
  static/js/publisher/form/AccordionHelp.js
  static/js/publisher/form/AccordionHelp.test.js
  static/js/publisher/form/banner.js
  static/js/publisher/form/banner.test.js
  static/js/publisher/form/fileInput.js
  static/js/publisher/form/icon.js
  static/js/publisher/form/media.js
  static/js/publisher/form/media.test.js
  static/js/publisher/form/mediaItem.js
  static/js/publisher/form/mediaList.js
  static/js/publisher/market/initBanner.js
  static/js/publisher/market/initBanner.test.js
  static/js/publisher/market/restrictions.js
  static/sass/_snapcraft_market.scss
  static/sass/_snapcraft_market_screenshots.scss
  static/sass/_snapcraft_p-file-input.scss
  static/sass/_snapcraft_p-form-help-text.scss
  static/sass/_snapcraft_patterns_icons.scss
  templates/publisher/listing.html
  tests/publisher/snaps/tests_listing.py
  webapp/publisher/snaps/logic.py
  webapp/publisher/snaps/views.py
  yarn.lock
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#1874 Embedded channels fix
  static/sass/styles-embedded.scss
  templates/store/snap-embedded-card.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1, Review: UX +1

#1876 Make sure size of embedded card in publicise page is updated
  static/js/publisher/publicise.js
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#1838 Featured snap background colours
  package.json
  static/js/config/swiper.config.js
  static/js/public/store-categories.js
  static/sass/_patterns_featured-snap.scss
  static/sass/_patterns_media-object--snap.scss
  static/sass/_snapcraft-p_grid.scss
  static/sass/_snapcraft_p-featured-snap.scss
  static/sass/styles.scss
  templates/store/_category-partial.html
  templates/store/_empty-category-partial.html
  templates/store/_generated-featured-snap-partial.html
  templates/store/_media-object-snap-partial.html
  templates/store/categories/iot.html
  templates/store/publisher-details.html
  templates/store/search.html
  templates/store/store.html
  webapp/snapcraft/views.py
  webapp/store/views.py
  yarn.lock
Labels: Review: Code +1, Review: Design +1, Review: QA +1, Review: UX +1

#1878 Update kde snaps (as icons have updated etc.)
  webapp/store/content/publishers/kde.yaml
Labels: Review: QA +1

#1880 Simple notification component and show error for releases
  templates/publisher/release-history.html
Labels: Review: Code +1, Review: QA +1
