Repository canonical/snapcraft.io, pull requests merged in 2019-02, with the labels that each got.

#1548 Removed google plus
  static/sass/_patterns_social-icons.scss
  templates/_footer.html
  templates/_layout-brandstore.html
  templates/_layout.html
Labels: Review: Code +1, Review: QA +1

#1552 Updated heading
  templates/index.html
Labels: Review: Code +1, Review: QA +1

#1561 Replace usabilla with intercom
  templates/first-snap/build.html
  templates/first-snap/install-snapcraft.html
  templates/first-snap/language.html
  templates/first-snap/package.html
  templates/first-snap/push.html
  templates/first-snap/test.html
Labels: Review: Code +1

#1577 Settings page uses old fixed heading style
  templates/publisher/settings.html
Labels: Review: Code +1, Review: QA +1

#1573 Update state commaSeperatedStringToArray function to trim values
  static/js/publisher/state.js
  static/js/publisher/state.test.js
Labels: Review: Code +1, Review: QA +1

#1574 Remove metrics related code from settings page
  tests/publisher/snaps/tests_post_settings.py
  webapp/publisher/snaps/logic.py
  webapp/publisher/snaps/views.py
Labels: Review: Code +1, Review: QA +1

#1581 Order channels by track/risk/branch
  static/js/libs/channels.js
  static/js/libs/channels.test.js
  static/js/publisher/metrics/graphs/activeDevices.js
  static/js/publisher/metrics/metrics.js
  static/sass/_snapcraft_metrics.scss
  templates/publisher/metrics.html
  webapp/helpers.py
  webapp/publisher/snaps/views.py
  webapp/store/views.py
Labels: Review: Code +1, Review: QA +1

#1569 Remove livestream code
  codecov.yaml
  requirements.txt
  templates/index.html
  templates/partials/livestream-notification.html
  templates/partials/search-bar.html
  tests/tests_templates_utils.py
  webapp/handlers.py
  webapp/template_utils.py
Labels: Review: Code +1, Review: QA +1

#1571 Fsf go
  templates/home/_fsf_go.html
  webapp/first_snap/content/golang/package.yaml
Labels: Review: Code +1, Review: QA +1

#1587 Copyable code blocks for publicise snap page
  templates/publisher/publicise.html
Labels: Review: Code +1, Review: QA +1

#1589 Sort categories for listing page
  webapp/publisher/snaps/views.py
Labels: Review: Code +1, Review: QA +1

#1582 Fsf c
  templates/home/_fsf_c.html
  webapp/first_snap/content/c/build.yaml
  webapp/first_snap/content/c/package.yaml
  webapp/first_snap/content/c/test.yaml
Labels: Review: Code +1, Review: QA +1

#1583 FSF Node added
  templates/home/_fsf_node.html
  webapp/first_snap/content/node/build.yaml
  webapp/first_snap/content/node/package.yaml
  webapp/first_snap/content/node/test.yaml
Labels: Review: Code +1, Review: QA +1

#1558 First snap flow for java
  templates/home/_fsf_java.html
  webapp/first_snap/content/java/build.yaml
  webapp/first_snap/content/java/package.yaml
  webapp/first_snap/content/java/test.yaml
Labels: Review: Code +1, Review: QA +1

#1545 Preview listing page
  package.json
  static/js/public/snap-details/screenshots.js
  static/js/publisher/form.js
  static/js/publisher/form.test.js
  static/js/publisher/market/lightbox.js
  static/js/publisher/market/screenshots.js
  static/js/publisher/market/screenshots.test.js
  static/js/publisher/market/storageCommands.js
  static/js/publisher/market/storageCommands.test.js
  static/js/publisher/preview.js
  static/js/publisher/publisher.js
  static/sass/_snapcraft_snap-details.scss
  templates/publisher/listing.html
  templates/store/snap-details.html
  tests/publisher/snaps/test_post_preview.py
  webapp/publisher/snaps/preview_data.py
  webapp/publisher/snaps/views.py
  webapp/store/logic.py
  webapp/store/views.py
  yarn.lock
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#1591 Correct a typo: the snapcraft.yaml is in the project root
  templates/first-snap/package.html
Labels: Review: Code +1, Review: QA +1

#1592 first snap flow: fix Base appearing when the language doesn't use them
  templates/first-snap/package.html
Labels: Review: Code +1, Review: QA +1

#1575 Remove snapcraft logo from empty default icon
  templates/brand-store/search.html
  templates/brand-store/store.html
  templates/publisher/account-snaps.html
  templates/publisher/listing.html
  templates/store/_category-partial.html
  templates/store/categories/iot.html
  templates/store/search.html
  templates/store/snap-details.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#1570 Add list of categories to snap details page
  templates/store/snap-details.html
  tests/store/tests_details.py
  webapp/api/store.py
  webapp/store/logic.py
  webapp/store/views.py
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#1598 Don't try and add previewForm eventListener on settings page
  static/js/publisher/form.js
Labels: Review: Code +1, Review: QA +1

#1608 Ignore GA script if dataLayer is undefined
  static/js/base/ga.js
Labels: Review: Code +1

#1614 Remove unnecessary print call
  webapp/publisher/snaps/views.py
Labels: Review: Code +1

#1615 Improve categories, and fix some issues
  static/js/libs/arrays.js
  static/js/libs/arrays.test.js
  static/js/publisher/form.js
  static/js/publisher/form.test.js
  static/js/publisher/market/categories.js
  static/js/publisher/market/categories.test.js
  static/js/publisher/state.js
  templates/publisher/listing.html
  webapp/publisher/snaps/logic.py
  webapp/publisher/snaps/views.py
Labels: Review: Code +1, Review: QA +1

#1616 Tidied form tests, spy rather then mock external dep
  static/js/publisher/form.test.js
Labels: Review: Code +1, Review: QA +1

#1618 Add simple snap embedded card template
  static/sass/styles-embedded.scss
  templates/_layout-embedded.html
  templates/store/snap-embedded-card.html
Labels: Review: Code +1, Review: QA +1

#1617 Updated copy for homepage
  templates/index.html
Labels: Review: Code +1, Review: QA +1

#1590 Add 'unlisted' to snap privacy settings
  static/js/publisher/form.js
  static/js/publisher/state.js
  templates/publisher/settings.html
  tests/publisher/snaps/tests_post_settings.py
  tests/publisher/snaps/tests_settings.py
  webapp/publisher/snaps/logic.py
  webapp/publisher/snaps/views.py
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#1620 Ensure categories wrap on mobile
  static/sass/styles.scss
  templates/store/_snap-header-information.html
  templates/store/snap-details.html
Labels: Review: Code +1, Review: QA +1

#1628 Updated copy on notification displead on detail page of a snap you own
  templates/store/snap-details.html
Labels: Review: Code needed, Review: QA needed

#1627 Refactor snap details views to own view file
  webapp/store/snap_details_views.py
  webapp/store/views.py
Labels: Review: Code +1, Review: QA +1

#1631 Fix python tests warning
  tests/tests_badge_counter.py
Labels: Review: Code +1, Review: QA +1

#1632 Add basic tests for search endpoint
  tests/store/tests_search.py
Labels: Review: Code +1, Review: QA +1

#1639 Remove unnecessary js modules directory
  package.json
  static/js/modules/README.md
Labels: Review: QA needed
