Repository canonical/snapcraft.io, pull requests merged in 2019-03, with the labels that each got.

#1645 Add preconnect to GA, Marketo, Assets Server
  templates/_layout-brandstore.html
  templates/_layout-embedded.html
  templates/_layout.html
Labels: Project Fuse ⚡️, Review: Code +1, Review: QA +1

#1654 Remove cssnano dependency
  package.json
  yarn.lock
Labels: Review: Code +1, Review: QA +1

#1633 Add name dispute screens
  templates/publisher/register-name-dispute-success.html
  templates/publisher/register-name-dispute.html
  templates/publisher/register-snap.html
  tests/publisher/tests_register_name_dispute.py
  webapp/api/dashboard.py
  webapp/publisher/snaps/views.py
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#1670 Convert NodeList to array in first snap flow
  static/js/public/first-snap-flow.js
Labels: Review: Code +1, Review: QA +1

#1677 Update home page banner to new slanted strip design
  static/sass/_patterns_strip_slanted.scss
  static/sass/styles.scss
  templates/index.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#1676 Improve responsive styles for embedded card
  static/sass/styles-embedded.scss
  templates/store/snap-embedded-card.html
Labels: Review: Code +1, Review: QA needed, Review: UX +1

#1638 Cache static assets longer
  templates/_layout.html
  webapp/config.py
  webapp/handlers.py
Labels: Project Fuse ⚡️, Review: QA needed

#1655 List disputed names
  static/sass/_snapcraft_dispute-list.scss
  static/sass/styles.scss
  templates/publisher/account-snaps.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#1684 Don't break if total not set
  templates/store/search.html
  tests/store/tests_search.py
  webapp/store/views.py
Labels: Review: Code +1, Review: QA +1

#1681 Convert screenshots to React and implement new design
  package.json
  static/js/publisher/form.js
  static/js/publisher/form/media.js
  static/js/publisher/form/media.test.js
  static/js/publisher/form/mediaItem.js
  static/js/publisher/market/initMedia.js
  static/js/publisher/market/initMedia.test.js
  static/js/publisher/market/screenshots.js
  static/js/publisher/market/screenshots.test.js
  static/sass/_snapcraft_market_screenshots.scss
  templates/publisher/listing.html
  yarn.lock
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#1700 Convert dict_keys to list
  webapp/store/snap_details_views.py
Labels: Review: Code +1, Review: QA +1

#1683 Allow removing of snap icon
  static/js/publisher/form.js
  static/js/publisher/form.test.js
  static/sass/_snapcraft_market.scss
  templates/publisher/listing.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#1701 Image restrictions
  static/js/publisher/form/media.js
  static/js/publisher/form/media.test.js
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#1687 JetBrains publisher page
  static/sass/_patterns_featured-snap.scss
  static/sass/_patterns_fluid-grid.scss
  static/sass/_patterns_media-object--snap.scss
  static/sass/_snapcraft_details_heading.scss
  static/sass/styles.scss
  templates/index.html
  templates/store/_empty-category-partial.html
  templates/store/_media-object-snap-partial.html
  templates/store/categories/iot.html
  templates/store/publisher-details.html
  tests/store/tests_publisher.py
  webapp/config.py
  webapp/store/content/publishers/jetbrains.yaml
  webapp/store/views.py
  yarn.lock
Labels: Review: Code +1, Review: Design needed, Review: QA +1, Review: UX needed

#1694 Update to new markdown requirements
  templates/publisher/listing.html
  tests/tests_markdown_parser.py
  webapp/markdown.py
  webapp/publisher/snaps/views.py
  webapp/store/snap_details_views.py
Labels: Review: Code +1, Review: QA +1

#1717 Remove blog logic
  templates/store/publisher-details.html
Labels: Review: Code +1, Review: QA +1

#1728 Limit screenshots to 5 on the frontend
  webapp/store/logic.py
Labels: Review: Code +1, Review: QA +1

#1641 FSF ROS
  templates/home/_fsf_ros.html
  templates/partials/fsf_language.html
  webapp/first_snap/content/ros/build.yaml
  webapp/first_snap/content/ros/package.yaml
  webapp/first_snap/content/ros/test.yaml
Labels: Review: Code -1

#1733 Make the second FSF name warning less redundant
  webapp/first_snap/content/c/package.yaml
  webapp/first_snap/content/golang/package.yaml
  webapp/first_snap/content/java/package.yaml
  webapp/first_snap/content/node/package.yaml
  webapp/first_snap/content/pre-built/package.yaml
  webapp/first_snap/content/python/package.yaml
  webapp/first_snap/content/ros2/package.yaml
  webapp/first_snap/content/ruby/package.yaml
  webapp/first_snap/content/rust/package.yaml
Labels: Review: Code +1, Review: QA +1

#1737 Pin Werkzeug version
  requirements.txt
Labels: Review: Code +1, Review: QA +1

#1738 Fix disabled Revert button on publisher listing page
  static/js/publisher/form.js
  static/js/publisher/form.test.js
Labels: Review: Code +1, Review: QA +1

#1741 Consistently hide disabled screenshot navigation buttons
  static/sass/_patterns_maas_modal.scss
Labels: Review: Code +1, Review: QA +1

#1742 Fix slanted background not to collide with content on huge screens
  static/sass/_patterns_strip_slanted.scss
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#1735 Updated layout for listing page
  static/sass/_snapcraft_market.scss
  templates/publisher/listing.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#1740 Move image up in Snap Store banner on mobile
  templates/store/store.html
Labels: Review: Code +1, Review: QA +1

#1724 Make whole content of a embedded card clickable as a link to the store
  static/sass/styles-embedded.scss
  templates/store/snap-embedded-card.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#1712 File validation
  static/js/libs/fileValidation.js
  static/js/libs/fileValidation.test.js
  static/js/publisher/form/fileInput.js
  static/js/publisher/form/fileInput.test.js
  static/js/publisher/form/media.js
  static/js/publisher/form/media.test.js
  static/js/publisher/market/initMedia.js
  static/js/publisher/market/restrictions.js
  yarn.lock
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#1750 FSF Rust description changes
  templates/home/_fsf_rust.html
Labels: Review: Code needed

#1747 FSF Python description changes
  templates/home/_fsf_python.html
Labels: Review: Code needed, Review: QA needed, Review: UX needed

#1746 FSF Go description changes
  templates/home/_fsf_go.html
Labels: Review: Code needed, Review: QA needed, Review: UX needed

#1753 FSF Node small description changes
  templates/home/_fsf_node.html
Labels: Review: Code +1, Review: QA +1

#1752 FSF Java small description changes
  templates/home/_fsf_java.html
Labels: Review: Code +1, Review: QA +1

#1751 FSF C small description changes
  templates/home/_fsf_c.html
Labels: Review: Code +1, Review: QA +1

#1756 Hide embeddable card modal in preview
  templates/store/snap-details.html
  templates/store/snap-details/_report_snap_modal.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#1755 Removes “by” from publisher name
  templates/store/_snap-header-information.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#1734 Move the FSF up on the page
  templates/index.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1
