Repository canonical/snapcraft.io, pull requests merged in 2019-08, with the labels that each got.

#2126 Build list snap builds
  requirements.txt
  static/sass/_snapcraft_snap-builds.scss
  static/sass/styles.scss
  templates/publisher/_header.html
  templates/publisher/build-enable.html
  templates/publisher/build-list.html
  webapp/api/launchpad.py
  webapp/models/snap.py
  webapp/publisher/snaps/views.py
Labels: Review: Code +1

#2145 Fix annotated code styles in first snap flow
  static/sass/_patterns_annotated_code.scss
Labels: Review: Code +1, Review: QA +1

#2146 Vanilla layout fixes for docs
  static/sass/_snapcraft_p-docs.scss
  templates/docs/base.html
Labels: Review: Code +1, Review: QA +1

#2142 Vanilla snap details page
  static/sass/_patterns_distro_banner.scss
  static/sass/_snapcraft_details_heading.scss
  static/sass/_snapcraft_p-code-copyable.scss
  templates/partials/_publisher-featured-snap.html
  templates/partials/_snap-details-video-layout.html
  templates/store/snap-details.html
  templates/store/snap-details/_channel_map.html
  templates/store/snap-details/_distro-instructions-for-snap-support.html
  templates/store/snap-details/_embedded_card_modal.html
  templates/store/snap-details/_report_snap_modal.html
  templates/store/snap-distro-install.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1, Review: UX +1

#2147 Fix accordion steps in first snap flow
  static/sass/_patterns_first-snap-flow.scss
  templates/first-snap/package.html
  templates/first-snap/push.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#2148 Update pagination on blog to new pattern
  templates/blog/index.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#2163 Added title to docs so they appear on search results
  templates/docs/document.html
Labels: Review: Code +1, Review: QA +1

#2166 Fix tooltips positioning on metrics page
  templates/publisher/metrics.html
Labels: Review: Code +1, Review: QA +1

#2150 Publisher - Snap list
  static/sass/_patterns_table.scss
  static/sass/_snapcraft_snap-list.scss
  static/sass/styles.scss
  templates/publisher/account-snaps.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1, Review: UX +1

#2167 Publisher settings sticky bar consistent with listings
  static/sass/_snapcraft_market.scss
  templates/publisher/_header.html
  templates/publisher/listing.html
  templates/publisher/settings.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1, Review: UX +1

#2170 Update to vanilla-2.3.0
  package.json
  yarn.lock
Labels: Review: Code +1, Review: Design needed, Review: QA +1, Review: UX needed

#2181 Don't use hardcoded dates in test that compare to now()
  static/js/publisher/release/selectors/selectors.test.js
Labels: Review: Code +1

#2180 snaprcaft.yaml -> snapcraft.yaml
  webapp/first_snap/views.py
Labels: Review: Code +1, Review: QA +1

#2182 Fix td styles for headings in blog posts
  static/sass/_patterns_blog-post.scss
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#2184 Removed unsquash fs from all language guides
  webapp/first_snap/content/c/build.yaml
  webapp/first_snap/content/golang/build.yaml
  webapp/first_snap/content/java/build.yaml
  webapp/first_snap/content/moos/build.yaml
  webapp/first_snap/content/node/build.yaml
  webapp/first_snap/content/pre-built/build.yaml
  webapp/first_snap/content/python/build.yaml
  webapp/first_snap/content/ros/build.yaml
  webapp/first_snap/content/ros2/build.yaml
  webapp/first_snap/content/ruby/build.yaml
  webapp/first_snap/content/rust/build.yaml
Labels: Review: Code +1, Review: QA +1

#2187 Small fixes for Vanilla 2 footer
  static/sass/styles.scss
  templates/_footer.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#2190 Mind the gap
  static/sass/_snapcraft_p-navigation.scss
  yarn.lock
Labels: Review: Code +1, Review: QA +1

#2191 Fixes and updates around `u-fixed-width`
  static/js/public/fsf-language-select.js
  templates/first-snap/_layout_fsf.html
  templates/home/_fsf_c.html
  templates/home/_fsf_electron.html
  templates/home/_fsf_go.html
  templates/home/_fsf_java.html
  templates/home/_fsf_moos.html
  templates/home/_fsf_node.html
  templates/home/_fsf_pre-built.html
  templates/home/_fsf_python.html
  templates/home/_fsf_ros.html
  templates/home/_fsf_ros2.html
  templates/home/_fsf_ruby.html
  templates/home/_fsf_rust.html
  templates/publisher/account-details.html
  templates/publisher/account-snaps.html
  templates/publisher/listing.html
  templates/publisher/register-name-dispute.html
  templates/publisher/register-snap.html
  templates/publisher/request-reserved-name.html
  templates/publisher/username.html
  templates/store/publisher-details.html
  templates/store/search.html
  templates/store/snap-details.html
  templates/store/store.html
Labels: Review: Code +1, Review: QA +1

#2185 Command consistency
  templates/first-snap/_install-linux.html
  templates/first-snap/package.html
  webapp/first_snap/content/c/build.yaml
  webapp/first_snap/content/c/test.yaml
  webapp/first_snap/content/golang/build.yaml
  webapp/first_snap/content/golang/test.yaml
  webapp/first_snap/content/java/build.yaml
  webapp/first_snap/content/java/test.yaml
  webapp/first_snap/content/moos/build.yaml
  webapp/first_snap/content/moos/test.yaml
  webapp/first_snap/content/node/build.yaml
  webapp/first_snap/content/node/test.yaml
  webapp/first_snap/content/pre-built/build.yaml
  webapp/first_snap/content/pre-built/test.yaml
  webapp/first_snap/content/python/build.yaml
  webapp/first_snap/content/python/test.yaml
  webapp/first_snap/content/ros/build.yaml
  webapp/first_snap/content/ros/test.yaml
  webapp/first_snap/content/ros2/build.yaml
  webapp/first_snap/content/ros2/test.yaml
  webapp/first_snap/content/ruby/build.yaml
  webapp/first_snap/content/rust/build.yaml
  webapp/first_snap/content/rust/test.yaml
Labels: Review: Code +1, Review: QA +1

#2193 Vanillarise forms
  static/js/publisher/form/AccordionHelp.js
  static/js/publisher/form/banner.js
  static/js/publisher/form/media.js
  static/sass/_snapcraft_market.scss
  static/sass/_snapcraft_market_screenshots.scss
  templates/publisher/account-details.html
  templates/publisher/listing.html
  templates/publisher/settings.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1, Review: UX +1

#2192 Remove p-fluid-grid
  static/js/public/fsf-language-select.js
  static/js/publisher/form/mediaItem.js
  static/js/publisher/form/mediaList.js
  static/sass/_patterns_fluid-grid.scss
  static/sass/_snapcraft_custom-cols.scss
  static/sass/_snapcraft_market_screenshots.scss
  static/sass/styles.scss
  templates/first-snap/install-snapcraft.html
  templates/index.html
  templates/partials/fsf_language.html
  templates/snapcraft/build.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1, Review: UX +1

#2202 Fix navigation breakpoint
  static/sass/_search-form.scss
  static/sass/_snapcraft_distro-chart.scss
  static/sass/styles.scss
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#2203 Add new tour tooltip card pattern styles.
  static/sass/_snapcraft_tour.scss
  static/sass/styles.scss
  templates/index.html
Labels: Review: Code +1, Review: Design +1, Review: UX +1

#2206 Fix selectors throwing errors in Safari
  static/js/public/fsf-language-select.js
Labels: Review: Code +1, Review: QA +1

#2217 Add GA events to starting, skipping and finishing the tour
  static/js/publisher/tour/metricsEvents.js
  static/js/publisher/tour/tour.js
  static/js/publisher/tour/tourBar.js
  static/js/publisher/tour/tourOverlay.js
  static/js/publisher/tour/tourStepCard.js
Labels: Review: Code +1, Review: QA +1
