Repository canonical/snapcraft.io, pull requests merged in 2019-06, with the labels that each got.

#1948 Move all the YAML logic into helpers
  tests/first_snap/tests_views.py
  webapp/first_snap/views.py
  webapp/helpers.py
  webapp/snapcraft/logic.py
  webapp/store/snap_details_views.py
  webapp/store/views.py
Labels: Review: Code +1, Review: QA +1

#1947 Show better error message on incorrect aspect ratios
  static/js/libs/fileValidation.js
  static/js/libs/fileValidation.test.js
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#1956 Add builder blueprint
  templates/builder/index.html
  tests/builder/__init__.py
  tests/builder/test_views.py
  webapp/app.py
  webapp/builder/__init__.py
  webapp/builder/views.py
  webapp/snapcraft/views.py
Labels: Review: Code +1, Review: QA +1

#1970 If logged in, append fsf snap name with username
  templates/first-snap/package.html
  tests/first_snap/tests_views.py
  webapp/first_snap/views.py
Labels: Review: Code +1, Review: QA +1

#1971 Distro page navigation
  templates/_header_empty.html
  templates/_layout.html
  templates/store/snap-distro-install.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1, Review: UX +1

#1973 Add "more things..." to distro page
  templates/store/snap-distro-install.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#1981 Update CentOS background gradient
  webapp/store/content/distros/centos.yaml
Labels: Review: UX +1

#1983 Updates to distro page template
  templates/store/snap-distro-install.html
  webapp/store/snap_details_views.py
Labels: Review: UX +1

#1982 Add animated scroll to distro install instructions
  static/js/public/public.js
  static/js/public/scroll-to.js
  templates/store/snap-distro-install.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#1985 Update bleach to latest version
  requirements.txt
  webapp/publisher/snaps/views.py
Labels: Review: Code +1, Review: QA +1

#2008 Fix capitalisation of openSUSE
  webapp/store/content/distros/opensuse.yaml
Labels: Review: Code +1, Review: QA +1

#1990 Update visual style of release UI (in preparation for drag and drop)
  static/js/publisher/release/components/releasesTable.js
  static/js/publisher/release/components/releasesTableCell.js
  static/sass/_snapcraft_release.scss
Labels: Review: Code +1, Review: Design +1, Review: QA +1, Review: UX +1

#2002 Included install instructions specific for the distro here
  static/sass/_snapcraft-publisher.scss
  templates/store/snap-details.html
  templates/store/snap-details/_distro-instructions-for-snap-support.html
Labels: Review: Code +1, Review: QA +1

#2009 Fix capitalisation of openSUSE
  templates/store/snap-details/_distro-instructions-for-snap-support.html
Labels: Review: Code +1, Review: QA +1

#2011 Upgrade React for react-dnd compatibility
  yarn.lock
Labels: Review: Code +1, Review: QA +1

#2015 Updated snippet value adding a template function
  templates/store/snap-details/_channel_map.html
  templates/store/snap-distro-install.html
  tests/tests_templates_utils.py
  webapp/handlers.py
  webapp/template_utils.py
Labels: Review: Code +1, Review: QA +1

#1989 activeDevices module refactor, updated dashboard overview graph
  package.json
  static/js/libs/arrays.js
  static/js/libs/arrays.test.js
  static/js/publisher/metrics/axis.js
  static/js/publisher/metrics/graphs/activeDevices.js
  static/js/publisher/metrics/graphs/activeDevicesGraph/dataProcessing.js
  static/js/publisher/metrics/graphs/activeDevicesGraph/index.js
  static/js/publisher/metrics/graphs/activeDevicesGraph/rendering.js
  static/js/publisher/metrics/graphs/activeDevicesGraph/tooltips.js
  static/js/publisher/metrics/graphs/helpers.js
  static/js/publisher/metrics/graphs/snapInstalls.js
  static/js/publisher/metrics/metrics.js
  static/sass/_snapcraft-publisher.scss
  static/sass/_snapcraft_metrics.scss
  templates/publisher/account-snaps.html
  tests/publisher/tests_account_snaps_metrics.py
  webapp/metrics/helper.py
  webapp/store/content/publishers/kde.yaml
  yarn.lock
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#2013 Dispute reserved name
  templates/publisher/register-snap.html
  templates/publisher/request-reserved-name.html
  tests/publisher/tests_register_name.py
  tests/publisher/tests_reserved_name_dispute.py
  webapp/publisher/snaps/views.py
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#1898 Email preferences
  static/js/base/polyfills.js
  static/js/libs/shallowDiff.js
  static/js/libs/shallowDiff.test.js
  static/js/publisher/publisher.js
  static/js/publisher/submitEnabler.js
  static/js/publisher/submitEnabler.test.js
  templates/publisher/account-details.html
  tests/api/__init__.py
  tests/api/test_marketo_api.py
  tests/blog/tests_index.py
  tests/publisher/tests_account_details.py
  tests/publisher/tests_post_account_details.py
  webapp/api/marketo.py
  webapp/authentication.py
  webapp/blog/views.py
  webapp/first_snap/views.py
  webapp/helpers.py
  webapp/login/views.py
  webapp/publisher/snaps/logic.py
  webapp/publisher/views.py
  webapp/snapcraft/views.py
  webapp/store/logic.py
  webapp/store/snap_details_views.py
  webapp/store/views.py
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#2016 Added google site verification and removed embedded from indexing
  templates/_layout-brandstore.html
  templates/_layout-embedded.html
  templates/_layout.html
Labels: Review: Code +1, Review: QA +1

#2005 Allow youtu.be video urls
  static/js/publisher/preview.js
  tests/store/tests_public_logic.py
  webapp/store/logic.py
Labels: Review: Code +1, Review: QA +1

#2023 Move tracks dropdown to left side of heading
  static/js/publisher/release/components/releasesHeading.js
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#2024 White logos in distros
  static/sass/_patterns_distro_banner.scss
  templates/store/snap-distro-install.html
  webapp/store/content/distros/arch.yaml
  webapp/store/content/distros/centos.yaml
  webapp/store/content/distros/debian.yaml
  webapp/store/content/distros/elementary.yaml
  webapp/store/content/distros/fedora.yaml
  webapp/store/content/distros/kde-neon.yaml
  webapp/store/content/distros/kubuntu.yaml
  webapp/store/content/distros/manjaro.yaml
  webapp/store/content/distros/mint.yaml
  webapp/store/content/distros/opensuse.yaml
  webapp/store/content/distros/ubuntu.yaml
  webapp/store/snap_details_views.py
Labels: Review: Code needed, Review: Design +1, Review: QA +1

#2029 Updated install instructions
  templates/store/snap-details/_channel_map.html
  templates/store/snap-distro-install.html
Labels: Review: Code +1, Review: QA needed

#2025 Move revisions dropdown from table cell to heading
  static/js/publisher/release/components/releasesTableRow.js
  static/sass/_snapcraft_release.scss
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#2030 FSF - pagination as buttons
  static/js/public/first-snap-flow.js
  templates/first-snap/_install-linux.html
  templates/first-snap/_install-windows.html
  templates/first-snap/_layout_fsf.html
  templates/first-snap/build.html
  templates/first-snap/install-snapcraft.html
  templates/first-snap/package.html
  templates/first-snap/push.html
  templates/first-snap/test.html
  templates/home/_fsf_c.html
  templates/home/_fsf_electron.html
  templates/home/_fsf_go.html
  templates/home/_fsf_java.html
  templates/home/_fsf_moos.html
  templates/home/_fsf_node.html
  templates/home/_fsf_pre-built.html
  templates/home/_fsf_python.html
  templates/home/_fsf_ros.html
  templates/home/_fsf_ros2.html
  templates/home/_fsf_ruby.html
  templates/home/_fsf_rust.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1, Review: UX +1

#2036 Move promote and close channel actions to single menu
  static/js/publisher/release/components/channelMenu.js
  static/js/publisher/release/components/promoteMenu.js
  static/js/publisher/release/components/releasesTableRow.js
  static/sass/_snapcraft_release.scss
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#2043 Disable ```fences``` code blocks in preview
  static/js/publisher/preview.js
Labels: Review: Code +1, Review: QA +1

#2041 Fix Fedora logo on snap details page
  templates/store/snap-details/_distro-instructions-for-snap-support.html
Labels: Review: Code +1, Review: QA +1

#2042 Fix embedded card sizing issue in Safari
  static/js/publisher/publicise.js
Labels: Review: Code +1, Review: QA +1

#2044 Sort & update publicise languages with italian and portuguese additions
  static/images/badges/it/snap-store-black.svg
  static/images/badges/it/snap-store-white.svg
  static/images/badges/pl/snap-store-black.svg
  static/images/badges/pl/snap-store-white.svg
  static/images/badges/pt/snap-store-black.svg
  static/images/badges/pt/snap-store-white.svg
  templates/publisher/publicise/store_buttons.html
  webapp/publisher/snaps/views.py
Labels: Review: Code +1, Review: QA +1
