Repository canonical/snapcraft.io, pull requests merged in 2019-01, with the labels that each got.

#1495 Close unclosed tag on details page
  templates/store/snap-details.html
Labels: Review: Code +1

#1505 Highlight selected revisions in same colour as pending revisions
  static/js/publisher/release/revisionsList.js
  static/sass/_snapcraft_release.scss
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#1507 Improve code styling on descriptions
  webapp/markdown.py
Labels: Review: Code needed, Review: Design needed, Review: QA needed, Review: UX +1

#1503 Improve the layout of videos on snap details pages
  static/js/libs/iframeSize.js
  static/js/public/snap-details/screenshots.js
  static/js/public/snap-details/videos.js
  static/sass/_patterns_carousel.scss
  static/sass/_patterns_code-copyable.scss
  static/sass/_patterns_form-multiselect.scss
  static/sass/_patterns_media-object--snap.scss
  static/sass/_snapcraft_details_heading.scss
  static/sass/_snapcraft_p-notifications.scss
  static/sass/_snapcraft_snap-details.scss
  templates/partials/_snap-details-image-carousel.html
  templates/partials/_snap-details-video-layout.html
  templates/partials/_video.html
  templates/store/snap-details.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#1506 Show bigger promote button
  static/js/publisher/release/components/promoteMenu.js
  static/js/publisher/release/components/releasesTableCell.js
  static/js/publisher/release/releasesTable.js
  static/sass/_snapcraft_release.scss
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#1514 Better messaging for JSON parse errors
  static/js/publisher/release/releasesController.js
Labels: Review: Code +1, Review: QA +1

#1515 Only show revision version selector in available revisions panel
  static/js/publisher/release/revisionsList.js
Labels: Review: Code +1, Review: QA +1

#1517 nps privacy notice, bug fixing
  static/js/public/nps.js
  templates/index.html
Labels: Review: Code +1, Review: QA +1

#1519 Available markdown
  static/js/publisher/market/markdown.js
  static/js/publisher/publisher.js
  templates/publisher/listing.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#1508 Show available stores on snap registration page
  templates/publisher/register-snap.html
  tests/publisher/tests_register_name.py
  webapp/publisher/snaps/logic.py
  webapp/publisher/snaps/views.py
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#1520 Markdown support for snap description
  requirements.txt
  static/js/publisher/market/markdown.js
  static/js/publisher/publisher.js
  templates/publisher/listing.html
  templates/store/snap-details.html
  tests/tests_markdown_parser.py
  webapp/markdown.py
  webapp/store/logic.py
  webapp/store/views.py
Labels: Review: QA needed

#1532 Convert all dates to readable format on backend
  static/js/public/snap-details/channelMap.js
  tests/store/tests_public_logic.py
  webapp/store/logic.py
  webapp/store/views.py
Labels: Review: Code +1, Review: QA +1

#1538 Remove duplicated images uploaded
  tests/publisher/snaps/tests_post_binary_metadata.py
  webapp/publisher/snaps/logic.py
Labels: Review: Code +1, Review: QA +1

#1537 Change root element bkg colour to white
  static/sass/_patterns_sticky_footer.scss
Labels: Review: Code +1, Review: QA +1

#1392 Enable 12m and 24m metrics
  static/js/publisher/metrics/graphs/activeDevices.js
  templates/publisher/metrics.html
  tests/publisher/snaps/tests_get_metrics.py
  webapp/metrics/helper.py
  webapp/publisher/snaps/logic.py
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#1540 Move snap listing edit link to notification
  templates/store/snap-details.html
Labels: Review: Code +1, Review: UX +1

#1539 Make sticky element visually different on edit listing page
  static/js/libs/throttle.js
  static/js/publisher/market/stickyListingBar.js
  static/js/publisher/publisher.js
  static/sass/_snapcraft_market.scss
  templates/publisher/listing.html
Labels: Review: Code +1, Review: QA +1
