Repository canonical/snapcraft.io, pull requests merged in 2019-10, with the labels that each got.

#2282 Bump canonicalwebteam.blog to 4.0.0
  requirements.txt
  webapp/blog/views.py
Labels: Review: Code +1, Review: QA +1

#2294 Blog series in right column
  templates/blog/article.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#2292 Improve order of tags in head
  templates/_layout-brandstore.html
  templates/_layout-embedded.html
  templates/_layout.html
Labels: Performance ⚡️, Review: Code +1, Review: QA +1

#2295 Load categories after page load instead of DOM ready
  templates/store/store.html
Labels: Performance ⚡️, Review: Code +1, Review: QA +1

#2297 Image template
  requirements.txt
  templates/_layout.html
  templates/index.html
  templates/partials/_snap-screenshot.html
  templates/partials/fsf_language.html
  templates/store/_category-partial.html
  templates/store/_generated-featured-snap-partial.html
  templates/store/_media-object-snap-partial.html
  templates/store/snap-distro-install.html
  templates/store/store.html
  webapp/handlers.py
Labels: Performance ⚡️, Review: Code +1, Review: QA +1

#2284 Update the readme, hacking, and brandstores
  BRANDSTORES.md
  HACKING.md
  README.md
Labels: Review: Code +1, Review: Design needed, Review: QA +1

#2300 Make banners live
  templates/store/_category-partial.html
  tests/store/tests_search.py
  webapp/configs/snapcraft.py
  webapp/store/views.py
Labels: Review: Code +1, Review: QA +1

#2277 Refactor releases code into the release redux actions
  static/js/publisher/release/actions/releases.js
  static/js/publisher/release/actions/releases.test.js
  static/js/publisher/release/api/releases.js
  static/js/publisher/release/components/releasesConfirm.js
  static/js/publisher/release/constants.js
  static/js/publisher/release/releasesController.js
Labels: Review: Code +1, Review: QA +1

#2310 compress store badges
  static/images/badges/de/snap-store-black.svg
  static/images/badges/de/snap-store-white.svg
  static/images/badges/en/snap-store-black.svg
  static/images/badges/en/snap-store-white.svg
  static/images/badges/es/snap-store-black.svg
  static/images/badges/es/snap-store-white.svg
  static/images/badges/fr/snap-store-black.svg
  static/images/badges/fr/snap-store-white.svg
  static/images/badges/it/snap-store-black.svg
  static/images/badges/it/snap-store-white.svg
  static/images/badges/jp/snap-store-black.svg
  static/images/badges/jp/snap-store-white.svg
  static/images/badges/pl/snap-store-black.svg
  static/images/badges/pl/snap-store-white.svg
  static/images/badges/pt/snap-store-black.svg
  static/images/badges/pt/snap-store-white.svg
  static/images/badges/ru/snap-store-black.svg
  static/images/badges/ru/snap-store-white.svg
  static/images/badges/tw/snap-store-black.svg
  static/images/badges/tw/snap-store-white.svg
Labels: Performance ⚡️, Review: QA +1

#2313 Update to image-template v1.0.0
  requirements.txt
  templates/_layout.html
  templates/index.html
  templates/partials/_snap-screenshot.html
  templates/store/_generated-featured-snap-partial.html
  templates/store/_media-object-snap-partial.html
  templates/store/snap-details/_snap_heading_data.html
  templates/store/snap-distro-install.html
  templates/store/snap-embedded-card.html
  templates/store/store.html
  webapp/store/logic.py
Labels: Review: Code +1, Review: QA +1

#2317 Remove base64
  static/js/publisher/release/components/availableRevisionsMenu.js
  static/sass/_snapcraft_release.scss
Labels: Review: Code +1, Review: QA +1

#2316 Remove global max-width overrides. Add docs specific override
  static/sass/_snapcraft_custom-typography.scss
  static/sass/_snapcraft_p-docs.scss
  static/sass/styles.scss
Labels: Review: Code +1, Review: Design +1, Review: QA +1, Review: UX +1

#2318 Reduce docker image size
  .dockerignore
  Dockerfile
Labels: Review: Code +1, Review: QA +1

#2305 View progressive releases
  static/js/libs/channels.js
  static/js/publisher/release/components/progressiveBar.js
  static/js/publisher/release/components/releasesTable/cellViews.js
  static/js/publisher/release/components/releasesTable/releaseCell.js
  static/js/publisher/release/components/revisionLabel.js
  static/js/publisher/release/components/revisionsList.js
  static/js/publisher/release/components/revisionsListRow.js
  static/js/publisher/release/helpers.js
  static/js/publisher/release/selectors/index.js
  static/js/publisher/release/selectors/selectors.test.js
  static/sass/_snapcraft_p-progressive-bar.scss
  static/sass/_snapcraft_release.scss
  static/sass/styles.scss
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#2319 Add progressive releases to API calls
  static/js/publisher/release/actions/releases.js
  static/js/publisher/release/actions/releases.test.js
  static/js/publisher/release/api/releases.js
Labels: Review: Code +1

#2325 Fix body in release API call
  static/js/publisher/release/api/releases.js
Labels: Review: Code +1

#2328 Add progressive release feature flag support
  static/js/publisher/release/components/revisionsList.js
  static/js/publisher/release/components/revisionsListRow.js
  static/js/publisher/release/reducers/options.js
  static/js/publisher/release/selectors/index.js
  static/js/publisher/release/selectors/selectors.test.js
  templates/publisher/release-history.html
Labels: Review: Code +1, Review: QA +1

#2327 Progressive release apply
  static/js/publisher/release/actions/pendingReleases.js
  static/js/publisher/release/actions/pendingReleases.test.js
  static/js/publisher/release/components/progressiveConfirm.js
  static/js/publisher/release/components/releasesConfirm.js
  static/js/publisher/release/reducers/pendingReleases.js
  static/js/publisher/release/reducers/pendingReleases.test.js
  static/sass/_snapcraft_release.scss
Labels: Review: Code +1, Review: QA +1
