Repository canonical/snapcraft.io, pull requests merged in 2019-05, with the labels that each got.

#1882 Don't init store-categories on search page
  static/js/public/store-categories.js
  templates/store/search.html
Labels: Review: Code +1, Review: QA +1

#1883 Don't loop videos
  templates/partials/_video.html
Labels: Review: Code needed, Review: QA needed

#1886 More icons for the kde publisher page
  webapp/store/content/publishers/kde.yaml
Labels: Review: Design +1, Review: QA +1

#1881 Force image sizes to prevent load-jumping
  static/sass/_patterns_media-object--snap.scss
Labels: Review: Code +1, Review: QA +1

#1889 Add missing name to MOOS yaml files
  webapp/first_snap/content/moos/build.yaml
  webapp/first_snap/content/moos/test.yaml
Labels: Review: Code +1, Review: QA +1

#1892 Update for KDE publisher page
  webapp/store/content/publishers/kde.yaml
Labels: Review: QA +1

#1890 New category page
  static/js/libs/colours.js
  static/js/public/public.js
  static/js/public/store-categories.js
  static/sass/_patterns_media-object--snap.scss
  static/sass/_snapcraft-p_grid.scss
  static/sass/_snapcraft_p-featured-snap.scss
  templates/store/_generated-featured-snap-partial.html
  templates/store/_media-object-snap-partial.html
  templates/store/search.html
  templates/store/store.html
  tests/store/tests_search.py
  webapp/store/logic.py
  webapp/store/views.py
Labels: Review: Code +1, Review: Design +1, Review: QA +1, Review: UX +1

#1895 Hiri case study
  static/js/public/snap-details/blog-posts.js
  templates/partials/blog-card--minimal.html
  templates/store/snap-details.html
Labels: Review: Code +1, Review: QA +1

#1899 Case study partial. JS fix
  static/js/public/snap-details/blog-posts.js
  templates/partials/_hiri-case-study.html
  templates/store/snap-details.html
Labels: Review: Code +1

#1901 Remove unused content of package step of first snap flow
  webapp/first_snap/content/c/package.yaml
  webapp/first_snap/content/golang/package.yaml
  webapp/first_snap/content/java/package.yaml
  webapp/first_snap/content/moos/package.yaml
  webapp/first_snap/content/node/package.yaml
  webapp/first_snap/content/pre-built/package.yaml
  webapp/first_snap/content/python/package.yaml
  webapp/first_snap/content/ros/package.yaml
  webapp/first_snap/content/ros2/package.yaml
  webapp/first_snap/content/ruby/package.yaml
  webapp/first_snap/content/rust/package.yaml
Labels: Review: Code +1, Review: QA +1

#1902 Defend against unset limit for related blog posts
  static/js/public/snap-details/blog-posts.js
Labels: Review: Code +1

#1904 Update multipass link to new website
  templates/first-snap/_install-macos.html
Labels: Review: Code +1

#1908 Updated IoT page
  webapp/snapcraft/views.py
Labels: Review: Code +1, Review: QA +1

#1909 Update jsdom to remove polyfills from tests
  package.json
  static/js/publisher/form.test.js
  static/js/publisher/form/banner.test.js
  static/js/publisher/market/initBanner.test.js
  static/js/publisher/market/storageCommands.test.js
  static/js/test/setup/polyfill.js
  yarn.lock
Labels: Review: Code +1, Review: QA +1

#1913 Improve speed on blog pages
  tests/blog/tests_index.py
  webapp/api/blog.py
  webapp/blog/views.py
Labels: Review: Code +1, Review: QA +1

#1914 Increase timeout on wordpress API
  webapp/api/blog.py
Labels: Review: Code +1, Review: QA needed

#1916 Open first snap flow language details based on hash in URL
  static/js/public/fsf-language-select.js
Labels: Review: Code +1, Review: QA +1

#1915 Updated title for Domotz
  webapp/snapcraft/views.py
Labels: Review: Code +1, Review: QA +1

#1912 Moved devmode icon to right hand side
  static/js/publisher/release/components/releasesTableCell.js
  static/sass/_snapcraft_release.scss
Labels: Review: Code +1, Review: QA +1

#1920 Semi-automate snapcraft live
  templates/index.html
  templates/partials/livestream-notification.html
  templates/partials/search-bar.html
  webapp/helpers.py
  webapp/snapcraft/content/snapcraft_live.yaml
  webapp/snapcraft/logic.py
  webapp/snapcraft/views.py
  webapp/store/views.py
Labels: Review: Code needed, Review: Design +1, Review: QA +1

#1921 Switch to definition list
  templates/store/snap-details.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1, Review: UX needed

#1927 Reduce number of requests for getSnapCount in fsf
  static/js/public/first-snap-flow.js
Labels: Review: Code +1

#1923 Fix first snap flow macOS test instructions
  webapp/first_snap/content/c/test.yaml
  webapp/first_snap/content/golang/test.yaml
  webapp/first_snap/content/java/test.yaml
  webapp/first_snap/content/moos/test.yaml
  webapp/first_snap/content/node/test.yaml
  webapp/first_snap/content/pre-built/test.yaml
  webapp/first_snap/content/python/test.yaml
  webapp/first_snap/content/ros/test.yaml
  webapp/first_snap/content/ros2/test.yaml
  webapp/first_snap/content/ruby/test.yaml
  webapp/first_snap/content/rust/test.yaml
Labels: Review: Code +1, Review: QA +1

#1926 Skip featured colouring if parent can't be found
  static/js/libs/colours.js
Labels: Review: Code +1, Review: QA +1

#1925 Remove broken verified publisher tooltip from snaps grid
  templates/store/_media-object-snap-partial.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#1929 Make embedded card indexed by search engines as snap details page
  templates/store/snap-embedded-card.html
Labels: Review: Code +1, Review: QA +1

#1939 Update live banner
  webapp/snapcraft/content/snapcraft_live.yaml
Labels: Review: Code +1, Review: QA +1

#1942 Only show pagination if there are search results
  templates/store/search.html
Labels: Review: Code +1, Review: QA +1

#1946 Add details for today's snapcraft live
  webapp/snapcraft/content/snapcraft_live.yaml
Labels: Review: Code +1, Review: QA +1
