Repository canonical/snapcraft.io, pull requests merged in 2019-11, with the labels that each got.

#2321 Show a message if no snaps are returned on store
  templates/store/_category-partial.html
  tests/store/tests_get_store_view.py
  webapp/store/views.py
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#2326 Add is_canonical flag to session
  requirements.txt
  webapp/login/views.py
Labels: Review: Code +1, Review: QA +1

#2335 Improve screenshot sizes on snap details
  static/sass/_patterns_carousel.scss
  templates/partials/_snap-screenshot.html
Labels: Review: Code +1, Review: QA +1

#2337 Fix branch cells widths
  static/sass/_snapcraft_release.scss
Labels: Review: Code +1, Review: QA +1

#2340 Make channel map window width adapt to font size on large screens
  static/sass/_snapcraft_details_heading.scss
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#2344 Update CircleCI and tests
  .circleci/config.yml
  package.json
  run
Labels: Review: Code +1, Review: QA +1

#2329 Update progressive releases
  static/js/publisher/release/actions/pendingReleases.js
  static/js/publisher/release/actions/pendingReleases.test.js
  static/js/publisher/release/actions/releases.js
  static/js/publisher/release/actions/releases.test.js
  static/js/publisher/release/components/progressiveBar.js
  static/js/publisher/release/components/progressiveConfirm.js
  static/js/publisher/release/components/releasesConfirm.js
  static/js/publisher/release/components/releasesTable/cellViews.js
  static/js/publisher/release/components/releasesTable/releaseCell.js
  static/js/publisher/release/components/revisionsList.js
  static/js/publisher/release/components/revisionsListRow.js
  static/js/publisher/release/components/revisionsListRowProgressive.js
  static/js/publisher/release/reducers/history.js
  static/js/publisher/release/reducers/history.test.js
  static/js/publisher/release/reducers/pendingReleases.js
  static/js/publisher/release/reducers/pendingReleases.test.js
  static/js/publisher/release/releasesState.js
  static/js/publisher/release/selectors/index.js
  static/js/publisher/release/selectors/selectors.test.js
  static/sass/_snapcraft_p-progressive-bar.scss
  static/sass/_snapcraft_release.scss
Labels: Review: Code +1, Review: QA +1, Review: UX needed

#2351 Don't show progressive percentage on pending channel close
  static/js/publisher/release/components/releasesTable/releaseCell.js
Labels: Review: Code +1, Review: QA +1

#2357 Change `canBeProgressive` into `previousRevisions`
  static/js/publisher/release/actions/pendingReleases.js
  static/js/publisher/release/reducers/pendingReleases.js
  static/js/publisher/release/reducers/pendingReleases.test.js
Labels: Review: Code +1, Review: QA +1

#2352 Ensure revision can be dragged after progressive release is can…
  static/js/publisher/release/components/revisionsListRowProgressive.js
  static/sass/_snapcraft_release.scss
Labels: Review: Code +1, Review: QA +1

#2354 Fix feed issue with articles without category
  requirements.txt
Labels: Review: QA +1

#2358 Fetch snap builds from launchpad
  requirements.txt
  templates/publisher/_header.html
  templates/publisher/build-list.html
  webapp/api/launchpad.py
  webapp/publisher/snaps/views.py
Labels: Review: Code +1, Review: QA +1

#2353 Update progressiveBar target % when props change
  static/js/publisher/release/actions/releases.js
  static/js/publisher/release/actions/releases.test.js
  static/js/publisher/release/api/releases.js
  static/js/publisher/release/components/progressiveBar.js
  static/js/publisher/release/components/revisionsListRowProgressive.js
  static/js/publisher/release/reducers/pendingReleases.js
  static/js/publisher/release/selectors/index.js
Labels: Review: Code +1, Review: QA +1

#2361 Progressive release cancelation UI
  static/js/publisher/release/actions/pendingReleases.js
  static/js/publisher/release/actions/pendingReleases.test.js
  static/js/publisher/release/components/releasesConfirm.js
  static/js/publisher/release/components/revisionsListRow.js
  static/js/publisher/release/components/revisionsListRowProgressive.js
  static/js/publisher/release/reducers/pendingReleases.js
  static/js/publisher/release/reducers/pendingReleases.test.js
  static/js/publisher/release/selectors/index.js
  static/js/publisher/release/selectors/selectors.test.js
Labels: Review: Code +1, Review: QA +1

#2368 Dedupe non-progressive releases on release
  static/js/publisher/release/actions/releases.js
  static/js/publisher/release/actions/releases.test.js
Labels: Review: Code +1, Review: QA +1

#2364 Combine builds LP status and store upload status into one
  tests/publisher/snaps/test_builds.py
  webapp/publisher/snaps/builds.py
  webapp/publisher/snaps/views.py
Labels: Review: Code +1, Review: QA +1

#2369 Let the release date breath
  static/js/publisher/release/components/revisionsList.js
Labels: Review: Code +1, Review: QA +1

#2367 Show progressive release cancel in history table
  static/js/publisher/release/components/revisionsList.js
  static/js/publisher/release/components/revisionsListRow.js
  static/js/publisher/release/components/revisionsListRowProgressive.js
  static/js/publisher/release/releasesState.js
  static/js/publisher/release/selectors/index.js
  static/js/publisher/release/selectors/selectors.test.js
Labels: Review: Code +1, Review: QA +1

#2375 Add build status colors and build date
  static/js/publisher/builds/index.js
  static/sass/_snapcraft_builds.scss
  static/sass/styles.scss
Labels: Review: Code +1, Review: QA +1

#2370 Show pending progressive updates
  static/js/publisher/release/components/releasesTable/cellViews.js
  static/js/publisher/release/components/releasesTable/releaseCell.js
  static/sass/_snapcraft_release.scss
Labels: Review: Code +1, Review: QA +1

#2376 Automate publisher pages
  tests/store/tests_publisher.py
  webapp/api/store.py
  webapp/store/content/publishers/jetbrains-snaps.yaml
  webapp/store/content/publishers/jetbrains.yaml
  webapp/store/content/publishers/kde-snaps.yaml
  webapp/store/content/publishers/kde.yaml
  webapp/store/snap_details_views.py
  webapp/store/views.py
Labels: Review: Code +1, Review: QA +1

#2383 Add `snap_builds_enabled` key to context
  webapp/publisher/snaps/views.py
Labels: Review: Code +1, Review: QA +1
