Repository canonical/snapcraft.io, pull requests merged in 2020-07, with the labels that each got.

#2924 Fix bug with banner removal when trying to replace it first with and invalid image
  static/js/publisher/form/banner.js
  static/js/publisher/form/fileInput.js
Labels: Review: Code +1, Review: QA +1

#2926 Add Optimize anti-flicker snippet
  templates/_layout.html
Labels: Review: Code +1

#2932 Flutter
  templates/home/_fsf_flutter.html
  templates/partials/fsf_language.html
  webapp/first_snap/content/flutter/build.yaml
  webapp/first_snap/content/flutter/package.yaml
  webapp/first_snap/content/flutter/snapcraft.yaml
  webapp/first_snap/content/flutter/test.yaml
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#2936 Update Python dependencies
  requirements.txt
  webapp/docs/views.py
  webapp/tutorials/views.py
Labels: Review: Code +1, Review: QA +1

#2929 Check for updates to GitHub Actions every weekday
  .github/dependabot.yml
Labels: Review: Code +1

#2938 Mirror flutter logo
  templates/partials/fsf_language.html
Labels: Review: QA +1

#2939 Fix tutorial styling
  package.json
  static/sass/_snapcraft_p-tutorials.scss
  templates/tutorials/tutorial.html
  yarn.lock
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#2941 Update docs search navigation
  static/sass/_patterns_pagination.scss
  templates/docs/search.html
Labels: Review: Code needed, Review: QA needed, Review: UX +1

#2942 Updated flutter first-snap example to a simplier app that already has a linux target
  templates/home/_fsf_flutter.html
  webapp/first_snap/content/flutter/build.yaml
  webapp/first_snap/content/flutter/package.yaml
  webapp/first_snap/content/flutter/snapcraft.yaml
  webapp/first_snap/content/flutter/test.yaml
Labels: Review: Code +1, Review: QA +1

#2947 Catch the no tag found error
  webapp/blog/views.py
Labels: Review: Code +1, Review: QA +1

#2950 Make snap name max 40 characters
  templates/publisher/register-snap.html
Labels: Review: Code +1, Review: QA +1

#2956 Remove intercom js snippet
  templates/first-snap/_layout_fsf.html
Labels: Review: Code +1, Review: QA +1

#2958 ros1 fsf: properly test the snap
  webapp/first_snap/content/ros/build.yaml
  webapp/first_snap/content/ros/snapcraft.yaml
  webapp/first_snap/content/ros/test.yaml
Labels: Review: Code +1, Review: QA +1

#2959 Add message if linked repo does not exists
  templates/publisher/builds.html
  webapp/api/github.py
  webapp/publisher/snaps/build_views.py
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#2953 Remove hardcode of default track for node
  tests/tests_templates_utils.py
  webapp/helpers.py
  webapp/publisher/snaps/metrics_views.py
  webapp/store/snap_details_views.py
Labels: Review: Code +1, Review: QA +1

#2962 Update some dependencies
  package.json
  webpack.config.rules.js
  yarn.lock
Labels: Review: Code +1, Review: QA +1

#2967 Replace .is--disabled with .is-disabled
  static/js/publisher/form.js
  static/js/publisher/form.test.js
  static/js/publisher/release/components/contextualMenu.js
  static/js/publisher/submitEnabler.js
  templates/first-snap/install-snapcraft.html
  yarn.lock
Labels: Review: Code +1, Review: QA +1

#2964 Rename deploy to konf
  konf/limenet.snapcraft.io.yaml
  konf/sdrsatcom.snapcraft.io.yaml
  konf/site.yaml
  konf/staging-api.snapcraft.io.yaml
Labels: Review: QA +1

#2969 Bug fixes on builds
  templates/publisher/builds.html
  webapp/publisher/snaps/build_views.py
Labels: Review: Code +1, Review: QA +1

#2963 Fix issue with BSI webhooks
  webapp/api/github.py
  webapp/publisher/snaps/build_views.py
Labels: Review: Code +1, Review: QA +1

#2972 Missing yarn.lock in Docker
  Dockerfile
Labels: Review: Code +1, Review: QA +1

#2973 Upgrade to babel 7
  .babelrc
  package.json
  static/js/public/first-snap-flow.test.js
  static/js/publisher/market/storageCommands.test.js
  yarn.lock
Labels: Review: Code +1, Review: QA +1

#2977 Fix multiselect always highlighted first option
  static/js/publisher/form/multiselect.js
Labels: Review: Code +1, Review: QA +1

#2979 Update store-api module
  requirements.txt
  tests/publisher/snaps/tests_listing.py
  tests/publisher/snaps/tests_post_listing.py
  tests/store/tests_get_store_view.py
  tests/store/tests_public_logic.py
  tests/store/tests_search.py
  webapp/store/logic.py
Labels: Review: Code +1, Review: QA +1
