Repository canonical/snapcraft.io, pull requests merged in 2020-04, with the labels that each got.

#2636 3rd party blog posts
  static/js/public/snap-details/blog-posts.js
  static/sass/_patterns_blog-post.scss
  templates/partials/blog-card--minimal.html
  templates/store/snap-details.html
  templates/store/snap-details/_templates.html
  webapp/blog/content/blog-posts.yaml
  webapp/blog/views.py
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#2645 Add instructions for newer versions of Debian.
  webapp/store/content/distros/debian.yaml
Labels: Review: Code +1, Review: QA +1

#2644 Fsf improvements
  static/js/public/accordion.js
  static/sass/_patterns_annotated_code.scss
  static/sass/_patterns_first-snap-flow.scss
  templates/first-snap/_breadcrumb.html
  templates/first-snap/build-and-test.html
  templates/first-snap/build.html
  templates/first-snap/install-snapcraft.html
  templates/first-snap/package.html
  templates/first-snap/push.html
  templates/home/_fsf_go.html
  templates/home/_fsf_java.html
  templates/home/_fsf_node.html
  templates/home/_fsf_python.html
  templates/home/_fsf_ruby.html
  templates/home/_fsf_rust.html
  tests/first_snap/tests_views.py
  webapp/first_snap/content/c/build.yaml
  webapp/first_snap/content/c/test.yaml
  webapp/first_snap/content/golang/build.yaml
  webapp/first_snap/content/golang/snapcraft.yaml
  webapp/first_snap/content/golang/test.yaml
  webapp/first_snap/content/java/build.yaml
  webapp/first_snap/content/java/snapcraft.yaml
  webapp/first_snap/content/java/test.yaml
  webapp/first_snap/content/moos/build.yaml
  webapp/first_snap/content/moos/test.yaml
  webapp/first_snap/content/node/build.yaml
  webapp/first_snap/content/node/snapcraft.yaml
  webapp/first_snap/content/node/test.yaml
  webapp/first_snap/content/pre-built/build.yaml
  webapp/first_snap/content/pre-built/test.yaml
  webapp/first_snap/content/python/build.yaml
  webapp/first_snap/content/python/snapcraft.yaml
  webapp/first_snap/content/python/test.yaml
  webapp/first_snap/content/ros/build.yaml
  webapp/first_snap/content/ros/test.yaml
  webapp/first_snap/content/ros2/build.yaml
  webapp/first_snap/content/ros2/test.yaml
  webapp/first_snap/content/ruby/build.yaml
  webapp/first_snap/content/ruby/snapcraft.yaml
  webapp/first_snap/content/ruby/test.yaml
  webapp/first_snap/content/rust/build.yaml
  webapp/first_snap/content/rust/snapcraft.yaml
  webapp/first_snap/content/rust/test.yaml
  webapp/first_snap/views.py
Labels: Review: Code +1, Review: QA +1

#2648 If snap is in launchpad show webhook url on settings page
  templates/publisher/settings.html
  tests/publisher/snaps/tests_post_settings.py
  tests/publisher/snaps/tests_settings.py
  webapp/publisher/snaps/settings_views.py
Labels: Review: Code +1, Review: QA +1

#2649 remove extra slash in blog url
  webapp/blog/content/blog-posts.yaml
Labels: Review: Code +1

#2652 Backend changes to disconnect a repo
  requirements.txt
  templates/publisher/disconnect-repo.html
  webapp/publisher/snaps/build_views.py
  webapp/publisher/snaps/views.py
Labels: Review: Code needed

#2655 Remove GitHub webhook when disconnecting a repo
  webapp/api/github.py
  webapp/publisher/snaps/build_views.py
Labels: Review: Code +1, Review: QA +1

#2656 webook -> webhook
  templates/publisher/settings.html
Labels: Review: Code +1

#2651 5 year metrics
  templates/publisher/metrics.html
Labels: Review: Code +1, Review: QA +1

#2658 Fix empty store_name issue
  requirements.txt
  webapp/publisher/snaps/build_views.py
Labels: Review: Code +1, Review: QA +1

#2654 Add remove repo
  static/js/publisher/builds/repoDisconnect.js
  static/js/publisher/publisher.js
  static/sass/_patterns_modal.scss
  templates/publisher/_repo-disconnect-modal.html
  templates/publisher/builds.html
  templates/publisher/disconnect-repo.html
  webapp/publisher/snaps/build_views.py
  webapp/publisher/snaps/views.py
Labels: Review: Code +1, Review: Design +1, Review: QA +1, Review: UX +1

#2660 Link repo only for Snap collaborators
  webapp/api/dashboard.py
  webapp/publisher/snaps/build_views.py
Labels: Review: Code +1, Review: QA +1

#2662 Update Store module to 2.0.1
  requirements.txt
Labels: Review: Code +1, Review: QA +1

#2663 Disconnect snap
  requirements.txt
  static/js/publisher/builds/repoDisconnect.js
  static/js/publisher/publisher.js
  static/sass/_patterns_modal.scss
  templates/publisher/_repo-disconnect-modal.html
  templates/publisher/builds.html
  webapp/api/github.py
  webapp/publisher/snaps/build_views.py
  webapp/publisher/snaps/views.py
Labels: Review: QA +1

#2666 GitHub Docker use .env
  .dockerignore
  .github/workflows/main.yml
Labels: Review: Code +1

#2665 Update flask-base to 0.5.1
  .circleci/config.yml
  requirements.txt
Labels: Review: Code +1, Review: QA +1

#2668 Enable default track selection
  static/js/publisher/release/components/defaultTrackModifier.js
  static/js/publisher/release/components/releasesHeading.js
Labels: Review: QA +1

#2672 Simplify get_builds method
  webapp/publisher/snaps/build_views.py
Labels: Review: Code +1, Review: QA +1

#2673 Ensure copy-to-clipboard works for FSF steps
  templates/first-snap/build-and-test.html
Labels: Review: Code +1, Review: QA +1

#2674 Pi distro page
  static/js/public/expandable-area.js
  static/sass/_snapcraft_show-more.scss
  templates/store/snap-details/_distro-instructions-for-snap-support.html
  templates/store/snap-distro-install.html
  webapp/store/content/distros/raspbian.yaml
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#2676 Added error for invalid yaml file
  webapp/api/github.py
  webapp/publisher/snaps/build_views.py
Labels: Review: Code +1

#2675 New build page
  templates/snapcraft/build.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#2677 Invalid snapcraft yaml
  static/js/publisher/builds/components/repoConnect.js
  webapp/publisher/snaps/build_views.py
Labels: Review: Code +1, Review: QA +1

#2671 Update RHEL distro specific install page
  webapp/store/content/distros/rhel.yaml
Labels: Review: Code +1, Review: QA +1

#2681 Update to focal
  .circleci/config.yml
  Dockerfile
  requirements.txt
Labels: Review: Code +1, Review: QA +1

#2683 Don't try and remove an element that doesn't exist
  static/js/public/expandable-area.js
Labels: Review: Code +1, Review: QA +1

#2686 Show a better error if launchpad return a timeout
  webapp/publisher/snaps/build_views.py
Labels: Review: Code +1, Review: QA +1

#2687 Fix brandstore nav
  templates/_header-brandstore.html
Labels: Review: Code needed, Review: QA needed

#2688 hide show-more with CSS
  static/js/public/expandable-area.js
  static/sass/_snapcraft_show-more.scss
Labels: Review: Code needed

#2685 Fix spinner to show in FF
  static/js/publisher/builds/repoDisconnect.js
Labels: Review: Code +1, Review: QA +1

#2695 Disable categories dropdown when API call fail
  templates/publisher/listing.html
Labels: Review: Code +1, Review: QA +1

#2697 Update to vanilla 2.10
  package.json
  static/sass/_snapcraft_metrics.scss
  static/sass/_snapcraft_p-featured-snap.scss
  templates/blog/article.html
  templates/docs/search.html
  templates/first-snap/_breadcrumb.html
  templates/index.html
  templates/partials/_hiri-case-study.html
  templates/partials/blog-card--minimal.html
  templates/partials/blog-card.html
  templates/partials/search-bar.html
  templates/publisher/_header.html
  templates/publisher/account-snaps.html
  templates/publisher/build.html
  templates/publisher/developer_programme_agreement.html
  templates/publisher/listing.html
  templates/publisher/metrics.html
  templates/publisher/publicise/_publisher_publicise_layout.html
  templates/publisher/register-name-dispute-success.html
  templates/publisher/register-name-dispute.html
  templates/publisher/register-snap.html
  templates/publisher/request-reserved-name.html
  templates/publisher/username.html
  templates/snapcraft/build.html
  templates/store/_empty-category-partial.html
  templates/store/_generated-featured-snap-partial.html
  templates/store/_media-object-snap-partial.html
  templates/store/categories/iot.html
  templates/store/publisher-details.html
  templates/store/snap-details.html
  templates/store/snap-details/_channel_map.html
  templates/store/snap-details/_snap_heading_data.html
  templates/store/snap-embedded-card.html
  templates/store/store.html
  templates/tutorials/index.html
  templates/tutorials/tutorial.html
  yarn.lock
Labels: Review: Code +1, Review: QA +1

#2694 Feature/build messaging
  templates/publisher/account-snaps.html
  templates/snapcraft/build.html
Labels: Review: QA +1

#2701 Fix GitHub rate limit issue
  webapp/publisher/snaps/build_views.py
Labels: Review: Code +1, Review: QA +1

#2696 Add icon restriction info
  static/js/publisher/form/icon.js
  static/js/publisher/market/restrictions.js
  static/sass/_snapcraft_market.scss
Labels: Review: Code +1, Review: QA +1

#2702 Fix button spacing on mobile
  static/sass/_snapcraft_market.scss
  templates/publisher/listing.html
  templates/publisher/settings.html
  templates/store/snap-details.html
Labels: Review: Code +1, Review: QA +1

#2704 Fix blog links
  webapp/blog/views.py
Labels: Review: Code +1, Review: QA +1

#2705 Show the developer for Canonical and Snapcrafters snapped snaps
  templates/store/_snap-header-developer-information.html
  templates/store/_snap-header-information.html
  templates/store/snap-details/_snap_heading_data.html
  webapp/blog/views.py
  webapp/store/content/developers/snaps.yaml
  webapp/store/logic.py
  webapp/store/snap_details_views.py
Labels: Review: Code +1, Review: QA +1

#2707 Fix formatting of snap details blog post images
  requirements.txt
  static/sass/_patterns_blog-post.scss
  webapp/blog/views.py
Labels: Review: Code +1, Review: QA +1

#2706 Update to use multistage
  .dockerignore
  Dockerfile
Labels: Review: Code +1, Review: QA +1

#2711 Allow users without organizations to build snaps
  templates/publisher/builds.html
Labels: Review: Code +1, Review: QA +1

#2716 Allow builds from collaborators
  static/js/publisher/builds/components/repoConnect.js
  static/js/publisher/builds/index.js
  templates/publisher/builds.html
  webapp/api/github.py
  webapp/publisher/snaps/build_views.py
Labels: Review: Code +1, Review: QA +1

#2709 Move to different GTM code
  templates/_layout-brandstore.html
  templates/_layout.html
Labels: Review: Code +1
