Repository canonical/snapcraft.io, pull requests merged in 2020-01, with the labels that each got.

#2415 Update node-sass to 4.13.0
  package.json
  webapp/authentication.py
  yarn.lock
Labels: Review: Code +1, Review: QA +1

#2412 Add extra null check when getting src
  static/js/public/snap-details/videos.js
Labels: Review: Code +1

#2416 Add latest Linux Mint versions (Tina and Tricia) to mint.yaml
  webapp/store/content/distros/mint.yaml
Labels: Review: Code +1, Review: QA +1

#2417 Update run script to use latest docker image
  run
Labels: Review: Code +1, Review: QA +1

#2410 Add spam validation for blog whitepapers
  static/js/public/formValidation.js
  static/js/public/public.js
  templates/blog/article.html
Labels: Review: Code +1, Review: QA +1

#2425 Enable register snap name button initially
  static/js/public/first-snap-flow.js
  templates/first-snap/push.html
Labels: Review: Code +1, Review: QA +1

#2428 Add noindex to unlisted snaps pages
  requirements.txt
  templates/_layout-brandstore.html
  templates/store/snap-details.html
  tests/store/tests_details.py
  tests/store/tests_distro_page.py
  tests/store/tests_embedded_card.py
  tests/store/tests_github_badge.py
  webapp/store/snap_details_views.py
Labels: Review: Code +1, Review: QA +1

#2432 Fix markdown issue with URLs
  webapp/markdown.py
Labels: Review: Code +1, Review: QA +1

#2434 Add 3rd party store links
  templates/store/snap-details.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#2433 Improved ProgressiveBar in chrome
  static/js/publisher/release/components/progressiveBar.js
  static/js/publisher/release/components/revisionsListRow.js
Labels: Review: Code +1, Review: QA +1

#2439 Title case categories
  webapp/store/logic.py
Labels: Review: Code +1, Review: QA +1

#2438 Simplify getprogressivestate
  static/js/publisher/release/components/releasesTable/releaseCell.js
  static/js/publisher/release/components/revisionsListRow.js
  static/js/publisher/release/components/revisionsListRowProgressive.js
  static/js/publisher/release/selectors/index.js
  static/js/publisher/release/selectors/selectors.test.js
Labels: Review: Code +1, Review: QA +1

#2441 Make snap title wrap
  static/sass/_snapcraft_details_heading.scss
  static/sass/_utilities_text-wrap.scss
  static/sass/styles.scss
  templates/store/snap-details.html
Labels: Review: Code +1, Review: QA +1

#2445 Ensure global errors are visible on form submission
  static/js/publisher/form.js
Labels: Review: Code +1, Review: QA +1

#2440 Make distro list expandable on snap details page
  static/js/public/public.js
  static/js/public/snap-details/exapandable-distr-chart.js
  static/sass/_snapcraft_distro-chart.scss
  templates/store/snap-details.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1, Review: UX +1

#2446 Display publisher name on /store page
  templates/store/_media-object-snap-partial.html
  webapp/snapcraft/views.py
Labels: Review: Code +1, Review: QA +1

#2452 Upgrade to vanilla 2.5.0
  package.json
  static/sass/_patterns_media-object--snap.scss
  static/sass/_snapcraft-publisher.scss
  static/sass/_snapcraft_details_heading.scss
  static/sass/_snapcraft_p-docs.scss
  static/sass/_snapcraft_p-navigation.scss
  static/sass/_snapcraft_tour.scss
  static/sass/styles.scss
  templates/_header.html
  yarn.lock
Labels: Review: Code +1, Review: QA +1

#2459 Make the table on /snaps mobile friendly
  static/sass/_snapcraft_p-table-mobile-card.scss
  static/sass/styles.scss
  templates/publisher/account-snaps.html
Labels: Review: Code +1, Review: QA +1

#2456 Move confirm buttons to own component
  static/js/publisher/release/components/releasesConfirm.js
  static/js/publisher/release/components/releasesConfirmActions.js
Labels: Review: Code +1, Review: QA +1

#2455 Use the correct last page link
  tests/store/tests_search.py
  webapp/store/views.py
Labels: Review: Code +1, Review: QA +1

#2462 Clone helper
  static/js/publisher/release/helpers.js
  static/js/publisher/release/helpers.test.js
  static/js/publisher/release/reducers/pendingReleases.js
  static/js/publisher/release/selectors/index.js
Labels: Review: Code +1, Review: QA +1

#2461 Progressive bar styling - rounded at 100% and greyscale when disabled
  static/js/publisher/release/components/progressiveBar.js
  static/sass/_snapcraft_p-progressive-bar.scss
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#2471 Replace _handle_errors function
  webapp/publisher/snaps/views.py
  webapp/publisher/views.py
  webapp/store/views.py
Labels: Review: Code +1

#2475 Make year in the footer dynamic
  templates/_footer.html
  webapp/handlers.py
Labels: Review: Code +1, Review: QA +1

#2468 Move the release details below the button row
  static/js/publisher/release/components/releasesConfirm.js
  static/sass/_snapcraft_release.scss
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#2469 Move progressiveRow to class. Throttle onChange handler
  static/js/publisher/release/components/progressiveBar.js
  static/js/publisher/release/components/releasesConfirmDetails/progressiveRow.js
Labels: Review: Code +1, Review: QA +1

#2481 Add more vertical spacing for companion apps section
  static/sass/styles.scss
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#2478 Ensure progressive releases are hidden when flag is disabled
  static/js/publisher/release/components/releasesConfirmDetails/index.js
  static/js/publisher/release/components/releasesConfirmDetails/releaseRow.js
  templates/publisher/release-history.html
  webapp/handlers.py
Labels: Review: Code +1, Review: QA +1

#2470 Add GA event tracking to release-ui
  static/js/base/ga.js
  static/js/publisher/release/actions/gaEventTracking.js
  static/js/publisher/release/actions/gaEventTracking.test.js
  static/js/publisher/release/actions/history.js
  static/js/publisher/release/actions/history.test.js
  static/js/publisher/release/actions/pendingReleases.js
  static/js/publisher/release/actions/pendingReleases.test.js
  static/js/publisher/release/components/channelMenu.js
  static/js/publisher/release/components/releasesConfirm.js
  static/js/publisher/release/components/releasesTable/channelHeading.js
  static/js/publisher/release/components/releasesTable/droppableRow.js
  static/sass/_snapcraft-publisher.scss
  static/sass/_snapcraft_p-docs.scss
Labels: Review: Code +1, Review: QA +1

#2482 Ensure progressive values align
  static/js/publisher/release/actions/pendingReleases.js
Labels: Review: Code +1, Review: QA +1

#2489 remove legacy banner whitelisting
  static/js/publisher/market/restrictions.js
Labels: Review: Code +1, Review: QA +1
