Repository canonical/snapcraft.io, pull requests merged in 2020-02, with the labels that each got.

#2490 Display truncated fsf yaml files
  .gitignore
  static/js/public/fsf-expandable-yaml-details.js
  static/js/public/fsf-language-select.js
  static/js/public/public.js
  static/sass/_snapcraft_show-more.scss
  static/sass/styles.scss
  templates/first-snap/language.html
  templates/home/_fsf_c.html
  templates/home/_fsf_electron.html
  templates/home/_fsf_go.html
  templates/home/_fsf_java.html
  templates/home/_fsf_moos.html
  templates/home/_fsf_node.html
  templates/home/_fsf_pre-built.html
  templates/home/_fsf_python.html
  templates/home/_fsf_ros.html
  templates/home/_fsf_ros2.html
  templates/home/_fsf_ruby.html
  templates/home/_fsf_rust.html
  templates/home/_fsf_yaml_show_more.html
  templates/index.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#2493 2483 build unauthorised page with build info
  static/sass/_snapcraft_p-build.scss
  templates/publisher/builds.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#2479 Check if snapcraft.yaml is present
  requirements.txt
  tests/api/cassettes/GitHubAPITest.test_get_user_repositories.yaml
  tests/api/cassettes/GitHubAPITest.test_get_username.yaml
  tests/api/cassettes/GitHubAPITest.test_is_snapcraft_yaml_present.yaml
  tests/api/test_github.py
  webapp/api/github.py
  webapp/authentication.py
  webapp/login/views.py
  webapp/publisher/github/views.py
  webapp/publisher/snaps/views.py
Labels: Review: Code +1, Review: QA +1

#2499 Launchpad API Call to launch a build
  templates/publisher/builds.html
  tests/api/cassettes/LaunchapdAPITest.test_get_snap_by_store_name.yaml
  tests/api/cassettes/LaunchapdAPITest.test_new_snap.yaml
  tests/api/cassettes/LaunchapdAPITest.test_trigger_build.yaml
  tests/api/test_launchpad.py
  webapp/api/launchpad.py
  webapp/publisher/snaps/views.py
Labels: Review: Code +1, Review: QA +1

#2500 Build list
  static/js/publisher/builds/index.js
  static/sass/_snapcraft_builds.scss
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#2505 Replace forEach with regular for loops for showMore elements
  static/js/public/fsf-expandable-yaml-details.js
  static/js/public/fsf-language-select.js
Labels: Review: Code +1, Review: QA +1

#2501 Get GitHub repos filtered by org
  templates/publisher/builds.html
  tests/api/cassettes/GitHubAPITest.test_get_org_repositories.yaml
  tests/api/cassettes/GitHubAPITest.test_get_orgs.yaml
  tests/api/cassettes/GitHubAPITest.test_get_user.yaml
  tests/api/cassettes/GitHubAPITest.test_get_user_repositories.yaml
  tests/api/cassettes/GitHubAPITest.test_is_snapcraft_yaml_present.yaml
  tests/api/test_github.py
  webapp/api/github.py
  webapp/app.py
  webapp/login/oauth_views.py
  webapp/publisher/github/views.py
  webapp/publisher/snaps/views.py
Labels: Review: Code +1, Review: QA +1

#2508 Upgrade to latest version of discourse docs
  requirements.txt
  webapp/docs/views.py
Labels: Review: Code +1, Review: QA +1

#2507 Update Show more buttons with the new pattern
  static/js/public/expandable-area.js
  static/js/public/expandable-details.js
  static/js/public/fsf-language-select.js
  static/js/public/public.js
  static/js/public/snap-details/exapandable-distr-chart.js
  static/sass/_patterns_distro_banner.scss
  static/sass/_snapcraft_distro-chart.scss
  static/sass/_snapcraft_show-more.scss
  templates/first-snap/language.html
  templates/index.html
  templates/store/snap-details.html
  templates/store/snap-distro-install.html
Labels: Review: Code +1, Review: QA +1

#2509 Tutorials
  static/sass/_snapcraft_p-tutorials.scss
  static/sass/styles.scss
  templates/_header.html
  templates/tutorials/index.html
  templates/tutorials/tutorial.html
  webapp/app.py
  webapp/tutorials/__init__.py
  webapp/tutorials/views.py
Labels: Review: Code +1, Review: QA +1

#2510 Increase tour background transparency
  static/sass/_snapcraft_tour.scss
Labels: Review: Code +1, Review: QA +1

#2502 Dynamic build list
  static/js/publisher/builds/helpers.js
  static/js/publisher/builds/index.js
  templates/publisher/builds.html
  webapp/api/launchpad.py
  webapp/publisher/snaps/views.py
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#2518 Validate individual GitHub repos
  tests/api/cassettes/GitHubAPITest.test_get_snapcraft_yaml_location.yaml
  tests/api/test_github.py
  webapp/api/github.py
  webapp/publisher/snaps/build_views.py
  webapp/publisher/snaps/views.py
Labels: Review: Code +1, Review: QA +1

#2520 Fix AttributeError in doc pages
  requirements.txt
Labels: Review: Code +1, Review: QA +1

#2527 GitHub checks when saving a repo
  tests/api/cassettes/GitHubAPITest.test_check_permissions_over_repo.yaml
  tests/api/test_github.py
  webapp/api/github.py
  webapp/publisher/snaps/views.py
Labels: Review: Code +1, Review: QA +1

#2532 Refactor code
  tests/api/cassettes/GitHubAPITest.test_get_org_repositories.yaml
  tests/api/cassettes/GitHubAPITest.test_get_snapcraft_yaml_name.yaml
  tests/api/cassettes/GitHubAPITest.test_get_user_repositories.yaml
  tests/api/test_github.py
  webapp/api/github.py
  webapp/publisher/snaps/build_views.py
  webapp/publisher/snaps/views.py
Labels: Review: Code +1, Review: QA +1

#2529 Make sure to test for bool
  static/js/publisher/tour.js
Labels: Review: Code +1, Review: QA +1

#2531 Progressive releases to master
  static/js/base/ga.js
  static/js/libs/channels.js
  static/js/publisher/release/actions/gaEventTracking.js
  static/js/publisher/release/actions/gaEventTracking.test.js
  static/js/publisher/release/actions/history.js
  static/js/publisher/release/actions/history.test.js
  static/js/publisher/release/actions/pendingReleases.js
  static/js/publisher/release/actions/pendingReleases.test.js
  static/js/publisher/release/actions/releases.js
  static/js/publisher/release/actions/releases.test.js
  static/js/publisher/release/api/releases.js
  static/js/publisher/release/components/channelMenu.js
  static/js/publisher/release/components/progressiveBar.js
  static/js/publisher/release/components/progressiveConfirm.js
  static/js/publisher/release/components/releasesConfirm.js
  static/js/publisher/release/components/releasesConfirmActions.js
  static/js/publisher/release/components/releasesConfirmDetails/cancelProgressiveRow.js
  static/js/publisher/release/components/releasesConfirmDetails/closeChannelsRow.js
  static/js/publisher/release/components/releasesConfirmDetails/globalRow.js
  static/js/publisher/release/components/releasesConfirmDetails/index.js
  static/js/publisher/release/components/releasesConfirmDetails/progressiveRow.js
  static/js/publisher/release/components/releasesConfirmDetails/progressiveRowGroup.js
  static/js/publisher/release/components/releasesConfirmDetails/releaseRow.js
  static/js/publisher/release/components/releasesConfirmDetails/types.js
  static/js/publisher/release/components/releasesTable/cellViews.js
  static/js/publisher/release/components/releasesTable/channelHeading.js
  static/js/publisher/release/components/releasesTable/droppableRow.js
  static/js/publisher/release/components/releasesTable/releaseCell.js
  static/js/publisher/release/components/revisionLabel.js
  static/js/publisher/release/components/revisionsList.js
  static/js/publisher/release/components/revisionsListRow.js
  static/js/publisher/release/components/revisionsListRowProgressive.js
  static/js/publisher/release/constants.js
  static/js/publisher/release/helpers.js
  static/js/publisher/release/helpers.test.js
  static/js/publisher/release/reducers/history.js
  static/js/publisher/release/reducers/history.test.js
  static/js/publisher/release/reducers/options.js
  static/js/publisher/release/reducers/pendingReleases.js
  static/js/publisher/release/reducers/pendingReleases.test.js
  static/js/publisher/release/releasesController.js
  static/js/publisher/release/releasesState.js
  static/js/publisher/release/selectors/index.js
  static/js/publisher/release/selectors/selectors.test.js
  static/sass/_snapcraft_p-progressive-bar.scss
  static/sass/_snapcraft_p-release-details-row.scss
  static/sass/_snapcraft_release.scss
  static/sass/styles.scss
  templates/publisher/release-history.html
  webapp/handlers.py
Labels: Review: QA +1

#2537 Include yaml file name in fsf
  static/sass/_patterns_annotated_code.scss
  templates/first-snap/package.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#2539 Consistent publisher headers.
  templates/publisher/_header.html
  tests/publisher/snaps/tests_get_metrics.py
  tests/publisher/snaps/tests_post_settings.py
  tests/publisher/snaps/tests_publicise.py
  tests/publisher/snaps/tests_publicise_badges.py
  tests/publisher/snaps/tests_publicise_cards.py
  tests/publisher/snaps/tests_revision.py
  tests/publisher/snaps/tests_settings.py
  webapp/publisher/snaps/views.py
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#2540 Always get total active devices from most recent 24 hours
  tests/publisher/snaps/tests_get_metrics.py
  webapp/publisher/snaps/views.py
Labels: Review: Code +1, Review: QA +1

#2541 Fix styling of release change row
  static/js/publisher/release/releasesController.js
Labels: Review: Code +1, Review: QA +1

#2528 FSF expand next accordion when clicking register snap name
  static/js/public/first-snap-flow.js
  templates/first-snap/push.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#2534 Add GitHub Webhook endpoint
  webapp/api/github.py
  webapp/api/launchpad.py
  webapp/publisher/snaps/build_views.py
  webapp/publisher/snaps/views.py
Labels: Review: Code +1, Review: QA +1

#2551 Use flask-base
  requirements.txt
  tests/first_snap/tests_views.py
  webapp/app.py
  webapp/handlers.py
Labels: Review: Code +1, Review: QA +1

#2560 Drops redundant placeholder from search field
  templates/partials/search-bar.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#2562 Revert "Use flask-base"
  requirements.txt
  tests/first_snap/tests_views.py
  webapp/app.py
  webapp/handlers.py
Labels: Review: Code +1

#2504 Connect to repo
  static/js/publisher/builds/components/datalistSelect.js
  static/js/publisher/builds/components/repoConnect.js
  static/js/publisher/builds/components/select.js
  static/js/publisher/publisher.js
  static/sass/_snapcraft_p-build.scss
  templates/publisher/builds.html
  webapp/publisher/snaps/build_views.py
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#2555 Switch over to using canonicalwebteam.launchpad
  requirements.txt
  tests/api/cassettes/LaunchapdAPITest.test_get_snap_by_store_name.yaml
  tests/api/cassettes/LaunchapdAPITest.test_new_snap.yaml
  tests/api/cassettes/LaunchapdAPITest.test_trigger_build.yaml
  tests/api/test_launchpad.py
  webapp/api/launchpad.py
  webapp/publisher/snaps/build_views.py
  webapp/publisher/snaps/views.py
Labels: Review: Code needed, Review: QA needed

#2548 Create GitHub Webhook for users
  templates/publisher/builds.html
  webapp/api/github.py
  webapp/publisher/snaps/build_views.py
  webapp/publisher/snaps/views.py
Labels: Review: Code +1, Review: QA +1

#2564 Remove "Go to listing" button
  static/js/public/first-snap-flow.js
  templates/first-snap/push.html
  templates/publisher/_header.html
  templates/publisher/account-snaps.html
  templates/publisher/listing.html
  tests/publisher/snaps/tests_listing.py
  webapp/publisher/snaps/views.py
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#2567 Rename API classes
  requirements.txt
  tests/api/cassettes/GitHubTest.test_check_permissions_over_repo.yaml
  tests/api/cassettes/GitHubTest.test_get_org_repositories.yaml
  tests/api/cassettes/GitHubTest.test_get_orgs.yaml
  tests/api/cassettes/GitHubTest.test_get_snapcraft_yaml_location.yaml
  tests/api/cassettes/GitHubTest.test_get_snapcraft_yaml_name.yaml
  tests/api/cassettes/GitHubTest.test_get_user.yaml
  tests/api/cassettes/GitHubTest.test_get_user_repositories.yaml
  tests/api/test_github.py
  tests/api/test_marketo_api.py
  webapp/api/github.py
  webapp/api/marketo.py
  webapp/publisher/github/views.py
  webapp/publisher/snaps/build_views.py
  webapp/publisher/snaps/views.py
  webapp/publisher/views.py
  webapp/store/views.py
Labels: Review: Code +1, Review: QA +1

#2566 Fix marketo response index error
  webapp/api/marketo.py
  webapp/publisher/views.py
Labels: Review: Code +1, Review: QA +1

#2542 FSF - Remove clone step
  static/sass/_patterns_annotated_code.scss
  templates/first-snap/build.html
  templates/first-snap/install-snapcraft.html
  templates/first-snap/package.html
  templates/first-snap/push.html
  webapp/first_snap/content/c/build.yaml
  webapp/first_snap/content/golang/build.yaml
  webapp/first_snap/content/golang/snapcraft.yaml
  webapp/first_snap/content/java/build.yaml
  webapp/first_snap/content/moos/build.yaml
  webapp/first_snap/content/node/build.yaml
  webapp/first_snap/content/node/snapcraft.yaml
  webapp/first_snap/content/pre-built/build.yaml
  webapp/first_snap/content/python/build.yaml
  webapp/first_snap/content/python/snapcraft.yaml
  webapp/first_snap/content/ros/build.yaml
  webapp/first_snap/content/ros2/build.yaml
  webapp/first_snap/content/ruby/build.yaml
  webapp/first_snap/content/rust/build.yaml
  webapp/first_snap/content/rust/snapcraft.yaml
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#2547 1047 fsf change build snap section
  static/js/public/accordion.js
  static/sass/_patterns_first-snap-flow.scss
  templates/first-snap/_breadcrumb.html
  templates/first-snap/build-and-test.html
  templates/first-snap/build.html
  templates/first-snap/package.html
  templates/first-snap/push.html
  tests/first_snap/tests_views.py
  webapp/first_snap/content/c/build.yaml
  webapp/first_snap/content/c/test.yaml
  webapp/first_snap/content/golang/build.yaml
  webapp/first_snap/content/golang/test.yaml
  webapp/first_snap/content/java/build.yaml
  webapp/first_snap/content/java/test.yaml
  webapp/first_snap/content/moos/build.yaml
  webapp/first_snap/content/moos/test.yaml
  webapp/first_snap/content/node/build.yaml
  webapp/first_snap/content/node/test.yaml
  webapp/first_snap/content/pre-built/build.yaml
  webapp/first_snap/content/pre-built/test.yaml
  webapp/first_snap/content/python/build.yaml
  webapp/first_snap/content/python/test.yaml
  webapp/first_snap/content/ros/build.yaml
  webapp/first_snap/content/ros/test.yaml
  webapp/first_snap/content/ros2/build.yaml
  webapp/first_snap/content/ros2/test.yaml
  webapp/first_snap/content/ruby/build.yaml
  webapp/first_snap/content/ruby/test.yaml
  webapp/first_snap/content/rust/build.yaml
  webapp/first_snap/content/rust/test.yaml
  webapp/first_snap/views.py
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#2573 Add start script in packages.json for dotrun
  package.json
Labels: Review: Code +1, Review: QA +1

#2568 Snap builds
  .gitignore
  entrypoint
  package.json
  requirements.txt
  static/js/publisher/builds/components/datalistSelect.js
  static/js/publisher/builds/components/repoConnect.js
  static/js/publisher/builds/components/select.js
  static/js/publisher/builds/helpers.js
  static/js/publisher/builds/index.js
  static/js/publisher/publisher.js
  static/sass/_snapcraft_builds.scss
  static/sass/_snapcraft_p-build.scss
  static/sass/styles.scss
  templates/_footer.html
  templates/publisher/_header.html
  templates/publisher/build.html
  templates/publisher/builds.html
  tests/api/cassettes/GitHubTest.test_check_permissions_over_repo.yaml
  tests/api/cassettes/GitHubTest.test_get_org_repositories.yaml
  tests/api/cassettes/GitHubTest.test_get_orgs.yaml
  tests/api/cassettes/GitHubTest.test_get_snapcraft_yaml_location.yaml
  tests/api/cassettes/GitHubTest.test_get_snapcraft_yaml_name.yaml
  tests/api/cassettes/GitHubTest.test_get_user.yaml
  tests/api/cassettes/GitHubTest.test_get_user_repositories.yaml
  tests/api/test_github.py
  tests/api/test_marketo_api.py
  tests/publisher/snaps/test_builds.py
  webapp/api/dashboard.py
  webapp/api/github.py
  webapp/api/marketo.py
  webapp/api/requests.py
  webapp/api/sso.py
  webapp/app.py
  webapp/authentication.py
  webapp/login/oauth_views.py
  webapp/login/views.py
  webapp/publisher/github/views.py
  webapp/publisher/snaps/build_views.py
  webapp/publisher/snaps/builds.py
  webapp/publisher/snaps/views.py
  webapp/publisher/views.py
  webapp/store/views.py
  yarn.lock
Labels: Review: QA +1

#2579 Fix cache issue with GitHub
  tests/api/cassettes/GitHubTest.test_get_snapcraft_yaml_name.yaml
  webapp/api/github.py
Labels: Review: Code +1, Review: QA +1

#2580 Update launchpad library
  requirements.txt
Labels: Review: Code +1, Review: QA +1

#2581 Fix GitHub signature issue
  webapp/api/github.py
  webapp/publisher/snaps/build_views.py
Labels: Review: Code +1, Review: QA +1
