Repository canonical/snapcraft.io, pull requests merged in 2020-06, with the labels that each got.

#2840 Better handle snap details blog posts that don't have images
  static/js/public/snap-details/blog-posts.js
  templates/partials/blog-card--minimal.html
Labels: Review: Code +1, Review: QA +1

#2841 Make delete icon accessible
  static/js/publisher/form/AccordionHelp.js
  static/js/publisher/form/icon.js
Labels: Review: Code +1, Review: QA +1

#2844 BG, BN, and RO buttons to publicise
  static/images/badges/bg/snap-store-black.svg
  static/images/badges/bg/snap-store-white.svg
  static/images/badges/bn/snap-store-black.svg
  static/images/badges/bn/snap-store-white.svg
  static/images/badges/ro/snap-store-black.svg
  static/images/badges/ro/snap-store-white.svg
  webapp/publisher/snaps/publicise_views.py
Labels: Review: Code +1, Review: QA +1

#2868 Update webpack config
  .webpack/entry.js
  .webpack/rules.js
  package.json
  webpack.config.js
  yarn.lock
Labels: Review: Code +1, Review: QA +1

#2872 Fix webpack config includes
  .eslintrc.js
  webpack.config.entry.js
  webpack.config.js
  webpack.config.rules.js
Labels: Review: Code +1, Review: QA +1

#2876 2768 add tests for builds
  .github/workflows/pr.yml
  static/js/publisher/builds/components/datalistSelect.test.js
  static/js/publisher/builds/components/repoConnect.js
  static/js/publisher/builds/components/repoConnect.test.js
  static/js/publisher/builds/components/select.test.js
  static/js/publisher/builds/components/triggerBuild.test.js
  static/js/publisher/builds/helpers.js
  static/js/publisher/builds/helpers.test.js
  yarn.lock
Labels: Review: Code +1, Review: QA +1

#2873 Change listing page title maxlenght to 40 chars
  static/js/publisher/form.js
  static/js/publisher/form.test.js
  static/sass/_patterns_media-object--snap.scss
  static/sass/_snapcraft_market.scss
  static/sass/_snapcraft_p-build.scss
  templates/publisher/listing.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#2883 Change embedded cards height
  static/js/publisher/publicise.js
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#2884 Update to Vanilla 2.13
  package.json
  static/js/public/accordion.js
  static/js/public/first-snap-flow.js
  templates/first-snap/build-and-test.html
  templates/first-snap/package.html
  templates/first-snap/push.html
  yarn.lock
Labels: Review: Code +1, Review: QA +1

#2885 Enable captions by default
  templates/partials/_video.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#2887 Centre align the icon in the middle for buttons
  static/js/publisher/tour/tourStepCard.js
  static/sass/_snapcraft_builds.scss
Labels: Review: Code +1, Review: QA +1

#2894 Add k8s configuration in deploy/site.yaml
  README.md
  deploy/site.yaml
Labels: Review: Code +1

#2896 Show warning about unstable channels
  static/js/public/snap-details/channelMap.js
  templates/store/snap-details/_channel_map.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#2897 Appliance links
  static/sass/_snapcraft_details_heading.scss
  templates/store/snap-details.html
  templates/store/snap-details/_channel_map.html
  webapp/store/snap_details_views.py
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#2895 Changes for new demo service
  .github/pull_request_template.md
  requirements.txt
Labels: Review: Code +1, Review: QA +1

#2899 Update Dockerfile: Remove unnecessary ADD
  Dockerfile
Labels: Review: Code +1, Review: QA +1

#2901 K8s config for limenet, sdrsatcom and staging-api
  deploy/limenet.snapcraft.io.yaml
  deploy/sdrsatcom.snapcraft.io.yaml
  deploy/staging-api.snapcraft.io.yaml
Labels: Review: Code +1

#2902 Shorten build table statuses
  static/js/publisher/builds/helpers.js
Labels: Review: Code +1, Review: QA +1

#2903 Fix warning bug
  static/js/public/snap-details/channelMap.js
  templates/410.html
Labels: Review: Code +1

#2907 Added snap revision JSON endpoint
  requirements.txt
  webapp/publisher/snaps/release_views.py
  webapp/publisher/snaps/views.py
Labels: Review: Code +1, Review: QA +1

#2912 additional messages for risk levels
  static/js/public/snap-details/channelMap.js
  templates/store/snap-details/_channel_map.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#2915 Change label to paragraph
  templates/store/snap-details/_channel_map.html
Labels: Review: Code +1, Review: QA +1

#2916 Remove build with github link from navigaton
  templates/_header.html
Labels: Review: Code +1, Review: QA +1

#2910 Release issues
  static/js/publisher/release/releasesController.js
  static/js/publisher/release/releasesState.js
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#2918 Update canonicalwebteam.blog to 6.0.0
  requirements.txt
  webapp/blog/views.py
Labels: Review: Code +1, Review: QA +1

#2913 Remove logout redirect through BSI
  tests/publisher/tests_account_logout.py
  webapp/login/views.py
Labels: Review: Code needed
