Repository canonical/snapcraft.io, pull requests merged in 2020-05, with the labels that each got.

#2721 Update suru on /build
  static/sass/_patterns_strip_slanted.scss
  static/sass/styles.scss
  templates/snapcraft/build.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#2723 Remove 'key' from 'progressive' following changes in the API
  static/js/publisher/release/actions/pendingReleases.js
  static/js/publisher/release/actions/pendingReleases.test.js
  static/js/publisher/release/actions/releases.js
  static/js/publisher/release/components/releasesConfirm.js
  static/js/publisher/release/components/releasesConfirmDetails/index.js
  static/js/publisher/release/components/releasesConfirmDetails/progressiveRow.js
  static/js/publisher/release/components/revisionsListRowProgressive.js
  static/js/publisher/release/constants.js
  static/js/publisher/release/reducers/pendingReleases.js
  static/js/publisher/release/reducers/pendingReleases.test.js
  static/js/publisher/release/selectors/index.js
Labels: Review: Code +1, Review: QA +1

#2708 Do not open lightbox in a new window on mobile
  static/js/public/snap-details/screenshots.js
  static/sass/_patterns_maas_modal.scss
Labels: Review: Code +1, Review: QA +1

#2727 Fixes #2720: Hiding "Raspberry Pi" from installation instruction
  templates/store/snap-details/_distro-instructions-for-snap-support.html
Labels: Review: Code +1, Review: QA +1

#2730 Remove button spinner on repo disconnect
  package.json
  static/js/publisher/builds/repoDisconnect.js
Labels: Review: Code +1, Review: QA +1

#2743 Handle no repos
  static/js/publisher/builds/components/repoConnect.js
  tests/api/test_github.py
  webapp/api/github.py
Labels: Review: Code +1, Review: QA +1

#2747 Changed build endpoint to return a JSON
  webapp/publisher/snaps/build_views.py
Labels: Review: Code +1, Review: QA +1

#2754 Don't show distro pages for non rpi snaps
  webapp/store/snap_details_views.py
Labels: Review: Code +1, Review: QA +1

#2758 Add usabilla to docs
  templates/docs/base.html
Labels: Review: Code +1, Review: QA +1

#2750 2746 create trigger new build component
  static/js/publisher/builds/components/triggerBuild.js
  static/js/publisher/builds/helpers.js
  static/js/publisher/builds/index.js
  templates/publisher/builds.html
  webapp/publisher/snaps/build_views.py
Labels: Review: Code +1, Review: QA +1

#2755 Update Vanilla to 2.11
  package.json
  static/sass/_patterns_form-multiselect.scss
  yarn.lock
Labels: Review: Code +1, Review: QA +1

#2756 Blog views: Avoid catching generic exceptions
  webapp/blog/views.py
Labels: Review: Code +1, Review: QA +1

#2761 Autofocus search
  templates/partials/search-bar.html
  templates/store/search.html
Labels: Review: Code +1, Review: QA +1

#2766 Update global-nav to latest version
  package.json
  yarn.lock
Labels: Review: Code +1, Review: QA +1

#2769 Add renovate config file
  renovate.json
Labels: Review: Code +1

#2770 Reduce requested permissions from GitHub
  tests/api/cassettes/GitHubTest.test_check_permissions_over_repo.yaml
  tests/api/test_github.py
  webapp/api/github.py
  webapp/login/oauth_views.py
Labels: Review: Code +1, Review: QA +1

#2762 Add outline to elements to match vanilla
  static/sass/_patterns_form-multiselect.scss
  static/sass/_snapcraft_market.scss
  static/sass/_snapcraft_market_screenshots.scss
  templates/publisher/listing.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#2772 Added queue_time when fetching the builds data
  requirements.txt
  webapp/publisher/snaps/build_views.py
Labels: Review: Code +1, Review: QA +1

#2784 Update launchpad library
  requirements.txt
Labels: Review: Code +1, Review: QA +1

#2778 Add estimated launchpad building queue time
  static/js/publisher/builds/index.js
Labels: Review: Code +1, Review: QA +1

#2776 Channel map endpoint
  static/js/publisher/release.js
  static/js/publisher/release/components/releasesTable/channelHeading.js
  static/js/publisher/release/releasesController.js
  static/js/publisher/release/releasesState.js
  static/js/publisher/release/selectors/index.js
  static/js/publisher/release/selectors/selectors.test.js
  static/sass/_snapcraft_release.scss
  templates/publisher/release-history.html
  tests/publisher/snaps/tests_revision.py
  webapp/api/dashboard.py
  webapp/publisher/snaps/release_views.py
Labels: Review: Code +1, Review: QA +1

#2779 Check GitHub webhook branch
  tests/api/cassettes/GitHubTest.test_get_snapcraft_yaml_name.yaml
  webapp/api/github.py
  webapp/publisher/snaps/build_views.py
Labels: Review: Code +1, Review: QA +1

#2818 Update to Vanilla 2.12
  package.json
  static/sass/_snapcraft_p-docs.scss
  yarn.lock
Labels: Review: Code +1, Review: QA +1

#2825 Fix Python dependencies issue
  Dockerfile
Labels: Review: Code +1, Review: QA +1

#2821 Fix default tracks on Release UI
  webapp/publisher/snaps/release_views.py
Labels: Review: Code +1, Review: QA +1

#2823 Fix build page
  static/js/publisher/builds/index.js
  templates/publisher/build.html
Labels: Review: Code +1, Review: QA +1

#2824 List Launchpad builds with status 'Needs building'
  requirements.txt
  webapp/publisher/snaps/build_views.py
Labels: Review: Code +1, Review: QA +1

#2827 Show build error message if it exists
  static/js/publisher/builds/components/triggerBuild.js
  static/js/publisher/builds/index.js
Labels: Review: Code +1, Review: QA +1

#2829 Fix articles error
  webapp/blog/views.py
Labels: Review: Code +1, Review: QA +1

#2830 Show queue time when needs_building
  static/js/publisher/builds/index.js
Labels: Review: Code +1, Review: QA +1

#2831 Add github actions
  .circleci/config.yml
  .github/workflows/main.yml
  .github/workflows/pr.yml
  webapp/api/requests.py
  webapp/blog/views.py
  webapp/publisher/snaps/listing_views.py
  webapp/store/logic.py
Labels: Review: Code +1

#2834 Remove extra info call on releases endpoint
  static/js/publisher/release/releasesState.js
  tests/publisher/snaps/tests_revision.py
  webapp/publisher/snaps/release_views.py
Labels: Review: Code +1, Review: QA +1
