Repository canonical/snapcraft.io, pull requests merged in 2020-11, with the labels that each got.

#3170 Small typo
  README.md
Labels: Review: Code +1

#3173 Generate sitemap.xml
  templates/sitemap.xml
  webapp/snapcraft/views.py
Labels: Review: Code +1, Review: QA +1

#3174 Improve metatags for snap pages
  templates/_layout.html
  templates/store/snap-details.html
Labels: Review: Code +1, Review: QA +1

#3214 Build admin template
  package.json
  static/sass/_snapcraft_l-application.scss
  static/sass/styles.scss
  templates/admin/admin.html
  webapp/store/views.py
Labels: Review: Code +1, Review: QA +1

#3217 Added flask blueprint for admin pages
  webapp/admin/views.py
  webapp/app.py
  webapp/store/views.py
Labels: Review: Code needed, Review: QA needed

#3219 Add stores list to sidebar
  static/sass/_snapcraft_l-application.scss
  static/sass/_snapcraft_p-admin.scss
  static/sass/styles.scss
  templates/admin/_navigation.html
  templates/admin/admin.html
  webapp/admin/views.py
Labels: Review: Code +1, Review: QA +1

#3221 Get stores and list them
  templates/admin/_navigation.html
  templates/admin/admin.html
  webapp/admin/logic.py
  webapp/admin/views.py
Labels: Review: Code +1, Review: QA +1

#3220 Add missing category JSON for snaps
  templates/store/snap-details.html
Labels: Review: Code +1, Review: QA +1

#3226 Switch from sass-lint to stylelint
  .stylelintrc
  package.json
  static/sass/_button-overrides.scss
  static/sass/_map.scss
  static/sass/_pattern-hero-tab.scss
  static/sass/_patterns_annotated_code.scss
  static/sass/_patterns_blog-post.scss
  static/sass/_patterns_button_spinner.scss
  static/sass/_patterns_carousel.scss
  static/sass/_patterns_distro_banner.scss
  static/sass/_patterns_form-multiselect.scss
  static/sass/_patterns_logo-links.scss
  static/sass/_patterns_maas_modal.scss
  static/sass/_patterns_media-object--snap.scss
  static/sass/_patterns_pagination.scss
  static/sass/_patterns_strip_slanted.scss
  static/sass/_patterns_testimonial.scss
  static/sass/_search-form.scss
  static/sass/_snapcraft-publicise.scss
  static/sass/_snapcraft-publisher.scss
  static/sass/_snapcraft_banner.scss
  static/sass/_snapcraft_custom-cols.scss
  static/sass/_snapcraft_custom-typography.scss
  static/sass/_snapcraft_details_heading.scss
  static/sass/_snapcraft_distro-chart.scss
  static/sass/_snapcraft_embedded_card_modal.scss
  static/sass/_snapcraft_graph-tooltip.scss
  static/sass/_snapcraft_market.scss
  static/sass/_snapcraft_market_screenshots.scss
  static/sass/_snapcraft_metrics.scss
  static/sass/_snapcraft_p-build.scss
  static/sass/_snapcraft_p-code-copyable.scss
  static/sass/_snapcraft_p-featured-snap.scss
  static/sass/_snapcraft_p-form-validation.scss
  static/sass/_snapcraft_p-navigation.scss
  static/sass/_snapcraft_p-progressive-bar.scss
  static/sass/_snapcraft_p-release-details-row.scss
  static/sass/_snapcraft_p-tutorials.scss
  static/sass/_snapcraft_p-verified.scss
  static/sass/_snapcraft_patterns_icons.scss
  static/sass/_snapcraft_release.scss
  static/sass/_snapcraft_show-more.scss
  static/sass/_snapcraft_snap-details.scss
  static/sass/_snapcraft_tour.scss
  static/sass/_utilities_disabled.scss
  static/sass/styles-embedded.scss
  static/sass/styles.scss
  yarn.lock
Labels: Review: Code +1

#3227 Add members view
  static/sass/_snapcraft_l-application.scss
  static/sass/styles.scss
  templates/admin/_navigation.html
  templates/admin/members.html
  webapp/admin/views.py
Labels: Review: Code +1, Review: QA +1

#3228 Get brand store snaps
  Dockerfile
  requirements.txt
  templates/admin/_snaps_section.html
  webapp/admin/logic.py
  webapp/admin/views.py
  webapp/authentication.py
Labels: Review: Code +1, Review: QA +1

#3229 Get store members API data
  templates/admin/_navigation.html
  templates/admin/members.html
  webapp/admin/views.py
Labels: Review: Code +1, Review: QA +1

#3233 Build admin settings page
  static/sass/_snapcraft_p-form-help-text.scss
  static/sass/styles.scss
  templates/admin/_navigation.html
  templates/admin/settings.html
  webapp/admin/views.py
Labels: Review: Code +1, Review: QA +1

#3236 Update discourse module
  requirements.txt
  templates/_header.html
  webapp/docs/views.py
  webapp/snapcraft/views.py
  webapp/tutorials/views.py
Labels: Review: Code +1, Review: QA +1

#3234 Members API
  templates/admin/admin_layout.html
  templates/admin/manage_members.html
  templates/admin/members.html
  webapp/admin/views.py
Labels: Review: Code +1, Review: QA +1

#3238 Split sitemap.xml
  templates/sitemap.xml
  templates/sitemap/sitemap-index.xml
  templates/sitemap/sitemap.xml
  webapp/blog/views.py
  webapp/snapcraft/views.py
  webapp/store/views.py
Labels: Review: Code +1, Review: QA +1

#3239 Remove bleach for descirption
  webapp/store/snap_details_views.py
Labels: Review: Code +1, Review: QA +1
