Repository canonical/snapcraft.io, pull requests merged in 2020-10, with the labels that each got.

#3093 Fetch builds only after the previous fetch finished
  static/js/publisher/builds/index.js
Labels: Review: Code +1, Review: QA +1

#3084 Remove extra slash for badge URLs
  static/js/publisher/publicise.js
Labels: Review: Code +1, Review: QA +1

#3080 Install webhook button
  HACKING.md
  konf/site.yaml
  templates/publisher/builds.html
  templates/publisher/settings.html
  webapp/login/oauth_views.py
  webapp/publisher/snaps/build_views.py
  webapp/publisher/snaps/views.py
Labels: Review: Code +1, Review: QA +1

#3095 HACKING.md - Snap automated builds
  HACKING.md
Labels: Review: Code needed

#3097 Issue 3030 - Center aligned the text under the logos
  templates/partials/fsf_language.html
Labels: Review: Code +1, Review: QA +1

#3096 Changed pagination links to buttons
  templates/store/search.html
Labels: Review: Code +1, Review: QA +1

#3107 Remove timeout limit
  webapp/api/requests.py
  webapp/helpers.py
  webapp/login/views.py
  webapp/publisher/snaps/build_views.py
  webapp/publisher/snaps/listing_views.py
  webapp/publisher/snaps/metrics_views.py
  webapp/publisher/snaps/publicise_views.py
  webapp/publisher/snaps/release_views.py
  webapp/publisher/snaps/settings_views.py
  webapp/publisher/snaps/views.py
  webapp/publisher/views.py
Labels: Review: Code +1

#3085 Set width and height to thumbnails
  requirements.txt
  webapp/blog/views.py
Labels: Review: Code +1, Review: QA +1

#3110 Env variable for tests
  .env
  tests/publisher/snaps/tests_post_settings.py
  tests/publisher/snaps/tests_settings.py
Labels: Review: Code +1, Review: QA +1

#3112 Use new summary button for loading builds
  static/js/publisher/builds/components/buildsTable.js
  static/js/publisher/builds/index.js
  static/sass/_snapcraft_release.scss
  static/sass/styles.scss
Labels: Review: Code +1, Review: QA +1

#3108 Integrate cookie-policy v3.0.3
  package.json
  run
  static/js/base/cookie-policy.js
  static/sass/styles.scss
  templates/_footer.html
  templates/_layout.html
  webpack.config.entry.js
  yarn.lock
Labels: Review: Code +1, Review: QA +1

#3125 Display full channel name
  static/sass/_snapcraft_graph-tooltip.scss
Labels: Review: Code +1, Review: QA +1, hacktoberfest-accepted

#3124 Show unlisted visibility in the snaps table
  templates/publisher/account-snaps.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#3131 Remove sqlite cached session
  requirements.txt
  tests/tests_requests_cache.py
  webapp/api/requests.py
  webapp/app.py
  webapp/store/views.py
Labels: Review: Code +1

#3132 Configure talisker session for publisher API
  webapp/app.py
Labels: Review: Code needed

#3123 Show error message for collaborators
  webapp/publisher/snaps/build_views.py
Labels: Review: Code +1, Review: QA +1

#3133 Update snap store privacy notice
  templates/_footer.html
  templates/publisher/developer_programme_agreement.html
Labels: Review: Code +1, Review: QA +1

#3142 Rearrange the tooltip for maximum viewage
  static/js/publisher/metrics/graphs/activeDevicesGraph/tooltips.js
  static/sass/_snapcraft_graph-tooltip.scss
Labels: Review: Code +1, Review: QA +1

#3152 Fix forEach error for hero tabpanel on homepage
  static/js/public/hero-tabpanel.js
Labels: Review: Code +1, Review: QA +1

#3157 Migrate from LibSass to Dart Sass
  package.json
  yarn.lock
Labels: Review: Code +1, Review: QA +1
