Repository canonical/snapcraft.io, pull requests merged in 2020-09, with the labels that each got.

#3039 Update /about/listing headings
  templates/about/listing.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#3044 Update supported openSUSE Leap versions
  webapp/store/content/distros/opensuse.yaml
Labels: Review: Code +1, Review: QA +1

#3048 Show only verified snaps as verified on homepage carousel
  static/js/public/hero-tabpanel.js
Labels: Review: Code +1, Review: QA +1

#3050 Fix error when auth is stale
  requirements.txt
Labels: Review: Code +1

#3051 Add architecture metrics on publisher page
  templates/publisher/metrics.html
  webapp/publisher/snaps/logic.py
Labels: Review: Code +1, Review: QA +1

#3053 Remove quote plus not required for API call
  webapp/store/views.py
Labels: Review: Code +1, Review: QA +1

#3059 Set a default timeout
  webapp/api/requests.py
Labels: Review: Code +1, Review: QA +1

#3071 Update flask-base
  requirements.txt
Labels: Review: Code +1, Review: QA +1

#3075 Fix 500 error after webhook creation
  webapp/api/github.py
  webapp/publisher/snaps/build_views.py
Labels: Review: Code needed, Review: QA needed

#3069 Add Github actions badge to readme
  .github/workflows/master.yml
  README.md
Labels: Review: Code +1

#3078 Remove hard coded categories
  webapp/docs/views.py
Labels: Review: Code +1, Review: QA +1

#3063 Use ModularTable for builds
  static/js/publisher/builds/components/buildsTable.js
  static/js/publisher/builds/index.js
  static/sass/_snapcraft_builds.scss
  static/sass/styles.scss
Labels: Review: Code +1, Review: QA +1
