Repository canonical/snapcraft.io, pull requests merged in 2021-11, with the labels that each got.

#3753 Fix global snaps in brand store
  static/js/brand-store/Snaps/Snaps.js
  static/js/brand-store/Snaps/SnapsTable.js
  static/js/brand-store/Snaps/SnapsTableRow.js
Labels: Review: Code +1, Review: QA +1

#3752 Fix brand store mobile
  static/js/brand-store/Snaps/Snaps.js
  static/js/brand-store/Snaps/SnapsFilter.js
Labels: Review: Code +1, Review: QA +1

#3760 Update snapcraft.yaml for ROS
  templates/home/_fsf_ros.html
  webapp/first_snap/content/ros/snapcraft.yaml
Labels: Review: Code +1, Review: QA +1

#3759 Copy update
  templates/index.html
Labels: Review: Code +1, Review: QA +1

#3761 Homepage a11y fixes
  static/js/public/hero-tabpanel.js
  templates/_footer.html
  templates/_header-brandstore.html
  templates/_header.html
  templates/home/_fsf_c.html
  templates/home/_fsf_electron.html
  templates/home/_fsf_flutter.html
  templates/home/_fsf_go.html
  templates/home/_fsf_java.html
  templates/home/_fsf_moos.html
  templates/home/_fsf_node.html
  templates/home/_fsf_pre-built.html
  templates/home/_fsf_python.html
  templates/home/_fsf_ros.html
  templates/home/_fsf_ros2.html
  templates/home/_fsf_ruby.html
  templates/home/_fsf_rust.html
  templates/index.html
Labels: Review: Code +1, Review: QA +1

#3764 Homepage a11y fixes (#3761)
  static/js/public/hero-tabpanel.js
  templates/_footer.html
  templates/_header-brandstore.html
  templates/_header.html
  templates/home/_fsf_c.html
  templates/home/_fsf_electron.html
  templates/home/_fsf_flutter.html
  templates/home/_fsf_go.html
  templates/home/_fsf_java.html
  templates/home/_fsf_moos.html
  templates/home/_fsf_node.html
  templates/home/_fsf_pre-built.html
  templates/home/_fsf_python.html
  templates/home/_fsf_ros.html
  templates/home/_fsf_ros2.html
  templates/home/_fsf_ruby.html
  templates/home/_fsf_rust.html
  templates/index.html
Labels: Review: Code +1, Review: QA +1

#3776 Setup typescript for brandstore
  package.json
  static/js/brand-store/Snaps/Snaps.js
  tsconfig.json
  webpack.config.rules.js
  yarn.lock
Labels: Review: Code +1 (with changes)

#3777 Convert first pages to typescript
  static/js/brand-store/NoStores/NoStores.test.tsx
  static/js/brand-store/NoStores/NoStores.tsx
  static/js/brand-store/NoStores/index.ts
  static/js/brand-store/NotAuthorized/NotAuthorized.test.tsx
  static/js/brand-store/NotAuthorized/NotAuthorized.tsx
  static/js/brand-store/NotAuthorized/index.ts
  tsconfig.json
  webpack.config.js
  webpack.config.rules.js
Labels: Review: Code +1, Review: QA +1

#3784 Fix button margins on brand store invites table
  static/sass/styles.scss
Labels: Review: Code +1, Review: UX +1, Review: QA +1

#3782 Setup typescript for brandstore
  .babelrc
  package.json
  static/js/brand-store/Settings/Settings.test.tsx
  static/js/brand-store/Settings/Settings.tsx
  static/js/brand-store/Settings/index.ts
  static/js/brand-store/types/global.d.ts
  static/js/brand-store/types/shared.ts
  tsconfig.json
  yarn.lock
Labels: Review: Code +1
