Repository canonical/snapcraft.io, pull requests merged in 2021-02, with the labels that each got.

#3378 Fix word break in code element
  static/sass/styles.scss
Labels: Review: Code +1, Review: QA +1

#3381 Add collaborators col to snaps table
  templates/admin/_snaps_section.html
Labels: Review: Code +1, Review: QA +1

#3384 Add latest release data to snaps admin table
  templates/admin/_snaps_section.html
  tests/tests_templates_utils.py
  webapp/handlers.py
  webapp/template_utils.py
Labels: Review: Code +1, Review: QA +1

#3385 Make fsf links persistent with the fsf ABC test option
  static/js/public/first-snap-flow.js
  templates/first-snap/_breadcrumb.html
  templates/first-snap/build-and-test.html
  templates/first-snap/create-account.html
  templates/first-snap/install-snapcraft.html
  templates/first-snap/package.html
  templates/first-snap/push.html
  templates/home/_fsf_c.html
  templates/home/_fsf_flutter.html
  templates/home/_fsf_go.html
  templates/home/_fsf_java.html
  templates/home/_fsf_moos.html
  templates/home/_fsf_node.html
  templates/home/_fsf_pre-built.html
  templates/home/_fsf_python.html
  templates/home/_fsf_ros.html
  templates/home/_fsf_ros2.html
  templates/home/_fsf_ruby.html
  templates/home/_fsf_rust.html
  webapp/first_snap/views.py
  webapp/first_snap/views_2.py
  webapp/first_snap/views_3.py
Labels: Review: Code +1, Review: QA +1

#3386 Fix bug with closing admin page navigation
  static/sass/styles.scss
  templates/admin/admin_layout.html
Labels: Review: Code +1, Review: QA +1

#3387 Make snaps admin table use card pattern
  templates/admin/_snaps_section.html
Labels: Review: Code +1, Review: QA +1

#3389 Use Vanilla fix for app navigation pattern
  static/sass/styles.scss
  templates/admin/admin_layout.html
Labels: Review: Code +1, Review: QA +1

#3392 Disable talisker context logger
  tests/__init__.py
Labels: Review: Code +1

#3390 Link snap name to page if public
  templates/admin/_snaps_section.html
Labels: Review: Code +1, Review: QA +1

#3379 Fix tooltip on release page contextual menu
  static/js/publisher/release/components/channelMenu.js
Labels: Review: Code +1, Review: QA +1

#3396 Added post_manage_store_snaps
  requirements.txt
  webapp/admin/views.py
Labels: Review: Code needed, Review: QA needed

#3395 Allow adding and removing of snaps from store
  static/js/public/manage-snaps.js
  templates/admin/manage_snaps.html
  webpack.config.entry.js
  webpack.config.rules.js
Labels: Review: Code +1, Review: QA +1

#3398 Filter members
  static/js/public/manage-members.js
  templates/admin/manage_members.html
Labels: Review: Code +1, Review: QA +1

#3401 Trigger optimize event when user clicks on a language
  static/js/public/fsf-language-select.js
Labels: Review: Code +1, Review: QA +1

#3400 Design amends for manage members page
  static/sass/_snapcraft_l-application.scss
  templates/admin/manage_members.html
  templates/admin/manage_snaps.html
Labels: Review: Code +1, Review: UX +1

#3391 Add noscript pixel
  templates/_layout.html
  webapp/snapcraft/snapcraft.png
  webapp/snapcraft/views.py
Labels: Review: Code +1, Review: QA +1

#3405 Remove store column from tables
  static/js/public/manage-members.js
  templates/admin/_snaps_section.html
  templates/admin/manage_members.html
  templates/admin/manage_snaps.html
  templates/admin/members.html
Labels: Review: Code +1, Review: QA +1

#3406 Count accept-encoding instances in prometheus
  requirements.txt
  webapp/handlers.py
Labels: Review: Code +1

#3412 Add changes count to members save button
  static/js/public/manage-members.js
Labels: Review: Code +1, Review: QA +1

#3413 Change wording of manage snaps page heading
  templates/admin/manage_snaps.html
Labels: Review: Code +1, Review: QA +1

#3404 Add manage member invites form
  requirements.txt
  static/js/public/manage-invites.js
  static/js/public/manage-members.js
  static/sass/_pattern_p-button-group.scss
  static/sass/_snapcraft_p-action-form.scss
  static/sass/styles.scss
  templates/admin/_manage_invites_form.html
  templates/admin/admin_layout.html
  templates/admin/invites.html
  templates/admin/manage_members.html
  templates/admin/members.html
  tests/tests_templates_utils.py
  webapp/admin/views.py
  webapp/handlers.py
  webapp/template_utils.py
  webpack.config.entry.js
  webpack.config.rules.js
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#3415 Add changed state to manage member checkboxes
  static/js/public/manage-members.js
  static/sass/_snapcraft_custom-checkboxes.scss
  static/sass/styles.scss
  templates/admin/manage_members.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#3422 Add width and height attributes to verified account icon
  templates/partials/_verified_developer.html
Labels: Review: Code +1, Review: QA +1

#3420 Add width and height attributes to site logo
  templates/_header.html
Labels: Review: Code +1, Review: QA +1

#3424 Preload hero background image
  templates/_layout.html
Labels: Review: Code +1, Review: QA +1

#3428 Remove exception for first snap on the list
  templates/admin/_snaps_section.html
Labels: Review: Code +1, Review: QA +1

#3426 Add missing as attribute to preloaded image
  templates/_layout.html
Labels: Review: Code +1, Review: QA +1

#3416 Added Candid login
  HACKING.md
  konf/staging-api.snapcraft.io.yaml
  requirements.txt
  tests/first_snap/tests_views.py
  tests/login/tests_login_handler.py
  tests/publisher/endpoint_testing.py
  tests/publisher/tests_publisher.py
  tests/store/tests_details.py
  tests/store/tests_github_badge.py
  webapp/authentication.py
  webapp/first_snap/views.py
  webapp/first_snap/views_2.py
  webapp/first_snap/views_3.py
  webapp/handlers.py
  webapp/login/views.py
  webapp/publisher/snaps/views.py
  webapp/publisher/views.py
  webapp/store/snap_details_views.py
Labels: Review: Code +1, Review: QA +1

#3418 Add invite member form to invites page
  static/js/public/invite-members.js
  static/js/public/manage-invites.js
  static/js/public/manage-members.js
  static/js/public/modal.js
  static/sass/styles.scss
  templates/admin/_invites_modal.html
  templates/admin/_manage_invites_form.html
  templates/admin/invites.html
  templates/admin/manage_members.html
  webapp/admin/views.py
  webpack.config.entry.js
  webpack.config.rules.js
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#3430 Fix bug with manage snaps save button
  static/js/public/manage-snaps.js
Labels: Review: Code +1, Review: QA +1

#3433 Add user email address to invite action confirmation modal
  static/js/public/manage-invites.js
Labels: Review: Code +1, Review: QA +1
