Repository canonical/snapcraft.io, pull requests merged in 2021-03, with the labels that each got.

#3444 Close history when the track is changed
  static/js/publisher/release/components/releasesHeading.js
Labels: Review: Code +1, Review: QA +1

#3445 Fix search exception
  tests/store/tests_search.py
  webapp/store/views.py
Labels: Review: Code +1

#3446 Check if user agent defined
  webapp/handlers.py
Labels: Review: Code +1

#3453 Enable Candid authentication
  webapp/login/views.py
Labels: Review: Code +1, Review: QA +1

#3454 Catch error when continued or new devices do not exist
  static/js/publisher/metrics/metrics.js
Labels: Review: Code +1, Review: QA +1

#3465 Empty macaroons in session on login
  webapp/login/views.py
Labels: Review: Code +1, Review: QA +1

#3466 Fix wrong variables to pop
  webapp/login/views.py
Labels: Review: Code needed

#3464 Fix sentry error
  static/js/publisher/publicise.js
Labels: Review: Code +1, Review: QA +1

#3452 Pin pull licenses from spdx repo
  .gitignore
  HACKING.md
  package.json
  webapp/helpers.py
  webapp/licenses.json
  webapp/store-licenses.json
Labels: Review: Code +1, Review: QA +1

#3442 Add logic to get YouTube thumbnail URL
  konf/site.yaml
  static/sass/_snapcraft-p-videos.scss
  templates/partials/_video.html
  webapp/store/views.py
Labels: Review: Code +1, Review: QA +1

#3476 Update header build snapcraft.io
  templates/snapcraft/build.html
Labels: Review: Code +1

#3479 Add action to check docs links
  .github/workflows/docs-links.yaml
Labels: Review: Code +1, Review: QA +1
