Repository canonical/snapcraft.io, pull requests merged in 2021-09, with the labels that each got.

#3665 Fix metrics
  webapp/publisher/snaps/metrics_views.py
Labels: Review: Code +1, Review: QA +1

#3668 Add stores side nav to admin
  package.json
  static/js/brand-store/App/App.js
  static/js/brand-store/App/index.js
  static/js/brand-store/Invites/Invites.js
  static/js/brand-store/Invites/index.js
  static/js/brand-store/Members/Members.js
  static/js/brand-store/Members/index.js
  static/js/brand-store/Navigation/Navigation.js
  static/js/brand-store/Navigation/index.js
  static/js/brand-store/NoStores/NoStores.js
  static/js/brand-store/NoStores/index.js
  static/js/brand-store/Settings/Settings.js
  static/js/brand-store/Settings/index.js
  static/js/brand-store/Snaps/Snaps.js
  static/js/brand-store/Snaps/index.js
  static/js/brand-store/brand-store.js
  static/js/brand-store/selectors/index.js
  static/js/brand-store/slices/brandStoreSlice.js
  static/js/brand-store/stores/store.js
  static/sass/_patterns_icons.scss
  static/sass/_snapcraft_l-application.scss
  static/sass/styles.scss
  templates/_base-layout.html
  templates/admin/admin.html
  templates/admin/admin_layout.html
  webapp/admin/views.py
  webapp/snapcraft/views.py
  webpack.config.entry.js
  yarn.lock
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#3676 Remove upload metadata on release field
  templates/publisher/listing.html
  templates/publisher/settings.html
Labels: Review: Code +1, Review: QA +1

#3683 Write brand store settings form tests
  static/js/brand-store/Settings/Settings.test.js
Labels: Review: Code +1, Review: QA +1

#3693 Add snaps table
  static/js/brand-store/App/App.js
  static/js/brand-store/Members/Members.js
  static/js/brand-store/Navigation/Navigation.js
  static/js/brand-store/SectionNav/SectionNav.js
  static/js/brand-store/SectionNav/SectionNav.test.js
  static/js/brand-store/SectionNav/index.js
  static/js/brand-store/Settings/Settings.js
  static/js/brand-store/Settings/Settings.test.js
  static/js/brand-store/Snaps/Snaps.js
  static/js/brand-store/Snaps/SnapsFilter.js
  static/js/brand-store/Snaps/SnapsTable.js
  static/js/brand-store/Snaps/SnapsTableRow.js
  static/js/brand-store/brand-store.js
  static/js/brand-store/selectors/index.js
  static/js/brand-store/slices/snapsSlice.js
  static/js/brand-store/store/index.js
  static/sass/_snapcraft_l-application.scss
  static/sass/styles.scss
  webapp/admin/views.py
Labels: Review: Code +1, Review: QA +1

#3701 Add snaps section
  package.json
  static/js/brand-store/Snaps/Snaps.js
  static/js/brand-store/Snaps/SnapsFilter.js
  static/js/brand-store/Snaps/SnapsSearch.js
  static/js/brand-store/Snaps/SnapsTable.js
  static/js/brand-store/Snaps/SnapsTableRow.js
  static/sass/_snapcraft_l-application.scss
  static/sass/_snapcraft_p-autocomplete.scss
  static/sass/_snapcraft_p-search-results.scss
  static/sass/styles.scss
  webapp/admin/views.py
  yarn.lock
Labels: Review: Code +1, Review: QA +1

#3702 Add members and invites table
  static/js/brand-store/Members/Members.js
  static/js/brand-store/selectors/index.js
  static/js/brand-store/slices/invitesSlice.js
  static/js/brand-store/slices/membersSlice.js
  static/js/brand-store/store/index.js
  static/sass/styles.scss
  webapp/admin/views.py
Labels: Review: Code +1, Review: QA +1

#3703 Add members filter
  static/js/brand-store/Members/Members.js
Labels: Review: Code +1, Review: QA +1

#3704 Fix non-existing repositories issue
  webapp/api/github.py
  webapp/publisher/snaps/build_views.py
Labels: Review: Code +1, Review: QA +1

#3707 Remove usabilla code
  templates/docs/base.html
Labels: Review: Code +1

#3713 Show error message for non-collaborators on releases
  static/js/publisher/release/actions/releases.js
  webapp/publisher/snaps/release_views.py
Labels: Review: Code +1, Review: QA +1
