Repository canonical/snapcraft.io, pull requests merged in 2021-01, with the labels that each got.

#3312 Update staging-api.snapcraft.io.yaml
  konf/staging-api.snapcraft.io.yaml
Labels: Review: Code +1

#3314 Remove weekly active devices column
  templates/admin/_snaps_section.html
Labels: Review: Code +1, Review: QA +1

#3316 JSON endpoint to summarize snap builds
  requirements.txt
  webapp/helpers.py
  webapp/publisher/snaps/build_views.py
  webapp/publisher/snaps/builds.py
  webapp/publisher/snaps/settings_views.py
  webapp/publisher/snaps/views.py
Labels: Review: Code +1, Review: QA +1

#3318 Add build status column
  static/js/publisher/build-status.js
  static/js/publisher/publisher.js
  templates/publisher/account-snaps.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#3331 Update env var names
  HACKING.md
  konf/staging-api.snapcraft.io.yaml
  webapp/api/sso.py
Labels: Review: Code +1, Review: QA +1

#3333 Update Launchpad to 0.8.1
  requirements.txt
  tests/publisher/snaps/tests_post_settings.py
  tests/publisher/snaps/tests_settings.py
Labels: Review: Code needed, Review: QA needed

#3337 Update flask-base and use exclude_xframe_options_header
  requirements.txt
  webapp/store/snap_details_views.py
Labels: Review: Code +1, Review: QA +1

#3349 Add icon and links to build summary
  static/js/publisher/build-status.js
  templates/publisher/account-snaps.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#3352 Change font display option to swap
  static/sass/styles.scss
Labels: Review: Code +1, Review: QA +1

#3351 Duplicate fsf routes twice
  templates/home/_fsf_c.html
  templates/home/_fsf_flutter.html
  webapp/app.py
  webapp/first_snap/views_2.py
  webapp/first_snap/views_3.py
Labels: Review: Code +1, Review: QA +1

#3355 Fix ga sentry erros
  static/js/base/ga.js
  templates/first-snap/_layout_fsf.html
  templates/partials/_code-snippet.html
  templates/store/snap-distro-install.html
Labels: Review: Code +1

#3353 Load YouTube video only when needed
  static/images/yt_play_btn.svg
  static/sass/_snapcraft-p-videos.scss
  static/sass/styles.scss
  templates/partials/_video.html
Labels: Review: Code +1, Review: QA +1

#3357 Throw error when ga-scroll element does not exist
  static/js/public/ga-scroll-event.js
Labels: Review: Code +1, Review: QA +1

#3360 Show built at time for launchpad builds
  static/js/publisher/release/components/releasesTable/channelHeading.js
Labels: Review: Code +1, Review: QA +1

#3363 Fix misplaced page title on snaps admin page
  templates/admin/snaps.html
Labels: Review: Code +1, Review: QA +1

#3364 Update channel map
  requirements.txt
  static/js/public/snap-details/channelMap.js
  templates/store/snap-embedded-card.html
  tests/store/tests_details.py
  tests/store/tests_distro_page.py
  tests/store/tests_embedded_card.py
  tests/store/tests_get_store_view.py
  tests/store/tests_github_badge.py
  tests/store/tests_public_logic.py
  webapp/store/logic.py
  webapp/store/snap_details_views.py
  webapp/store/views.py
Labels: Review: Code +1, Review: QA +1

#3354 Update content for ABC testing
  templates/first-snap/_breadcrumb.html
  templates/first-snap/create-account.html
  templates/first-snap/install-snapcraft.html
  templates/first-snap/push.html
  templates/home/_fsf_c.html
  templates/home/_fsf_flutter.html
  templates/home/_fsf_go.html
  templates/home/_fsf_java.html
  templates/home/_fsf_moos.html
  templates/home/_fsf_node.html
  templates/home/_fsf_pre-built.html
  templates/home/_fsf_python.html
  templates/home/_fsf_ros.html
  templates/home/_fsf_ros2.html
  templates/home/_fsf_ruby.html
  templates/home/_fsf_rust.html
  webapp/first_snap/views.py
  webapp/first_snap/views_2.py
  webapp/first_snap/views_3.py
Labels: Review: Code +1, Review: QA +1, Review: UX +1
