Repository canonical/snapcraft.io, pull requests merged in 2021-05, with the labels that each got.

#3526 Update README.md
  README.md
Labels: Review: Code +1

#3529 Empty invites state
  templates/admin/invites.html
Labels: Review: Code +1, Review: QA +1, Review: UX needed

#3532 Change collaborators column name
  templates/admin/snaps.html
Labels: Review: Code +1, Review: QA +1

#3533 Hide 'Edit details' link
  templates/_header.html
  templates/publisher/account-details.html
Labels: Review: Code +1, Review: QA +1

#3537 Fix heading size on details page
  templates/store/snap-details/_distro-instructions-for-snap-support.html
Labels: Review: Code +1, Review: QA +1

#3550 Add store ID field to setting page
  static/sass/_patterns_p-password-toggle-input.scss
  static/sass/styles.scss
  templates/admin/settings.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#3534 Add search field
  package.json
  static/js/public/manage-snaps.js
  static/js/public/utilities/build-snaps-table-row.js
  static/sass/_snapcraft_p-search-results.scss
  static/sass/_snapcraft_p-side-panel.scss
  static/sass/styles.scss
  templates/admin/snaps.html
  webapp/admin/views.py
  yarn.lock
Labels: Review: Code +1, Review: QA +1

#3555 Update title and button on snap distribution page
  templates/store/snap-distro-install.html
Labels: Review: Code +1

#3556 Update first snap flow
  templates/first-snap/_breadcrumb.html
  templates/first-snap/build-and-test.html
  templates/first-snap/upload.html
  tests/first_snap/tests_views.py
  webapp/app.py
  webapp/first_snap/views.py
  webapp/first_snap/views_2.py
  webapp/first_snap/views_3.py
Labels: Review: Code +1, Review: QA +1

#3559 Remove hardcoded companion apps section
  templates/store/snap-details.html
Labels: Review: Code +1, Review: Code needed, Review: QA +1

#3557 Remove hardcoded omgubuntu blog posts
  webapp/blog/content/blog-posts.yaml
  webapp/blog/views.py
Labels: Review: Code +1, Review: QA +1

#3554 Change title on snap details page
  templates/store/snap-details.html
Labels: Review: Code +1, Review: QA +1

#3561 Add missing secrets for the Staging API
  konf/staging-api.snapcraft.io.yaml
Labels: Review: Code +1

#3562 Remove delete icon overrides
  static/sass/_snapcraft_market.scss
  static/sass/_snapcraft_patterns_icons.scss
  static/sass/styles.scss
Labels: Review: Code +1, Review: QA +1

#3564 Remove undefined template variable
  templates/partials/blog-card.html
Labels: Review: Code +1, Review: QA +1
