Repository canonical/snapcraft.io, pull requests merged in 2021-12, with the labels that each got.

#3786 Convert brand store selectors to typescript
  static/js/brand-store/Settings/Settings.tsx
  static/js/brand-store/selectors/index.js
  static/js/brand-store/selectors/index.ts
  static/js/brand-store/store/index.ts
  static/js/brand-store/types/shared.ts
  static/js/publisher/release/actions/releases.test.js
Labels: Review: Code +1

#3791 Change JS test to make it more reliable
  static/js/publisher/release/actions/releases.test.js
Labels: Review: Code +1

#3793 Fix related blog posts
  webapp/blog/views.py
Labels: Review: Code +1, Review: QA +1

#3798 Alias publisher names to IDs in store search
  templates/store/search.html
  webapp/store/views.py
Labels: Review: Code +1, Review: QA +1

#3796 Add Snapcrafters publisher page
  templates/store/publisher-details.html
  webapp/store/content/publishers/snapcrafters-snaps.yaml
  webapp/store/content/publishers/snapcrafters.yaml
  webapp/store/views.py
Labels: Review: Code +1, Review: UX +1, Review: Design +1, Review: QA +1

#3801 Convert brand store section nav to TypeScript
  static/js/brand-store/SectionNav/SectionNav.test.tsx
  static/js/brand-store/SectionNav/SectionNav.tsx
  static/js/brand-store/SectionNav/index.ts
Labels: Review: Code +1 (with changes)

#3803 Convert brand store slices to TypeScript
  static/js/brand-store/Settings/Settings.test.tsx
  static/js/brand-store/Settings/Settings.tsx
  static/js/brand-store/brand-store.js
  static/js/brand-store/hooks/index.ts
  static/js/brand-store/slices/brandStoreSlice.ts
  static/js/brand-store/slices/currentStoreSlice.ts
  static/js/brand-store/slices/invitesSlice.ts
  static/js/brand-store/slices/membersSlice.ts
  static/js/brand-store/slices/snapsSlice.ts
  static/js/brand-store/store/index.ts
Labels: Review: Code +1, Review: QA +1

#3806 Fix aspect ratio of Raspberry Pi logo
  templates/store/snap-details/_distro-instructions-for-snap-support.html
  webapp/store/content/distros/raspbian.yaml
Labels: Review: Code +1, Review: QA +1
