Repository canonical/snapcraft.io, pull requests merged in 2022-02, with the labels that each got.

#3872 Revert debugging changes
  webapp/api/requests.py
  webapp/app.py
Labels: Review: Code +1

#3877 Change highlight colour for release table cells
  static/sass/_snapcraft_release.scss
Labels: Review: Code +1, Review: QA +1

#3878 Update copy for update metadata on release
  templates/publisher/settings.html
Labels: Review: Code +1, Review: QA +1

#3884 Display 404 for not supported publishers
  webapp/store/views.py
Labels: Review: Code +1, Review: QA +1

#3888 Upgrade flask-base
  requirements.txt
Labels: Review: Code +1, Review: QA +1

#3890 Add changes summary to bottom of releases UI
  static/js/publisher/release/components/releasesConfirm.js
  static/js/publisher/release/components/releasesConfirmActions.js
  static/js/publisher/release/releasesController.js
  static/sass/_snapcraft_p-release-details-row.scss
  static/sass/_snapcraft_release.scss
Labels: Review: Code +1, Review: QA +1

#3893 Fix Python tests
  tests/login/tests_login_handler.py
  tests/publisher/endpoint_testing.py
  tests/publisher/snaps/tests_post_listing.py
  tests/publisher/snaps/tests_post_release.py
  webapp/publisher/snaps/release_views.py
Labels: Review: Code +1

#3894 Connection close header for API calls
  webapp/api/requests.py
Labels: Review: Code +1

#3895 Replace password toggle component
  static/js/brand-store/Settings/Settings.tsx
  static/js/brand-store/shared/PasswordToggle/PasswordToggle.js
  static/js/brand-store/shared/PasswordToggle/PasswordToggle.test.js
  static/js/brand-store/shared/PasswordToggle/index.js
  static/sass/_patterns_media-object--snap.scss
  static/sass/styles.scss
Labels: Review: Code +1, Review: QA +1

#3889 Add views for publishers and reviewers
  static/js/brand-store/Publisher/Publisher.tsx
  static/js/brand-store/Publisher/index.ts
  static/js/brand-store/Reviewer/Reviewer.tsx
  static/js/brand-store/Reviewer/index.ts
  static/js/brand-store/ReviewerAndPublisher/ReviewerAndPublisher.tsx
  static/js/brand-store/ReviewerAndPublisher/index.ts
  static/js/brand-store/Snaps/Snaps.js
  static/js/brand-store/types/global.d.ts
  templates/admin/admin.html
  webapp/admin/views.py
Labels: Review: Code +1, Review: UX +1, Review: QA +1
