Repository canonical/snapcraft.io, pull requests merged in 2022-04, with the labels that each got.

#3941 Check if GitHub app was revoked for snaps that are linked
  templates/publisher/builds.html
  webapp/api/github.py
  webapp/publisher/snaps/build_views.py
Labels: Review: Code +1, Review: QA +1

#3942 fix(ros2-first-snap): remove already satisfied dependencies
  templates/home/_fsf_ros2.html
  webapp/first_snap/content/ros2/snapcraft.yaml
Labels: Review: Code +1, Review: UX +1

#3945 Only show pipe if build-request-id is available
  static/js/publisher/release/components/releasesTable/cellViews.js
Labels: Review: Code +1, Review: QA +1

#3946 Release UI - compact dates
  static/js/publisher/release/components/releasesTable/channelHeading.js
  static/sass/_snapcraft_release.scss
Labels: Review: Code +1, Review: QA +1

#3944 Update reviewer/publisher messages
  static/js/brand-store/Publisher/Publisher.tsx
  static/js/brand-store/Reviewer/Reviewer.tsx
  static/js/brand-store/ReviewerAndPublisher/ReviewerAndPublisher.tsx
Labels: Review: Code +1, Review: QA +1

#3949 Progressive releases table cell
  static/js/publisher/release/components/releasesTable/cellViews.js
  static/js/publisher/release/components/releasesTable/releaseCell.js
  static/js/publisher/release/components/revisionLabel.js
  static/js/publisher/release/components/revisionsList.js
  static/js/publisher/release/components/revisionsListRow.js
  static/js/publisher/release/releasesState.js
  static/sass/_snapcraft_release.scss
  templates/publisher/release-history.html
Labels: Review: Code +1, Review: QA +1

#3955 Fix double publisher in header
  templates/store/snap-details/_snap_heading_data.html
Labels: Review: Code +1, Review: QA +1

#3954 Add progressive release tooltip
  static/js/publisher/release/components/releasesTable/cellViews.js
  static/js/publisher/release/components/releasesTable/releaseCell.js
  static/js/publisher/release/components/revisionLabel.js
  static/js/publisher/release/selectors/index.js
  static/js/publisher/release/selectors/selectors.test.js
  static/sass/_snapcraft_release.scss
Labels: Review: QA +1, Review: Code +1 (with changes)

#3956 Fix publicise checkboxes
  templates/publisher/publicise/embedded_cards.html
  templates/publisher/publicise/github_badges.html
Labels: Review: Code +1, Review: QA +1

#3963 Use ID from URL in brand store settings
  static/js/brand-store/Settings/Settings.test.tsx
  static/js/brand-store/Settings/Settings.tsx
Labels: Review: Code +1, Review: QA +1

#3968 Fix release table row hover state
  static/js/publisher/release/components/releasesTable/cellViews.js
  static/js/publisher/release/components/releasesTable/channelHeading.js
  static/js/publisher/release/components/releasesTable/row.js
Labels: Review: Code +1, Review: QA +1

#3967 Fix brand store sentry error
  static/js/brand-store/Snaps/SnapsFilter.js
Labels: Review: Code +1, Review: QA +1

#3966 Snapcraft Builds: Fix spinner position
  static/js/publisher/builds/components/repoConnect.js
Labels: Review: Code +1, Review: QA +1

#3964 Add progressive release column to history table
  static/js/publisher/release/components/releasesTable/cellViews.js
  static/js/publisher/release/components/releasesTable/releaseCell.js
  static/js/publisher/release/components/revisionsList.js
  static/js/publisher/release/components/revisionsListRow.js
  static/js/publisher/release/components/revisionsListRowProgressive.js
  static/sass/_snapcraft_release.scss
  static/sass/styles.scss
Labels: Review: Code +1, Review: UX +1, Review: Design +1, Review: QA +1

#3975 Fix brand store snaps table on mobile
  static/js/brand-store/Snaps/SnapsTable.js
  static/js/brand-store/Snaps/SnapsTableRow.js
  static/sass/styles.scss
Labels: Review: Code +1, Review: UX +1, Review: QA +1

#3978 Remove release UI actions on mobile
  static/js/publisher/release/components/contextualMenu.js
  static/js/publisher/release/components/dnd.js
  static/js/publisher/release/components/releasesTable/cellViews.js
  static/js/publisher/release/components/releasesTable/channelHeading.js
  static/js/publisher/release/releasesController.js
Labels: Review: Code +1, Review: UX +1, Review: QA +1

#3979 Convert release UI history table to cards
  static/js/publisher/release/components/revisionsList.js
  static/js/publisher/release/components/revisionsListRow.js
Labels: Review: Code +1, Review: QA +1

#3980 Add security.txt
  requirements.txt
  security.txt
Labels: Review: Code +1, Review: QA +1

#3983 Show all brand stores
  static/js/brand-store/Snaps/Snaps.js
  static/js/brand-store/Snaps/SnapsTable.js
Labels: Review: Code +1, Review: QA +1
