Repository canonical/snapcraft.io, pull requests merged in 2022-06, with the labels that each got.

#4015 Add release progress chart for previous revisions
  static/js/publisher/release/components/ProgressiveReleaseProgressChart.tsx
  static/js/publisher/release/components/revisionsList.js
  static/js/publisher/release/components/revisionsListRow.js
  static/sass/_snapcraft_release.scss
Labels: Review: Code +1, Review: UX +1, Review: QA +1

#4018 Move listing page links to sidebar
  templates/store/snap-details.html
  templates/store/snap-details/_details.html
Labels: Review: Code +1, Review: QA +1

#4017 Update search to fix no results issue
  requirements.txt
Labels: Review: Code +1, Review: QA +1

#4020 Add metadata links to listing page template
  static/sass/_snapcraft_metadata-links.scss
  static/sass/styles.scss
  templates/store/snap-details/_details.html
  tests/tests_templates_utils.py
  webapp/handlers.py
  webapp/store/snap_details_views.py
  webapp/template_utils.py
Labels: Review: Code +1, Review: UX +1, Review: QA +1

#4022 Update design for metadata links on snap page
  static/sass/_snapcraft_metadata-links.scss
  static/sass/styles.scss
  templates/store/snap-details/_details.html
Labels: Review: Code +1, Review: UX +1, Review: QA +1

#4026 Move listing form fields into partials
  templates/publisher/listing.html
  templates/publisher/metadata/_category.html
  templates/publisher/metadata/_contact.html
  templates/publisher/metadata/_description.html
  templates/publisher/metadata/_featured-banner.html
  templates/publisher/metadata/_license.html
  templates/publisher/metadata/_metrics.html
  templates/publisher/metadata/_screenshots.html
  templates/publisher/metadata/_snap-icon.html
  templates/publisher/metadata/_summary.html
  templates/publisher/metadata/_title.html
  templates/publisher/metadata/_video.html
  templates/publisher/metadata/_website.html
Labels: Review: Code +1, Review: QA +1

#4025 Update icons for metadata links
  static/sass/_patterns_icons.scss
  templates/store/snap-details/_details.html
Labels: Review: Code +1, Review: UX +1, Review: QA +1

#4027 Add new metadata link fields
  templates/publisher/listing.html
  templates/publisher/metadata/_donations.html
  templates/publisher/metadata/_issues.html
  templates/publisher/metadata/_source-code.html
Labels: Review: Code +1, Review: QA +1

#4028 Implement Star Developers
  static/js/public/hero-tabpanel.js
  static/sass/_snapcraft_p-verified.scss
  templates/brand-store/search.html
  templates/partials/_star_developer.html
  templates/partials/_verified_developer.html
  templates/store/_media-object-snap-partial.html
  templates/store/_snap-header-information.html
  templates/store/publisher-details.html
  templates/store/snap-embedded-card.html
  webapp/handlers.py
Labels: Review: Code +1, Review: UX +1, Review: Design +1, Review: QA +1

#4030 Implement notification for dropped architectures
  templates/publisher/builds.html
  tests/api/cassettes/GitHubTest.test_get_snapcraft_yaml_data.yaml
  tests/api/test_github.py
  webapp/api/github.py
  webapp/publisher/snaps/build_views.py
Labels: Review: Code +1, Review: UX +1, Review: QA +1

#4032 Add some extra information on the set up webook link in settings
  templates/publisher/settings.html
Labels: Review: Code +1, Review: QA +1

#4034 Setup listing React app
  static/js/publisher/listing/components/App/App.test.tsx
  static/js/publisher/listing/components/App/App.tsx
  static/js/publisher/listing/components/App/index.ts
  static/js/publisher/listing/index.tsx
  static/js/publisher/listing/types/index.d.ts
  templates/publisher/listing.html
  templates/publisher/metadata/_donations.html
  templates/publisher/metadata/_issues.html
  templates/publisher/metadata/_source-code.html
  webapp/publisher/snaps/listing_views.py
  webpack.config.entry.js
Labels: Review: Code +1, Review: QA +1

#4036 Disallow markdown links in preview
  static/js/publisher/preview.js
Labels: Review: Code +1, Review: QA +1

#4037 Add header to listing page
  package.json
  static/js/publisher/listing/components/App/App.test.tsx
  static/js/publisher/listing/components/App/App.tsx
  static/js/publisher/listing/components/NavTabs/NavTabs.test.tsx
  static/js/publisher/listing/components/NavTabs/NavTabs.tsx
  static/js/publisher/listing/components/NavTabs/index.ts
  static/js/publisher/listing/components/PageHeader/PageHeader.test.tsx
  static/js/publisher/listing/components/PageHeader/PageHeader.tsx
  static/js/publisher/listing/components/PageHeader/index.ts
  static/js/publisher/listing/components/SaveAndPreview/SaveAndPreview.test.tsx
  static/js/publisher/listing/components/SaveAndPreview/SaveAndPreview.tsx
  static/js/publisher/listing/components/SaveAndPreview/index.ts
  yarn.lock
Labels: Review: Code +1, Review: QA +1

#4038 Add some basic percy tests for less-QA'd parts of the site
  package.json
  snapshots.yml
Labels: Review: Code +1, Review: QA +1

#4040 Ensure developer isn't cached outside publisher pages
  static/js/base/base.js
  static/js/base/navigation.js
  templates/_header.html
  webapp/snapcraft/views.py
  yarn.lock
Labels: Review: Code +1, Review: UX +1, Review: QA +1

#4043 Fix typo
  templates/publisher/register-name-dispute.html
Labels: Review: Code +1

#4046 Published field inconsistency - yesterday vs date #3543
  webapp/store/logic.py
Labels: Review: Code +1, Review: QA +1

#4052 Fix undefined showing on homepage cards
  static/js/public/hero-tabpanel.js
Labels: Review: Code +1, Review: QA +1

#4053 Add listing page category fields
  static/js/publisher/listing/components/App/App.test.tsx
  static/js/publisher/listing/components/App/App.tsx
  static/js/publisher/listing/components/CategoriesInput/CategoriesInput.test.tsx
  static/js/publisher/listing/components/CategoriesInput/CategoriesInput.tsx
  static/js/publisher/listing/components/CategoriesInput/index.ts
  static/js/publisher/listing/components/ListingDescriptionField/ListingDescriptionField.tsx
  static/js/publisher/listing/components/ListingFormInput/ListingFormInput.tsx
Labels: Review: Code +1, Review: QA +1
