Repository canonical/snapcraft.io, pull requests merged in 2022-10, with the labels that each got.

#4137 Add collaborations tab
  static/js/publisher/collaboration/components/App/App.tsx
  static/js/publisher/collaboration/components/App/index.tsx
  static/js/publisher/collaboration/index.tsx
  static/js/publisher/collaboration/types/index.d.ts
  static/js/publisher/shared/PageHeader/PageHeader.tsx
  templates/publisher/collaboration.html
  webapp/publisher/snaps/collaboration_views.py
  webapp/publisher/snaps/views.py
  webpack.config.entry.js
Labels: Review: Code +1, Review: QA +1, Hacktoberfest, hacktoberfest-accepted

#4139 Build active shares table
  static/js/brand-store/Members/Members.js
  static/js/publisher/collaboration/components/App/App.tsx
  static/sass/styles.scss
  webapp/publisher/snaps/collaboration_views.py
Labels: Review: Code +1, Review: UX +1, Hacktoberfest, hacktoberfest-accepted

#4140 Built collaborator invites table
  static/js/publisher/collaboration/components/App/App.tsx
  webapp/publisher/snaps/collaboration_views.py
Labels: Review: Code +1, Review: QA +1, Hacktoberfest, hacktoberfest-accepted

#4148 Remove email address validation from the listing page
  static/js/publisher/listing/sections/ContactInformationSection/ContactInformationSection.tsx
Labels: Review: Code +1, Review: QA +1

#4149 Remove check as the API will handle it
  tests/publisher/snaps/tests_post_release.py
  webapp/publisher/snaps/release_views.py
Labels: Review: Code +1, Review: QA +1

#4153 Fix no store screen showing
  static/js/brand-store/slices/membersSlice.ts
  static/js/brand-store/slices/snapsSlice.ts
Labels: Review: Code +1, Review: QA +1
