Repository canonical/snapcraft.io, pull requests merged in 2022-01, with the labels that each got.

#3828 Fix video preview for snaps
  static/js/publisher/preview.js
Labels: Review: Code +1, Review: QA +1

#3830 Split services on snapcraft.io
  konf/site.yaml
Labels: Review: Code +1

#3832 Split publisher
  .github/workflows/pr.yml
  konf/site.yaml
Labels: Review: Code +1

#3836 Extra logging
  konf/site.yaml
  requirements.txt
  webapp/app.py
Labels: Review: Code +1, Review: QA +1

#3840 Convert release table to vanilla
  .stylelintrc
  static/js/publisher/release/components/releasesTable/droppableRow.js
  static/js/publisher/release/components/releasesTable/index.js
  static/sass/_snapcraft_release.scss
Labels: Review: Code +1, Review: UX +1, Review: QA +1

#3841 Remove tabs in release table
  static/js/publisher/release/components/releasesTable/availableRevisionsTabs.js
  static/js/publisher/release/components/releasesTable/index.js
  static/sass/_snapcraft_release.scss
Labels: Review: Code +1, Review: QA +1

#3844 Update copy for release UI track switcher
  static/js/publisher/release/components/releasesHeading.js
Labels: Review: Code +1, Review: QA +1

#3858 Update release date format in release UI history table
  static/js/publisher/release/components/revisionsList.js
  static/js/publisher/release/components/revisionsListRow.js
Labels: Review: Code +1, Review: QA +1

#3859 Clear new member roles when closing panel
  static/js/brand-store/Members/InviteModal.js
  static/js/brand-store/Members/InvitesTable.js
  static/js/brand-store/Members/Members.js
  static/sass/styles.scss
Labels: Review: Code +1, Review: QA +1

#3860 Close member sidepanel when clicking outside of it
  static/js/brand-store/Members/Members.js
  static/sass/_snapcraft_l-application.scss
Labels: Review: Code +1, Review: QA +1

#3862 Update macOS install instructions
  templates/first-snap/_install-macos.html
Labels: Review: Code +1, Review: QA +1

#3863 Fix brand store snaps side panel and notifications
  static/js/brand-store/Snaps/Snaps.js
Labels: Review: Code +1, Review: QA +1

#3865 Test with gevent.Timeout
  requirements.txt
  webapp/api/exceptions.py
  webapp/api/requests.py
  webapp/login/views.py
  webapp/publisher/views.py
  webapp/store/snap_details_views.py
  webapp/store/views.py
Labels: Review: Code +1, Review: QA +1

#3866 Remove gunicorn max-requests
  entrypoint
Labels: Review: Code +1

#3867 Use two gunicorn workers
  entrypoint
Labels: Review: Code +1

#3869 Upgrade flask-base and set session cookie to SameSite=None Secure
  requirements.txt
  webapp/config.py
Labels: Review: Code +1, Review: QA +1

#3864 Build release UI channel cell changes
  static/js/publisher/release/components/channelMenu.js
  static/js/publisher/release/components/contextualMenu.js
  static/js/publisher/release/components/releasesTable/channelHeading.js
  static/sass/_snapcraft_release.scss
Labels: Review: Code +1, Review: UX +1, Review: QA +1
