Repository canonical/snapcraft.io, pull requests merged in 2022-03, with the labels that each got.

#3892 Revision cell changes to Release UI
  static/js/publisher/release/components/contextualMenu.js
  static/js/publisher/release/components/historyIcon.js
  static/js/publisher/release/components/historyPanel.js
  static/js/publisher/release/components/releasesTable/cellViews.js
  static/js/publisher/release/components/releasesTable/channelHeading.js
  static/js/publisher/release/components/releasesTable/channelRow.js
  static/js/publisher/release/components/releasesTable/index.js
  static/js/publisher/release/components/releasesTable/releaseCell.js
  static/js/publisher/release/components/releasesTable/releaseMenuItem.js
  static/js/publisher/release/components/releasesTable/revisionCell.js
  static/js/publisher/release/components/revisionsList.js
  static/js/publisher/release/components/revisionsListRow.js
  static/sass/_snapcraft_release.scss
  templates/publisher/release-history.html
Labels: Review: Code +1, Review: UX +1, Review: QA +1

#3904 Fix promote button hover state in the release UI
  static/sass/_snapcraft_release.scss
Labels: Review: Code +1, Review: UX +1, Review: QA +1

#3914 Fix settings options indent
  templates/publisher/listing.html
Labels: Review: Code +1, Review: QA +1

#3915 Fix release cell padding
  static/sass/_snapcraft_release.scss
Labels: Review: Code +1, Review: QA +1

#3900 Superadmin
  static/js/brand-store/Members/Members.js
  static/js/brand-store/NotAuthorized/NotAuthorized.test.tsx
  static/js/brand-store/NotAuthorized/NotAuthorized.tsx
  static/js/brand-store/NotAuthorized/index.ts
  static/js/brand-store/Settings/Settings.tsx
  static/js/brand-store/Snaps/Snaps.js
  static/js/brand-store/Snaps/SnapsTable.js
  static/js/brand-store/Snaps/SnapsTableRow.js
Labels: Review: Code +1

#3928 Replace some bad gateway to 404s
  requirements.txt
  tests/store/tests_details.py
  webapp/publisher/views.py
  webapp/store/snap_details_views.py
  webapp/store/views.py
Labels: Review: Code +1, Review: QA +1

#3931 Fix next/prev page buttons
  templates/blog/index.html
  templates/store/search.html
  templates/store/snap-details.html
  templates/tutorials/tutorial.html
Labels: Review: Code +1, Review: QA +1

#3935 Fix docker image
  requirements.txt
Labels: Review: Code +1, Review: QA +1

#3930 Fix first user flow package snap
  static/js/public/accordion.js
  static/js/public/accordion.test.js
  static/js/public/first-snap-flow.js
  static/sass/_patterns_first-snap-flow.scss
  templates/first-snap/build-and-test.html
  templates/first-snap/package.html
  templates/first-snap/upload.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#3934 [Sentry] Ignore AbortError messages
  templates/_base-layout.html
Labels: Review: Code +1
