Repository canonical/snapcraft.io, pull requests merged in 2022-09, with the labels that each got.

#4088 Convert snap settings page to React
  static/js/publisher/listing/components/App/App.tsx
  static/js/publisher/settings/components/App/App.tsx
  static/js/publisher/settings/components/App/index.ts
  static/js/publisher/settings/index.tsx
  static/js/publisher/settings/types/SettingsData.d.ts
  static/js/publisher/settings/types/index.d.ts
  static/js/publisher/settings/utils/getChanges.ts
  static/js/publisher/settings/utils/getFormData.ts
  static/js/publisher/settings/utils/getSettingsData.ts
  static/js/publisher/settings/utils/index.ts
  static/js/publisher/shared/PageHeader/PageHeader.test.tsx
  static/js/publisher/shared/PageHeader/PageHeader.tsx
  static/js/publisher/shared/PageHeader/index.ts
  static/js/publisher/shared/SaveAndPreview/SaveAndPreview.test.tsx
  static/js/publisher/shared/SaveAndPreview/SaveAndPreview.tsx
  static/js/publisher/shared/SaveAndPreview/index.ts
  static/js/publisher/shared/SearchAutocomplete/SearchAutocomplete.tsx
  static/js/publisher/shared/SearchAutocomplete/index.ts
  templates/publisher/settings.html
  webpack.config.entry.js
Labels: Review: Code +1, Review: QA +1

#4089 Removed legacy settings page
  static/js/publisher/publisher.js
  static/js/publisher/settings.js
  templates/publisher/settings.html
Labels: Review: Code +1, Review: QA +1

#4090 Remove legacy listing page
  static/js/publisher/form/multiselect.js
  static/js/publisher/publisher.js
  templates/publisher/listing.html
  templates/publisher/metadata/_category.html
  templates/publisher/metadata/_contact.html
  templates/publisher/metadata/_description.html
  templates/publisher/metadata/_featured-banner.html
  templates/publisher/metadata/_license.html
  templates/publisher/metadata/_metrics.html
  templates/publisher/metadata/_screenshots.html
  templates/publisher/metadata/_snap-icon.html
  templates/publisher/metadata/_summary.html
  templates/publisher/metadata/_title.html
  templates/publisher/metadata/_video.html
  templates/publisher/metadata/_website.html
Labels: Review: Code +1, Review: QA +1

#4091 Fix JS error
  static/js/publisher/listing/components/Screenshots/ScreenshotList.tsx
Labels: Review: Code +1, Review: QA +1

#4096 Update percy SDK version
  package.json
Labels: Review: Code +1

#4097 Fix image upload aspect ratio bug
  static/js/publisher/listing/components/ImageUpload/ImageUpload.tsx
Labels: Review: Code +1, Review: QA +1

#4099 Update mistune
  requirements.txt
  tests/tests_markdown_parser.py
  webapp/markdown.py
Labels: Review: Code +1, Review: QA +1

#4100 Update brand store checkboxes
  static/js/brand-store/Snaps/SnapsTable.js
  static/js/brand-store/Snaps/SnapsTableRow.js
Labels: Review: Code +1, Review: QA +1

#4102 Add a caption to the snaps table
  static/js/brand-store/Snaps/SnapsTable.js
  static/sass/styles.scss
  yarn.lock
Labels: Review: Code +1

#4103 Brand store table checkboxes
  static/js/brand-store/Snaps/SnapsTable.js
  static/js/brand-store/Snaps/SnapsTableRow.js
  static/sass/_snapcraft_l-application.scss
Labels: Review: Code +1, Review: QA +1

#4107 Fix homepage card tooltips
  static/sass/_patterns_media-object--snap.scss
Labels: Review: Code +1, Review: QA +1

#4109 Fix metadata warning when changing images
  static/js/publisher/listing/components/App/App.tsx
  static/js/publisher/listing/utils/index.ts
  static/js/publisher/listing/utils/shouldShowUpdateMetadataWarning.ts
Labels: Review: Code +1, Review: QA +1

#4110 Fix empty metrics view
  static/js/publisher/metrics/graphs/activeDevicesGraph/dataProcessing.js
  static/js/publisher/metrics/graphs/activeDevicesGraph/tooltips.js
Labels: Review: Code +1, Review: QA +1

#4126 Fix brand store blank page
  static/js/brand-store/Snaps/SnapsTable.js
Labels: Review: Code +1, Review: QA +1

#4129 Show a no store page is user isn't in store
  static/js/brand-store/App/App.js
  static/js/brand-store/Members/Members.js
  static/js/brand-store/NoStores/NoStores.test.tsx
  static/js/brand-store/NoStores/NoStores.tsx
  static/js/brand-store/NoStores/index.ts
  static/js/brand-store/Settings/Settings.test.tsx
  static/js/brand-store/Settings/Settings.tsx
  static/js/brand-store/Snaps/Snaps.js
  static/js/brand-store/StoreNotFound/StoreNotFound.tsx
  static/js/brand-store/StoreNotFound/index.ts
  static/js/brand-store/slices/brandStoreSlice.ts
  static/js/brand-store/slices/currentStoreSlice.ts
  static/js/brand-store/slices/invitesSlice.ts
  static/js/brand-store/slices/membersSlice.ts
  static/js/brand-store/slices/snapsSlice.ts
Labels: Review: UX needed, Review: Code +1, Review: QA +1

#4133 Remove flash messages from published snaps page
  templates/publisher/account-snaps.html
Labels: Review: Code +1, Review: QA +1

#4134 Fix flash message consumption
  webapp/publisher/snaps/listing_views.py
  webapp/publisher/snaps/settings_views.py
Labels: Review: Code +1, Review: QA +1
