Repository canonical/snapcraft.io, pull requests merged in 2023-03, with the labels that each got.

#4209 Update site navigation
  package.json
  static/js/base/dropdown-menu-toggle.js
  static/js/base/global-nav.js
  static/sass/styles.scss
  templates/_base-layout.html
  templates/_header.html
  yarn.lock
Labels: Review: Code +1, Review: UX +1, Review: Design +1, Review: QA +1

#4210 Fix bug in include snap form
  static/sass/_snapcraft_l-application.scss
Labels: Review: Code +1, Review: QA +1

#4211 Update favicon
  templates/_base-layout.html
  templates/_layout-brandstore.html
  templates/_layout-embedded.html
  webapp/app.py
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#4213 Update empty header
  templates/_header_empty.html
Labels: Review: Code +1, Review: QA +1

#4190 append embedded-stores to snaps list
  webapp/admin/views.py
Labels: Review: Code +1, Review: QA +1, Don't merge

#4214 append embedded-store to snaps list
  static/js/brand-store/Snaps/Snaps.js
  webapp/admin/views.py
Labels: Review: Code +1, Review: QA +1

#4217 Update dependencies
  .eslintrc.js
  .stylelintrc
  babel.config.json
  jest.config.js
  package.json
  requirements.txt
  static/js/brand-store/App/App.js
  static/js/brand-store/Members/Members.js
  static/js/brand-store/Navigation/Navigation.js
  static/js/brand-store/Settings/Settings.test.tsx
  static/js/brand-store/Settings/Settings.tsx
  static/js/brand-store/brand-store.js
  static/js/libs/colours.js
  static/js/publisher/builds/components/repoConnect.js
  static/js/publisher/builds/index.js
  static/js/publisher/collaboration/index.tsx
  static/js/publisher/listing/index.tsx
  static/js/publisher/market/initBanner.js
  static/js/publisher/market/initBanner.test.js
  static/js/publisher/market/initIcon.js
  static/js/publisher/market/initIcon.test.js
  static/js/publisher/release.js
  static/js/publisher/release/components/dnd.js
  static/js/publisher/settings/index.tsx
  static/js/publisher/tour.js
  yarn.lock
Labels: Review: Code +1, Review: QA +1

#4220 Fix metadata being disabled
  static/js/publisher/listing/utils/getFormData.ts
  static/js/publisher/listing/utils/shouldShowUpdateMetadataWarning.ts
  tests/publisher/snaps/tests_post_listing.py
  webapp/publisher/snaps/listing_views.py
Labels: Review: Code +1, Review: QA +1

#4221 Fix metadata updates
  static/js/publisher/listing/utils/shouldShowUpdateMetadataWarning.ts
Labels: Review: Code +1, Review: QA +1

#4227 append embedded-store to snaps list
  static/js/brand-store/Snaps/Snaps.js
  webapp/admin/views.py
Labels: Review: Code +1, Review: QA +1

#4229 Improve fetching of brand-stores on login
  webapp/login/views.py
Labels: Review: Code +1, Review: QA +1

#4233 Add update metadata warning on snap settings page
  static/js/publisher/listing/components/App/App.tsx
  static/js/publisher/settings/components/App/App.tsx
  static/js/publisher/shared/UpdateMetadataModal/UpdateMetadataModal.tsx
  static/js/publisher/shared/UpdateMetadataModal/index.ts
Labels: Review: Code needed, Review: QA needed

#4235 Fix issue with brand-store homepage
  webapp/store/views.py
Labels: Review: Code +1, Review: QA +1

#4234 fixed a wrong number of snaps published results for publishers (snapcrafters, jetbrains, and kde)
  webapp/store/views.py
Labels: Review: Code +1, Review: QA +1
