Repository canonical/snapcraft.io, pull requests merged in 2023-07, with the labels that each got.

#4316 Add models table
  package.json
  static/js/brand-store/components/App/App.tsx
  static/js/brand-store/components/Models/Models.test.tsx
  static/js/brand-store/components/Models/Models.tsx
  static/js/brand-store/components/Models/models-data.js
  static/js/brand-store/types/shared.ts
  static/js/brand-store/utils/getFilteredModels.test.ts
  static/js/brand-store/utils/getFilteredModels.ts
  static/js/brand-store/utils/index.ts
  static/js/brand-store/utils/maskString.test.ts
  static/js/brand-store/utils/maskString.ts
  yarn.lock
Labels: Review: Code +1, Review: QA +1

#4319 Fix for superset brand stores not loading
  static/js/brand-store/components/Snaps/Snaps.tsx
Labels: Review: Code +1

#4321 Add create new model view
  package.json
  static/js/brand-store/atoms/index.ts
  static/js/brand-store/components/App/App.tsx
  static/js/brand-store/components/Models/Models.test.tsx
  static/js/brand-store/components/Models/Models.tsx
  static/js/brand-store/utils/checkModelNameExists.test.ts
  static/js/brand-store/utils/checkModelNameExists.ts
  static/js/brand-store/utils/index.ts
  static/js/brand-store/utils/isClosedPanel.test.ts
  static/js/brand-store/utils/isClosedPanel.ts
  static/sass/_snapcraft_l-application.scss
  yarn.lock
Labels: Review: Code +1, Review: QA +1

#4322 Add policies view
  static/js/brand-store/components/App/App.tsx
  static/js/brand-store/components/Model/Policies.test.tsx
  static/js/brand-store/components/Model/Policies.tsx
  static/js/brand-store/components/Model/policies-data.js
  static/js/brand-store/components/Models/Models.test.tsx
  static/js/brand-store/components/Models/Models.tsx
  static/js/brand-store/types/shared.ts
  static/js/brand-store/utils/getFilteredPolicies.test.ts
  static/js/brand-store/utils/getFilteredPolicies.ts
  static/js/brand-store/utils/index.ts
Labels: Review: Code +1, Review: QA +1

#4323 Add link to survey
  templates/index.html
Labels: Review: Code +1, Review: UX +1, Review: QA +1

#4320 add developer_token to session for /login-beta
  webapp/login/views.py
Labels: Review: Code +1, Review: QA +1

#4334 Remove references to "Price"
  requirements.txt
  tests/publisher/snaps/tests_post_settings.py
  tests/publisher/snaps/tests_publicise_badges.py
  tests/publisher/snaps/tests_settings.py
  tests/store/tests_details.py
  tests/store/tests_distro_page.py
  tests/store/tests_embedded_card.py
  tests/store/tests_github_badge.py
  webapp/publisher/snaps/logic.py
  webapp/publisher/snaps/settings_views.py
  webapp/store/snap_details_views.py
Labels: Review: Code +1, Review: QA +1

#4332 Add model
  webapp/admin/views.py
Labels: Review: Code +1, Review: QA +1

#4333 Add policy endpoints
  webapp/admin/views.py
Labels: Review: Code +1, Review: QA +1

#4330 Make header full width in brand store
  static/sass/_snapcraft_l-application.scss
  static/sass/styles.scss
  templates/_header.html
  templates/admin/admin.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#4338 Add signing key endpoints
  webapp/admin/views.py
Labels: Review: Code +1, Review: QA +1

#4340 Fetch, display and create models
  static/js/brand-store/atoms/index.ts
  static/js/brand-store/components/Models/CreateModelForm.tsx
  static/js/brand-store/components/Models/Models.test.tsx
  static/js/brand-store/components/Models/Models.tsx
  static/js/brand-store/components/Models/ModelsFilter.tsx
  static/js/brand-store/components/Models/ModelsTable.tsx
  static/js/brand-store/components/Models/models-data.js
  static/js/brand-store/selectors/index.ts
  static/js/brand-store/types/shared.ts
  static/js/brand-store/utils/getFilteredModels.ts
  static/js/brand-store/utils/maskString.ts
Labels: Review: Code +1, Review: QA +1

#4343 Fix create model form validation error
  static/js/brand-store/components/Models/CreateModelForm.tsx
  static/js/brand-store/components/Models/Models.tsx
Labels: Review: Code +1, Review: QA +1

#4344 Build model view
  static/js/brand-store/components/Model/Model.tsx
  static/js/brand-store/components/Models/Models.tsx
  static/js/brand-store/selectors/index.ts
  static/js/brand-store/types/shared.ts
  static/js/brand-store/utils/checkModelNameExists.test.ts
  static/js/brand-store/utils/getFilteredModels.test.ts
Labels: Review: Code +1, Review: QA +1

#4342 Update store api version
  requirements.txt
Labels: Review: Code +1, Review: QA +1

#4346 Add model policies view
  static/js/brand-store/atoms/index.ts
  static/js/brand-store/components/Model/CreatePolicyForm.tsx
  static/js/brand-store/components/Model/Policies.test.tsx
  static/js/brand-store/components/Model/Policies.tsx
  static/js/brand-store/components/Model/PoliciesFilter.tsx
  static/js/brand-store/components/Model/PoliciesTable.tsx
  static/js/brand-store/components/Model/policies-data.js
  static/js/brand-store/components/Models/CreateModelForm.tsx
  static/js/brand-store/components/Models/Models.tsx
  static/js/brand-store/selectors/index.ts
  static/js/brand-store/types/shared.ts
  static/js/brand-store/utils/getFilteredPolicies.ts
Labels: Review: Code +1, Review: QA +1

#4347 Fix bug with missing policiy revision
  static/js/brand-store/components/Models/Models.tsx
  static/js/brand-store/components/Models/ModelsTable.tsx
Labels: Review: Code +1, Review: QA +1

#4349 Model service tests
  static/js/brand-store/components/Model/PoliciesFilter.test.tsx
  static/js/brand-store/components/Model/PoliciesFilter.tsx
  static/js/brand-store/components/Model/PoliciesTable.tsx
  static/js/brand-store/components/Models/ModelsFilter.test.tsx
  static/js/brand-store/components/Models/ModelsFilter.tsx
Labels: Review: Code +1, Review: QA +1

#4350 Add tests for model service navigation
  static/js/brand-store/components/Model/ModelNav.test.tsx
Labels: Review: Code +1, Review: QA +1

#4351 Add tests for model service tables
  static/js/brand-store/components/Model/PoliciesTable.test.tsx
  static/js/brand-store/components/Models/ModelsTable.test.tsx
Labels: Review: Code +1, Review: QA +1

#4352 Model service hooks
  static/js/brand-store/components/Model/CreatePolicyForm.tsx
  static/js/brand-store/components/Model/Model.tsx
  static/js/brand-store/components/Model/Policies.tsx
  static/js/brand-store/components/Models/Models.tsx
  static/js/brand-store/components/Models/ModelsTable.test.tsx
  static/js/brand-store/hooks/index.ts
  static/js/brand-store/types/shared.ts
Labels: Review: Code +1, Review: QA +1

#4354 Add tests for model service create forms
  static/js/brand-store/components/Model/CreatePolicyForm.test.tsx
  static/js/brand-store/components/Model/Model.test.tsx
  static/js/brand-store/components/Models/CreateModelForm.test.tsx
  static/js/brand-store/components/Models/Models.test.tsx
Labels: Review: Code +1, Review: QA +1

#4355 Redirect to login beta
  webapp/admin/views.py
  webapp/decorators.py
  webapp/login/views.py
Labels: Review: Code +1, Review: QA +1

#4356 Set page titles in brand store
  static/js/brand-store/components/Members/Members.tsx
  static/js/brand-store/components/Model/CreatePolicyForm.tsx
  static/js/brand-store/components/Model/Model.tsx
  static/js/brand-store/components/Model/Policies.test.tsx
  static/js/brand-store/components/Model/Policies.tsx
  static/js/brand-store/components/Models/CreateModelForm.tsx
  static/js/brand-store/components/Models/Models.test.tsx
  static/js/brand-store/components/Models/Models.tsx
  static/js/brand-store/components/Settings/Settings.test.tsx
  static/js/brand-store/components/Settings/Settings.tsx
  static/js/brand-store/components/Snaps/Snaps.tsx
  static/js/brand-store/components/StoreNotFound/StoreNotFound.tsx
  static/js/brand-store/selectors/index.ts
  static/js/brand-store/types/shared.ts
  static/js/brand-store/utils/index.ts
  static/js/brand-store/utils/setPageTitle.ts
Labels: Review: Code needed, Review: QA needed

#4359 Fix name overflow on models table
  static/js/brand-store/components/Model/Policies.tsx
  static/js/brand-store/components/Models/Models.tsx
  static/js/brand-store/components/Models/ModelsTable.tsx
Labels: Review: Code +1, Review: QA +1
