Repository canonical/snapcraft.io, pull requests merged in 2023-04, with the labels that each got.

#4238 Allow access to TOC page
  tests/publisher/tests_agreement.py
  webapp/authentication.py
  webapp/publisher/views.py
Labels: Review: Code +1, Review: QA +1

#4252 Actions: Force node 16 on test-js job
  .github/workflows/pr.yml
Labels: Review: Code +1

#4250 Update design on about publicise page
  templates/about/publicise.html
Labels: Review: Code +1, Review: QA +1

#4254 Wd 2960 build about your snap page
  static/js/public/about/listing.ts
  templates/about/listing.html
  webpack.config.entry.js
Labels: Review: Code +1, Review: QA needed

#4248 built a Release your snap page for Snapcraft rebranding
  templates/about/release.html
Labels: Review: Code +1, Review: QA +1
