Repository canonical/snapcraft.io, pull requests merged in 2023-02, with the labels that each got.

#4194 Remove specific emoji from display names
  requirements.txt
  templates/publisher/account-details.html
  templates/store/_media-object-snap-partial.html
  templates/store/community-publisher-details.html
  templates/store/snap-details/_details.html
  tests/publisher/endpoint_testing.py
  tests/publisher/tests_publisher.py
  tests/publisher/tests_publisher_logic.py
  tests/snapcraft/tests_public.py
  tests/store/tests_public_logic.py
  tests/tests_templates_utils.py
  webapp/admin/views.py
  webapp/handlers.py
  webapp/metrics/metrics.py
  webapp/publisher/snaps/logic.py
  webapp/publisher/views.py
  webapp/store/logic.py
  webapp/store/snap_details_views.py
  webapp/template_utils.py
Labels: Review: Code +1, Review: QA +1

#4195 Add flake8 and black as dependencies
  requirements.txt
Labels: Review: Code +1

#4196 Bump the module to fix some docs issues
  requirements.txt
Labels: Review: Code +1

#4200 Fix broken link in README
  README.md
Labels: Review: Code +1

#4202 Enable dark mode preview for icon upload
  static/js/publisher/listing/components/ImageUpload/ImageUpload.tsx
  static/js/publisher/listing/sections/ListingDetailsSection/ListingDetailsSection.tsx
  static/sass/_snapcraft_snap-image-upload.scss
  static/sass/styles.scss
Labels: Review: Code +1, Review: UX +1, Review: Design +1, Review: QA +1

#4204 Add a confirmation modal when excluding snaps
  static/js/brand-store/Snaps/Snaps.js
Labels: Review: Code +1, Review: UX +1, Review: QA +1

#4205 Redirect all tutorials from /tutorials -> /docs/snap-tutorials
  redirects.yaml
  templates/_header.html
  templates/about/publish.html
  webapp/template_utils.py
Labels: Review: Code +1, Review: QA +1
