Repository canonical/snapcraft.io, pull requests merged in 2023-09, with the labels that each got.

#4396 Fix model form submission
  static/js/brand-store/components/Models/CreateModelForm.tsx
  static/js/brand-store/components/Models/Models.tsx
Labels: Review: Code +1, Review: QA +1

#4395 Fix signing key form submission
  static/js/brand-store/components/SigningKeys/CreateSigningKeyForm.tsx
  static/js/brand-store/components/SigningKeys/SigningKeys.tsx
Labels: Review: Code +1, Review: QA +1

#4394 Make new policy form submit with enter key
  static/js/brand-store/components/Model/Policies.tsx
Labels: Review: Code needed, Review: QA needed

#4399 Convert model service cancel buttons to links and clear forms on close
  static/js/brand-store/components/Model/CreatePolicyForm.tsx
  static/js/brand-store/components/Model/Policies.tsx
  static/js/brand-store/components/Models/CreateModelForm.tsx
  static/js/brand-store/components/Models/Models.tsx
  static/js/brand-store/components/SigningKeys/CreateSigningKeyForm.tsx
  static/js/brand-store/components/SigningKeys/SigningKeys.tsx
Labels: Review: Code +1, Review: QA +1

#4400 Add new pagination to model service pages
  static/js/brand-store/components/AppPagination/AppPagination.tsx
  static/js/brand-store/components/AppPagination/index.ts
  static/js/brand-store/components/Model/Policies.tsx
  static/js/brand-store/components/Model/PoliciesTable.tsx
  static/js/brand-store/components/Models/Models.tsx
  static/js/brand-store/components/Models/ModelsTable.tsx
  static/js/brand-store/components/SigningKeys/SigningKeys.tsx
  static/js/brand-store/components/SigningKeys/SigningKeysTable.tsx
  static/sass/_snapcraft_l-application.scss
  static/sass/_snapcraft_p-app-pagination.scss
  static/sass/styles.scss
Labels: Review: Code +1, Review: QA +1

#4401 Test model services
  tests/admin/test_brand_store.py
  tests/admin/tests_models.py
  tests/admin/tests_policies.py
  tests/admin/tests_signing_keys.py
  webapp/admin/views.py
Labels: Review: Code +1

#4402 Disable model key revert button if no change
  static/js/brand-store/components/Model/Model.test.tsx
  static/js/brand-store/components/Model/Model.tsx
Labels: Review: Code +1, Review: QA +1

#4403 Add saving state in model service
  static/js/brand-store/components/Model/CreatePolicyForm.tsx
  static/js/brand-store/components/Models/CreateModelForm.tsx
  static/js/brand-store/components/SigningKeys/CreateSigningKeyForm.tsx
Labels: Review: Code +1, Review: QA +1

#4404 Fix page titles in models service
  static/js/brand-store/components/Model/CreatePolicyForm.tsx
  static/js/brand-store/components/Models/CreateModelForm.tsx
  static/js/brand-store/components/SigningKeys/CreateSigningKeyForm.tsx
Labels: Review: Code +1, Review: QA +1

#4408 Refactor create model to use optimistic updates correctly
  static/js/brand-store/components/Models/CreateModelForm.tsx
  static/js/brand-store/components/Models/ModelsTable.tsx
  static/js/brand-store/hooks/index.ts
  static/js/brand-store/types/shared.ts
Labels: Review: Code +1, Review: QA +1

#4409 Refactor create policy to use optimistic updates correctly
  static/js/brand-store/components/Model/CreatePolicyForm.tsx
  static/js/brand-store/components/Model/PoliciesTable.tsx
Labels: Review: Code +1, Review: Design +1

#4412 Fix duplicated content in build table
  static/js/publisher/builds/components/buildsTable.js
Labels: Review: Code +1, Review: QA +1

#4410 Refactor create signing key to use optimistic updates correctly
  static/js/brand-store/components/SigningKeys/CreateSigningKeyForm.tsx
  static/js/brand-store/components/SigningKeys/SigningKeysTable.tsx
Labels: Review: Code +1, Review: QA +1

#4414 Enable metadata links
  static/js/publisher/listing/sections/ContactInformationSection/ContactInformationSection.tsx
  static/js/publisher/listing/utils/getChanges.ts
  static/js/publisher/listing/utils/getListingData.ts
  templates/store/snap-details/_details.html
  tests/publisher/snaps/tests_listing.py
  tests/publisher/snaps/tests_post_listing.py
  tests/publisher/snaps/tests_post_settings.py
  webapp/publisher/snaps/listing_views.py
  webapp/publisher/snaps/logic.py
Labels: Review: Code +1, Review: QA +1

#4413 create /beta
  entrypoint
  requirements.txt
  webapp/decorators.py
  webapp/handlers.py
  webapp_beta/app.py
  webapp_beta/beta_app.py
  webapp_beta/snapcraft_bp.py
Labels: Review: Code +1, Review: QA +1
