Repository canonical/snapcraft.io, pull requests merged in 2023-10, with the labels that each got.

#4416 Add CSRF protection to the free youtube proxy we have created
  templates/partials/_video.html
  webapp/store/views.py
Labels: Review: Code +1, Review: QA +1

#4420 Save selected territories
  static/js/publisher/listing/utils/shouldShowUpdateMetadataWarning.ts
  static/js/publisher/settings/components/App/App.tsx
  static/js/publisher/settings/utils/getFormData.ts
Labels: Review: Code +1, Review: QA needed

#4421 Revert "Save selected territories (#4420)"
  static/js/publisher/listing/utils/shouldShowUpdateMetadataWarning.ts
  static/js/publisher/settings/components/App/App.tsx
  static/js/publisher/settings/utils/getFormData.ts
Labels: Review: Code +1

#4422 Only show metadata warning modal for visibility changes
  static/js/publisher/settings/components/App/App.tsx
Labels: Review: Code +1, Review: QA +1

#4423 Fix invite modal display
  static/sass/styles.scss
Labels: Review: Code +1, Review: QA +1

#4431 Bump canonicalwebteam.discourse to 5.4.3
  requirements.txt
Labels: Review: Code +1, Review: QA +1

#4435 Use build-base if available, fallback to base
  webapp/publisher/snaps/build_views.py
Labels: Review: Code +1, Review: QA +1

#4436 Add both highest stable version and most recent updated
  templates/store/snap-details/_details.html
  tests/store/tests_public_logic.py
  tests/tests_templates_utils.py
  webapp/store/logic.py
  webapp/store/snap_details_views.py
Labels: Review: Code +1, Review: QA +1

#4437 Bump discourse to 5.4.4
  requirements.txt
Labels: Review: Code +1, Review: QA +1
