Repository canonical/snapcraft.io, pull requests merged in 2024-08, with the labels that each got.

#4789 fix: Cancel pending policy requests when leaving model view
  static/js/brand-store/components/Models/Models.tsx
  static/js/brand-store/components/SigningKeys/SigningKeys.tsx
  static/js/brand-store/utils/getPolicies.ts
Labels: Review: Code +1, Review: QA +1

#4792 fix: Remove production check in entryfile
  entrypoint
Labels: Review: Code +1

#4797 chore: fix failing tests
  static/js/brand-store/components/Model/CreatePolicyForm.test.tsx
  static/js/brand-store/components/Model/Model.test.tsx
  static/js/brand-store/components/Models/CreateModelForm.test.tsx
  static/js/brand-store/components/Settings/Settings.test.tsx
  static/js/publisher/form/banner.test.js
  static/js/publisher/form/media.test.js
  static/js/publisher/listing/components/App/__tests__/App.test.tsx
  static/js/publisher/settings/components/App/__tests__/UnregisterSnapModal.test.tsx
  static/js/publisher/shared/SaveAndPreview/SaveAndPreview.test.tsx
Labels: Review: Code +1

#4796 fix: add optional parameters functionality when adding a new track
  requirements.txt
  static/js/publisher/release/components/TrackInfo.test.tsx
  static/js/publisher/release/components/TrackInfo.tsx
  static/js/publisher/release/components/releasesHeading.js
  static/js/publisher/release/helpers.test.js
  static/js/publisher/release/helpers.ts
  webapp/store/views.py
Labels: Review: Code +1, Review: QA +1

#4799 chore: remove unnecessary useEffect hook
  static/js/publisher/release/components/releasesHeading.js
Labels: Review: Code +1

#4802 feat: Create validation sets endpoints
  requirements.txt
  tests/store/tests_validation_sets.py
  webapp/store/views.py
Labels: Review: Code +1, Review: QA +1

#4803 feat: Create validation sets app shell
  package.json
  static/js/validation-sets/index.tsx
  static/js/validation-sets/pages/ValidationSet/ValidationSet.tsx
  static/js/validation-sets/pages/ValidationSet/index.ts
  static/js/validation-sets/pages/ValidationSets/ValidationSets.tsx
  static/js/validation-sets/pages/ValidationSets/index.ts
  static/js/validation-sets/routes/root.tsx
  templates/store/validation-sets.html
  webapp/store/views.py
  webpack.config.entry.js
  yarn.lock
Labels: Review: Code +1, Review: QA +1

#4804 feat: Add validation sets table
  static/js/validation-sets/hooks/__tests__/useValidationSets.test.ts
  static/js/validation-sets/hooks/index.ts
  static/js/validation-sets/hooks/useValidationSets.ts
  static/js/validation-sets/index.tsx
  static/js/validation-sets/pages/ValidationSets/ValidationSets.tsx
  static/js/validation-sets/pages/ValidationSets/__tests__/ValidationSets.test.tsx
Labels: Review: Code +1, Review: QA +1

#4806 feat: Create validation set table
  requirements.txt
  static/js/validation-sets/hooks/__tests__/useValidationSet.test.ts
  static/js/validation-sets/hooks/index.ts
  static/js/validation-sets/hooks/useValidationSet.ts
  static/js/validation-sets/pages/ValidationSet/ValidationSet.tsx
  static/js/validation-sets/pages/ValidationSet/__tests__/ValidationSet.test.tsx
  static/js/validation-sets/pages/ValidationSet/index.ts
  static/js/validation-sets/pages/ValidationSets/ValidationSets.tsx
  static/js/validation-sets/types/index.d.ts
  webapp/store/views.py
Labels: Review: Code +1

#4811 chore: Update security email address
  security.txt
Labels: Review: Code +1

#4812 fix: /docs/getting-started update
  redirects.yaml
  templates/publisher/account-snaps.html
Labels: Review: Code +1, Review: QA +1

#4813 fix: Fix application layout sidebar for validation sets
  static/js/validation-sets/routes/root.tsx
Labels: Review: Code needed, Review: QA needed

#4814 fix: Fix stale data error in validation sets
  static/js/validation-sets/pages/ValidationSet/ValidationSet.tsx
Labels: Review: Code +1, Review: QA +1

#4816 fix: Updated security expires date
  security.txt
Labels: Review: Code needed

#4817 fix: Use ApplicationLayout component for validation sets
  static/js/validation-sets/components/Logo/Logo.tsx
  static/js/validation-sets/components/Logo/index.ts
  static/js/validation-sets/components/PrimaryNav/PrimaryNav.tsx
  static/js/validation-sets/components/PrimaryNav/index.ts
  static/js/validation-sets/routes/root.tsx
Labels: Review: Code needed, Review: QA needed

#4819 chore: Enable support for RISC-V builds
  static/js/store/utils/getArchitectures.ts
Labels: Review: Code needed, Review: QA needed

#4820 fix: Fix broken store search
  webapp_beta/beta_app.py
Labels: Review: Code +1, Review: QA +1

#4815 feat: build /iot page
  static/sass/_patterns_media-object--snap.scss
  templates/store/_media-object-snap-partial.html
  templates/store/categories/iot.html
  webapp/snapcraft/views.py
Labels: Review: Code +1, Review: UX +1, Review: QA +1
