Repository canonical/snapcraft.io, pull requests merged in 2024-06, with the labels that each got.

#4671 fix: Fix compiler errors for metrics JS
  static/js/publisher/metrics/graphs/activeDevicesGraph/index.js
  static/js/publisher/metrics/metrics.ts
Labels: Review: Code +1

#4672 fix: Fix compiler warnings in publisher axis js
  static/js/publisher/metrics/axis.js
  static/js/publisher/metrics/axis.ts
Labels: Review: Code +1

#4673 fix: Fix compiler warnings in publisher installs js
  static/js/publisher/metrics/graphs/installs.ts
Labels: Review: Code +1

#4670 feat: add unregister snap name logic
  static/js/publisher/settings/components/App/App.tsx
  static/js/publisher/settings/components/App/__tests__/UnregisterSnapModal.test.tsx
  static/js/publisher/settings/components/UnregisterSnapModal.tsx
  templates/publisher/account-snaps.html
  tests/publisher/tests_account_snaps.py
  webapp/publisher/snaps/views.py
Labels: Review: UX needed, Review: Code +1, Review: QA +1

#4675 fix: Fix compiler warnings in active device graph data processing JS
  static/js/publisher/metrics/graphs/activeDevicesGraph/dataProcessing.ts
Labels: Review: Code +1

#4676 fix: Fix compiler warnings in active device graphs tooltips js
  static/js/libs/channels.js
  static/js/publisher/metrics/graphs/activeDevicesGraph/tooltips.ts
Labels: Review: Code +1

#4677 fix: Fix compiler warnings in metrics graphs JS
  static/js/publisher/metrics/graphs/activeDevicesGraph/dataProcessing.ts
  static/js/publisher/metrics/graphs/activeDevicesGraph/tooltips.ts
  static/js/publisher/metrics/metrics.ts
Labels: Review: Code +1

#4678 fix: Fix compiler warnings in release helpers
  static/js/publisher/release/helpers.ts
Labels: Review: Code +1

#4679 fix: Fix compiler warnings in actions releases JS
  static/js/publisher/release/actions/releases.ts
Labels: Review: Code +1

#4680 fix: Fix compiler warnings in releases components
  static/js/publisher/release/components/ProgressiveReleaseProgressChart.tsx
  static/js/publisher/release/components/dnd.tsx
  static/js/publisher/release/components/releasesConfirm.tsx
Labels: Review: Code +1

#4681 fix: Fix compiler warnings in releases table JS
  static/js/publisher/release/components/releasesTable/channelHeading.tsx
  static/js/publisher/release/components/releasesTable/droppableRow.tsx
  static/js/publisher/release/components/releasesTable/row.tsx
  static/js/publisher/release/helpers.ts
Labels: Review: Code needed

#4682 fix: Fix compiler warnings in release reducers JS
  static/js/publisher/release/components/releasesConfirm.tsx
  static/js/publisher/release/components/releasesTable/channelHeading.tsx
  static/js/publisher/release/components/releasesTable/droppableRow.tsx
  static/js/publisher/release/reducers/pendingReleases.ts
  static/js/publisher/release/selectors/index.js
  static/js/publisher/release/selectors/index.ts
Labels: Review: Code +1

#4683 fix: Fix compiler warnings in publisher settings JS
  static/js/publisher/settings/components/UnregisterSnapModal.tsx
  static/js/publisher/settings/index.tsx
Labels: Review: Code +1

#4685 fix: Fix compiler warnings in publisher tour JS
  static/js/publisher/tour/tourOverlay.tsx
Labels: Review: Code +1

#4686 fix: Fix compiler warnings in publisher release JS
  static/js/publisher/release/reducers/pendingReleases.ts
  static/js/publisher/release/selectors/index.ts
Labels: Review: Code +1

#4687 fix: Fix compiler warnings in publisher JS
  package.json
  static/js/global.d.ts
  static/js/publisher/form.ts
  static/js/publisher/preview.ts
  static/js/publisher/publicise.ts
  static/js/publisher/release.tsx
  static/js/publisher/submitEnabler.ts
  webpack.config.entry.js
  webpack.config.rules.js
  yarn.lock
Labels: Review: Code +1

#4689 fix: Fix compiler warnings in public snap details JS
  static/js/global.d.ts
  static/js/public/snap-details/channelMap.ts
  static/js/public/snap-details/embeddedCard.ts
  static/js/public/snap-details/videos.ts
Labels: Review: Code +1

#4692 fix: Fix compiler warnings in channel map JS
  static/js/public/snap-details/channelMap.ts
Labels: Review: Code +1

#4696 fix: Fix last python compiler warning
  webapp_beta/beta_app.py
Labels: Review: Code +1

#4700 chore: Increase code coverage for brand store JS
  static/js/brand-store/components/AccountDetails/__tests__/AccountDetails.test.tsx
  static/js/brand-store/components/Members/__tests__/InviteModal.test.tsx
  static/js/brand-store/components/Navigation/__tests__/Navigation.test.tsx
  static/js/brand-store/components/Publisher/__tests__/Publisher.test.tsx
  static/js/brand-store/components/Reviewer/__tests__/Reviewer.test.tsx
  static/js/brand-store/components/ReviewerAndPublisher/__tests__/ReviewerAndPubliser.test.tsx
  static/js/brand-store/components/StoreNotFound/__tests__/StoreNotFound.test.tsx
  static/js/brand-store/hooks/__tests__/useBrand.test.ts
  static/js/brand-store/hooks/__tests__/useModels.test.ts
  static/js/brand-store/hooks/__tests__/usePolicies.test.ts
  static/js/brand-store/hooks/__tests__/usePublisher.test.ts
  static/js/brand-store/hooks/__tests__/useSigningKeys.test.ts
Labels: Review: Code +1

#4702 chore: Increase test coverage for publisher JS
  static/js/publisher/collaboration/components/App/App.tsx
  static/js/publisher/collaboration/components/App/index.tsx
  static/js/publisher/collaboration/index.tsx
  static/js/publisher/collaboration/types/index.d.ts
  static/js/publisher/listing/utils/__tests__/formatFileSize.test.ts
  static/js/publisher/listing/utils/__tests__/getChanges.test.ts
  static/js/publisher/listing/utils/__tests__/validateAspectRatio.test.ts
  static/js/publisher/listing/utils/__tests__/validateImageDimensions.test.ts
  templates/publisher/collaboration.html
  webpack.config.entry.js
Labels: Review: Code +1, Review: QA +1

#4703 chore: Increase publisher JS code coverage
  static/js/publisher/listing/sections/AdditionalInformationSection/__tests__/AdditionalInformationSection.test.tsx
  static/js/publisher/listing/utils/__tests__/getChanges.test.ts
  static/js/publisher/listing/utils/__tests__/getFormData.test.ts
  static/js/publisher/listing/utils/__tests__/getListingData.test.ts
  static/js/publisher/listing/utils/__tests__/shouldShowUpdateMetadataWarning.test.ts
  static/js/publisher/listing/utils/shouldShowUpdateMetadataWarning.ts
  static/js/publisher/shared/SaveAndPreview/SaveAndPreview.test.tsx
  static/js/publisher/shared/UpdateMetadataModal/__tests__/UpdateMetadataModal.test.tsx
Labels: Review: Code +1

#4704 feat: Add separators to brand store navigation
  static/js/brand-store/components/Navigation/Navigation.tsx
  static/sass/_snapcraft_l-application.scss
Labels: Review: Code +1, Review: UX +1, Review: QA +1

#4707 ci: install js deps for tics
  .github/workflows/coverage.yml
Labels: Review: Code +1

#4709 fix: use p-navigation__row--25-75 and add highlights on Snapcraft.io navigation
  templates/_header.html
Labels: Review: Code +1, Review: QA +1

#4710 fix: fix coding standard violations in brandstore model breadcrumb
  static/js/brand-store/components/Model/ModelBreadcrumb.tsx
Labels: Review: Code +1

#4712 feat: Add helper to generate DNS verification token
  konf/site.yaml
  tests/tests_helpers.py
  webapp/helpers.py
Labels: Review: Code +1, Review: QA +1

#4714 fix: add missing types on return functions in /static/js/brandstore
  static/js/brand-store/utils/checkModelNameExists.ts
  static/js/brand-store/utils/checkSigningKeyExists.ts
  static/js/brand-store/utils/isClosedPanel.ts
  static/js/brand-store/utils/setPageTitle.ts
Labels: Review: Code +1

#4713 fix: add missing return types on functions in /static/js/publisher/listing
  static/js/publisher/listing/utils/formatFileSize.ts
  static/js/publisher/listing/utils/validateAspectRatio.ts
Labels: Review: Code +1

#4716 feat: Create endpoint to verify domain
  konf/staging-api.snapcraft.io.yaml
  requirements.txt
  webapp/store/snap_details_views.py
Labels: Review: Code +1, Review: QA +1

#4719 chore: update storeapi version
  requirements.txt
Labels: Review: Code +1

#4720 Update dns key name
  konf/site.yaml
Labels: Review: Code needed

#4721 fix: Fix DNS verification token
  webapp/config.py
  webapp/handlers.py
Labels: Review: Code +1, Review: QA +1

#4715 fix: add missing return types and avoid using any in /static/js/public/snap-details
  static/js/public/snap-details/videos.ts
Labels: Review: Code +1

#4722 feat: Separate primary domain from other domains
  static/js/publisher/listing/components/ListingFormInput/ListingFormInput.tsx
  static/js/publisher/listing/sections/ContactInformationSection/ContactInformationSection.tsx
  static/js/publisher/listing/utils/__tests__/getChanges.test.ts
  static/js/publisher/listing/utils/__tests__/getListingData.test.ts
  static/js/publisher/listing/utils/getChanges.ts
  static/js/publisher/listing/utils/getListingData.ts
Labels: Review: Code +1, Review: QA +1

#4725 feat: adds get_package_metadata flask endpoint
  tests/publisher/tests_get_package_metadata.py
  webapp/publisher/snaps/views.py
Labels: Review: Code +1

#4727 feat(snapReporting): Update reporting snap violation flow
  templates/store/snap-details.html
  templates/store/snap-details/_details.html
  templates/store/snap-details/_report_snap_modal.html
  tests/tests_templates_utils.py
  webapp/template_utils.py
Labels: Review: Code +1, Review: QA +1
