Repository canonical/snapcraft.io, pull requests merged in 2024-04, with the labels that each got.

#4573 Add track dropdown on all Snap release pages
  static/js/publisher/release/components/defaultTrackModifier.js
  static/js/publisher/release/components/releasesHeading.js
  static/js/publisher/release/components/trackDropdown.js
  static/sass/_snapcraft_release.scss
Labels: Review: Code +1, Review: QA +1

#4574 Add Request track aside panel
  static/js/publisher/release/components/releasesHeading.js
  static/js/publisher/release/components/trackDropdown.js
  static/js/publisher/release/releasesController.js
  static/sass/_snapcraft_release.scss
Labels: Review: Code +1, Review: UX +1, Review: QA +1

#4575 Fix unauthenticated agreement acceptance issue
  webapp/publisher/views.py
Labels: Review: Code +1, Review: QA +1

#4576 add tests for update-featured-snaps endpoint
  requirements.txt
  tests/admin/__init__.py
  tests/admin/admin_endpoint_testing.py
  tests/admin/test_brand_store.py
  tests/admin/tests_models.py
  tests/admin/tests_update_featured_snaps.py
  webapp/admin/views.py
  webapp/authentication.py
Labels: Review: Code +1

#4578 Revert "Fix unauthenticated agreement acceptance issue (#4575)"
  webapp/publisher/views.py
Labels: Review: Code +1, Review: QA +1

#4579 WD-9998 show 0% instead of NaN% on Snapcraft metrics graph
  static/js/publisher/metrics/graphs/activeDevicesGraph/tooltips.js
Labels: Review: Code +1, Review: QA +1

#4584 Only show stores is publisher has stores
  static/js/brand-store/components/AccountDetails/AccountDetails.tsx
  static/js/brand-store/components/AccountDetails/index.ts
  static/js/brand-store/components/App/App.tsx
  static/js/brand-store/components/Navigation/Navigation.tsx
Labels: Review: Code +1, Review: QA +1

#4587 Update account details links
  static/js/brand-store/components/Navigation/Navigation.tsx
  templates/_header.html
Labels: Review: Code +1, Review: QA +1

#4568 webapp/store/content/distros/arch: update instructions to mention snapd.apparmor.service
  webapp/store/content/distros/arch.yaml
Labels: Review: Code +1, Review: QA +1

#4593 Fix error message for releases
  static/js/publisher/release/components/notification.js
  static/js/publisher/release/releasesController.js
  webapp/publisher/snaps/release_views.py
Labels: Review: Code +1, Review: QA +1

#4594 Disable promote to promote option for devrel releases
  static/js/publisher/release/components/releasesTable/releaseMenuItem.js
Labels: Review: Code +1, Review: QA +1

#4596 Adds "Add track" functionality
  static/js/publisher/release/components/releasesHeading.js
  static/js/publisher/release/helpers.js
  static/js/publisher/release/releasesController.js
  static/sass/_snapcraft_release.scss
Labels: Review: Code needed, Review: UX +1, Review: QA needed

#4598 Fix beta store featured snaps
  static/js/store/components/Packages/Packages.tsx
Labels: Review: Code needed, Review: QA needed

#4599 Modify track creation guardrails information
  static/js/publisher/release/components/releasesHeading.js
Labels: Review: Code +1, Review: UX +1, Review: QA +1

#4600 Add column sorting to brand store
  static/js/brand-store/components/Snaps/IncludedSnapsTable.tsx
  static/js/brand-store/components/Snaps/PublishedSnapsTable.tsx
  static/sass/styles.scss
Labels: Review: Code +1, Review: QA +1

#4603 Show notification and set private to true
  templates/publisher/register-snap.html
Labels: Review: Code +1, Review: QA +1

#4605 Update snap feedback form to post to correct Google Form
  templates/store/snap-details/_report_snap_modal.html
Labels: Review: Code +1, Review: QA +1

#4606 Modify breakpoint-navigation-threshold
  static/sass/styles.scss
Labels: Review: Code +1, Review: QA +1

#4607 hide privacy section when user has only global store
  templates/publisher/register-snap.html
Labels: Review: Code +1, Review: QA +1

#4608 Add some attempt to reduce spam on report snap form
  static/js/public/snap-details/reportSnap.js
  templates/store/snap-details/_report_snap_modal.html
  webapp/store/snap_details_views.py
Labels: Review: Code +1, Review: QA +1

#4610 make link clickable in error message
  package.json
  templates/publisher/register-snap.html
  webapp/publisher/snaps/views.py
Labels: Review: Code +1, Review: QA +1
