Repository canonical/snapcraft.io, pull requests merged in 2024-10, with the labels that each got.

#4863 Wd 15262 improve performance of metric page
  jest.config.js
  static/js/publisher-pages/hooks/__tests__/useActiveDeviceMetrics.test.ts
  static/js/publisher-pages/hooks/__tests__/useActiveDeviceMetrics.test.tsx
  static/js/publisher-pages/hooks/useActiveDeviceMetrics.ts
  static/js/publisher-pages/hooks/useLatestActiveDevicesMetric.ts
  static/js/publisher-pages/hooks/useMetricsAnnotation.ts
  static/js/publisher-pages/pages/Metrics/ActiveDeviceMetrics.tsx
  static/js/publisher-pages/pages/Metrics/__tests__/ActiveDeviceMetrics.test.tsx
  webapp/metrics/helper.py
  webapp/publisher/snaps/metrics_views.py
  webapp/publisher/snaps/views.py
Labels: Review: Code +1, Review: QA +1

#4869 feat: Update Corp policy
  webapp/handlers.py
Labels: Review: Code +1

#4874 fix: show error when set default track returns 400
  static/js/publisher/release/actions/defaultTrack.js
  static/js/publisher/release/actions/defaultTrack.test.js
Labels: Review: Code +1, Review: QA +1

#4876 fix: self serve tracks metadata error
  static/js/publisher/release.tsx
  static/js/publisher/release/components/releasesHeading.js
  static/js/publisher/release/helpers.test.js
  static/js/publisher/release/helpers.ts
Labels: Review: Code +1, Review: QA +1

#4881 Update TiCS workflow to run once per week
  .github/workflows/coverage.yml
Labels: Review: Code +1

#4884 feat: remove security headers temporarily
  webapp/handlers.py
Labels: Review: Code +1, Review: QA +1

#4885 feat: remove caching temporarily
  webapp/handlers.py
Labels: Review: Code +1, Review: QA +1

#4886 chore: update internal deps
  package.json
  static/sass/_button-overrides.scss
  static/sass/_patterns_strip_slanted.scss
  static/sass/_snapcraft_details_heading.scss
  static/sass/_snapcraft_tour.scss
  yarn.lock
Labels: Review: Code +1, Review: QA +1

#4883 feat: added endpoint for install badge
  webapp/helpers.py
  webapp/store/snap_details_views.py
Labels: Review: Code needed, Review: QA needed

#4887 chore: added security headers back
  webapp/handlers.py
Labels: Review: Code +1, Review: QA +1

#4888 feat: Update badge urls
  templates/publisher/publicise/store_buttons.html
  templates/store/snap-embedded-card.html
Labels: Review: Code +1, Review: QA +1

#4893 feat: add an extra day to fix the reset issue on the metric page
  webapp/metrics/helper.py
Labels: Review: Code +1, Review: QA +1

#4892 Wd 15869 security header badge issue
  static/js/publisher-pages/pages/Publicise/PubliciseButtons.tsx
  templates/store/snap-embedded-card.html
Labels: Review: Code +1, Review: QA +1
