Repository canonical/snapcraft.io, pull requests merged in 2024-03, with the labels that each got.

#4545 fix: add timestamp to screenshots on upload
  static/js/publisher/listing/utils/getFormData.ts
Labels: Review: Code +1, Review: QA +1

#4547 feat: show percentages in the metrics graph for publishers
  static/js/publisher/metrics/graphs/activeDevicesGraph/tooltips.js
  static/sass/_snapcraft_graph-tooltip.scss
Labels: Review: Code +1, Review: QA +1

#4548 Update headings in brand store
  static/js/brand-store/components/Members/Members.tsx
  static/js/brand-store/components/Model/Model.test.tsx
  static/js/brand-store/components/Model/Model.tsx
  static/js/brand-store/components/Model/ModelBreadcrumb.tsx
  static/js/brand-store/components/Model/Policies.test.tsx
  static/js/brand-store/components/Model/Policies.tsx
  static/js/brand-store/components/Models/Models.test.tsx
  static/js/brand-store/components/Models/Models.tsx
  static/js/brand-store/components/Navigation/Navigation.tsx
  static/js/brand-store/components/SectionNav/SectionNav.test.tsx
  static/js/brand-store/components/SectionNav/SectionNav.tsx
  static/js/brand-store/components/SectionNav/index.ts
  static/js/brand-store/components/Settings/Settings.tsx
  static/js/brand-store/components/SigningKeys/SigningKeys.tsx
  static/js/brand-store/components/Snaps/Snaps.tsx
  static/js/brand-store/components/Snaps/SnapsTables.tsx
Labels: Review: Code +1, Review: QA +1

#4551 fix: by-channel metrics legend missing latest track
  webapp/publisher/snaps/metrics_views.py
Labels: Review: Code +1, Review: QA +1

#4553 fix: build page 503ing when api key access forbidden
  webapp/api/github.py
  webapp/publisher/snaps/build_views.py
Labels: Review: Code +1, Review: QA +1

#4556 Fix invisible links in global nav
  static/sass/styles.scss
Labels: Review: Code +1, Review: QA +1

#4550 Application layout
  static/js/brand-store/brand-store.tsx
  static/js/brand-store/components/App/App.tsx
  static/js/brand-store/components/Members/Members.tsx
  static/js/brand-store/components/Model/Model.test.tsx
  static/js/brand-store/components/Model/Model.tsx
  static/js/brand-store/components/Model/ModelBreadcrumb.tsx
  static/js/brand-store/components/Model/Policies.test.tsx
  static/js/brand-store/components/Model/Policies.tsx
  static/js/brand-store/components/Models/Models.test.tsx
  static/js/brand-store/components/Models/Models.tsx
  static/js/brand-store/components/Navigation/Logo.tsx
  static/js/brand-store/components/Navigation/Navigation.tsx
  static/js/brand-store/components/SectionNav/SectionNav.test.tsx
  static/js/brand-store/components/SectionNav/SectionNav.tsx
  static/js/brand-store/components/SectionNav/index.ts
  static/js/brand-store/components/Settings/Settings.test.tsx
  static/js/brand-store/components/Settings/Settings.tsx
  static/js/brand-store/components/SigningKeys/SigningKeys.tsx
  static/js/brand-store/components/Snaps/Snaps.tsx
  static/js/brand-store/components/Snaps/SnapsTables.tsx
  static/js/brand-store/hooks/index.ts
  static/sass/_snapcraft_l-application.scss
  static/sass/styles.scss
  templates/_base-layout.html
  templates/admin/admin.html
Labels: Review: Code +1, Review: UX +1, Review: QA +1

#4557 Update global nav
  package.json
  static/sass/styles.scss
  yarn.lock
Labels: Review: Code +1, Review: QA +1

#4558 Clear new member form on close
  static/js/brand-store/components/Members/Members.tsx
Labels: Review: Code +1, Review: QA +1

#4563 Update model view design
  static/js/brand-store/components/Model/Model.tsx
  static/js/brand-store/components/Models/CreateModelForm.tsx
  static/js/brand-store/components/Navigation/Navigation.tsx
  static/sass/styles.scss
Labels: Review: Code +1, Review: UX +1, Review: QA +1

#4559 Update brand store snaps view
  static/js/brand-store/components/Snaps/IncludedSnapsTable.tsx
  static/js/brand-store/components/Snaps/PublishedSnapsTable.tsx
  static/js/brand-store/components/Snaps/Snaps.tsx
  static/sass/styles.scss
Labels: Review: Code +1, Review: QA +1

#4566 Add overview link to brand store navigation
  static/js/brand-store/components/Navigation/Navigation.tsx
  static/sass/_snapcraft_l-application.scss
Labels: Review: Code +1, Review: QA +1

#4567 Add publisher data endpoint
  tests/publisher/tests_account_details.py
  webapp/helpers.py
  webapp/publisher/views.py
Labels: Review: Code +1, Review: QA +1

#4569 Remove account json endpoint
  static/js/base/navigation.js
  static/js/brand-store/hooks/index.ts
  webapp/snapcraft/views.py
Labels: Review: Code +1, Review: QA +1

#4570 add endpoint to update featured snaps
  webapp/admin/views.py
Labels: Review: Code +1

#4564 WIP: Add post_create_track method
  webapp/store/views.py
Labels: Review: QA +1, Review: Code +1 (with changes)
