Repository canonical/snapcraft.io, pull requests merged in 2024-12, with the labels that each got.

#4921 fix: Fix code linting errors in publisher app
  .eslintrc.js
  static/js/publisher-pages/components/SaveAndPreview/SaveAndPreview.test.tsx
  static/js/publisher-pages/components/SaveAndPreview/SaveAndPreview.tsx
  static/js/publisher-pages/components/SaveStateNotifications/SaveStateNotifications.tsx
  static/js/publisher-pages/components/SaveStateNotifications/__tests__/SaveStateNotifications.test.tsx
  static/js/publisher-pages/components/SearchAutocomplete/SearchAutocomplete.tsx
  static/js/publisher-pages/components/SectionNav/SectionNavTest.tsx
  static/js/publisher-pages/components/UpdateMetadataModal/UpdateMetadataModal.tsx
  static/js/publisher-pages/components/UpdateMetadataModal/__tests__/UpdateMetadataModal.test.tsx
  static/js/publisher-pages/hooks/__tests__/useActiveDeviceMetrics.test.tsx
  static/js/publisher-pages/hooks/useActiveDeviceMetrics.ts
  static/js/publisher-pages/hooks/useMetricsAnnotation.ts
  static/js/publisher-pages/hooks/useMutateListingData.ts
  static/js/publisher-pages/pages/Build/Build.tsx
  static/js/publisher-pages/pages/Builds/DisconnectRepoActions.tsx
  static/js/publisher-pages/pages/Builds/RepoConnected.tsx
  static/js/publisher-pages/pages/Builds/RepoNotConnected.tsx
  static/js/publisher-pages/pages/Builds/RepoSelector.tsx
  static/js/publisher-pages/pages/Listing/AdditionalInformation/LicenseInputs.tsx
  static/js/publisher-pages/pages/Listing/AdditionalInformation/LicenseSearch.tsx
  static/js/publisher-pages/pages/Listing/ContactInformation/__tests__/PrimaryDomainInput.test.tsx
  static/js/publisher-pages/pages/Listing/ListingDetails/Screenshot.tsx
  static/js/publisher-pages/pages/Listing/ListingDetails/ScreenshotList.tsx
  static/js/publisher-pages/pages/Listing/ListingDetails/Screenshots.tsx
  static/js/publisher-pages/pages/Listing/ListingForm/ListingForm.tsx
  static/js/publisher-pages/pages/Listing/PreviewForm/PreviewForm.tsx
  static/js/publisher-pages/pages/Metrics/ActiveDeviceMetrics.tsx
  static/js/publisher-pages/pages/Metrics/Metrics.tsx
  static/js/publisher-pages/pages/Metrics/TerritoryMetrics.tsx
  static/js/publisher-pages/pages/Metrics/__tests__/ActiveDeviceAnnotation.test.tsx
  static/js/publisher-pages/pages/Metrics/__tests__/ActiveDeviceMetrics.test.tsx
  static/js/publisher-pages/pages/Metrics/__tests__/TerritoryMetrics.test.tsx
  static/js/publisher-pages/pages/Publicise/PubliciseCards.tsx
  static/js/publisher-pages/pages/Publicise/__tests__/Publicise.test.tsx
  static/js/publisher-pages/pages/Settings/SettingsForm.tsx
  static/js/publisher-pages/pages/Settings/UnregisterSnapModal.tsx
  static/js/publisher-pages/pages/Settings/__tests__/UnregisterSnapModal.test.tsx
  static/js/publisher-pages/utils/formatImageChanges.ts
  static/js/publisher-pages/utils/getDefaultListingData.ts
  static/js/publisher-pages/utils/getListingChanges.ts
  static/js/publisher-pages/utils/getSettingsChanges.ts
  static/js/publisher-pages/utils/getSettingsFormData.ts
  static/js/publisher-pages/utils/shouldShowUpdateMetadataWarning.ts
Labels: Review: Code +1

#4922 fix: Fix publisher a11y error in builds section
  static/js/publisher-pages/pages/Builds/RepoSelector.tsx
Labels: Review: Code +1, Review: QA +1

#4923 fix: Fix publisher a11y errors in publicise cards section
  static/js/publisher-pages/pages/Publicise/PubliciseCards.tsx
Labels: Review: Code +1, Review: QA +1

#4924 fix: Fix publisher a11y errors in publicise badges section
  static/js/publisher-pages/pages/Publicise/PubliciseBadges.tsx
Labels: Review: Code +1, Review: QA +1

#4927 fix: fix bug in listing page markdown
  static/js/publisher/listing/components/ListingDetails/ListingDetails.tsx
Labels: Review: Code +1, Review: QA +1

#4928 fix: Fix a11y errors in license search
  static/js/publisher-pages/pages/Listing/AdditionalInformation/LicenseSearch.tsx
  static/js/publisher-pages/pages/Listing/ListingDetails/ListingDetails.tsx
  static/sass/_patterns_form-multiselect.scss
Labels: Review: Code +1, Review: QA +1

#4929 fix: Fix a11y errors in search autocomplete
  static/js/publisher-pages/components/SearchAutocomplete/SearchAutocomplete.tsx
Labels: Review: Code +1, Review: QA +1

#4935 fix: stick metrics tooltip to edge of screen
  static/js/publisher/metrics/graphs/activeDevicesGraph/tooltips.ts
Labels: Review: Code +1, Review: QA +1

#4937 fix: Fix checkbox values resetting in publisher settings form
  static/js/publisher-pages/pages/Settings/SettingsForm.tsx
Labels: Review: Code +1, Review: QA +1

#4938 fix: Fix primary website field clearing on revert
  static/js/publisher-pages/pages/Listing/ContactInformation/PrimaryDomainInput.tsx
  static/js/publisher-pages/pages/Listing/ContactInformation/__tests__/PrimaryDomainInput.test.tsx
Labels: Review: Code +1, Review: QA +1

#4939 fix: Make sure Edit button on preview page closes current tab
  static/js/publisher-pages/pages/Listing/PreviewForm/PreviewForm.tsx
  templates/publisher/account-snaps.html
  templates/publisher/publicise/store_buttons.html
  templates/store/snap-details.html
Labels: Review: Code +1, Review: QA +1

#4940 fix: Fix deleting icon or banner not activating save button
  static/js/publisher-pages/pages/Listing/ListingDetails/ImageUpload.tsx
  static/js/publisher-pages/pages/Listing/ListingDetails/ListingDetails.tsx
Labels: Review: Code +1, Review: QA +1

#4942 fix: render selected language in HTML and markdown snippets
  static/js/publisher-pages/pages/Publicise/PubliciseButtons.tsx
  webapp/publisher/snaps/publicise_views.py
Labels: Review: Code +1, Review: QA +1

#4943 fix: remove extra whitespace in embeddable card
  static/js/publisher-pages/pages/Publicise/PubliciseCards.tsx
Labels: Review: Code +1, Review: QA +1

#4945 fix: Fix preview card button being squashed
  static/sass/styles-embedded.scss
  templates/store/snap-embedded-card.html
Labels: Review: Code +1, Review: QA +1

#4946 fix: Fix display of releases table
  static/js/publisher-pages/pages/Releases/components/releasesHeading.js
  static/sass/styles.scss
Labels: Review: Code needed, Review: QA needed

#4947 fix: Add loading state to single build page
  static/js/publisher-pages/pages/Build/Build.tsx
  static/js/publisher-pages/pages/Releases/Releases.tsx
Labels: Review: Code +1, Review: QA +1

#4948 fix: ensure markdown is rendered correctly
  webapp/markdown.py
Labels: Review: Code +1, Review: QA +1

#4950 fix: Fix missing banner in listing publisher page
  static/js/publisher-pages/pages/Listing/ListingDetails/ImageUpload.tsx
  static/js/publisher-pages/utils/__tests__/getDefaultListingData.test.ts
  static/js/publisher-pages/utils/getDefaultListingData.ts
Labels: Review: Code +1, Review: QA +1

#4952 fix: Fix form not resetting when making changes to images
  static/js/publisher-pages/hooks/useMutateListingData.ts
  static/js/publisher-pages/utils/__tests__/formatImageChanges.test.ts
  static/js/publisher-pages/utils/formatImageChanges.ts
  static/js/publisher-pages/utils/getListingChanges.ts
Labels: Review: Code +1, Review: QA +1
