Repository canonical/snapcraft.io, pull requests merged in 2024-05, with the labels that each got.

#4613 feat: use codecov config
  .github/workflows/pr.yml
  codecov.yml
Labels: Review: Code +1, Review: QA +1

#4612 Update snap settings page
  static/js/publisher/settings/components/App/App.tsx
  static/js/publisher/settings/types/SettingsData.d.ts
  templates/publisher/settings.html
  tests/publisher/snaps/tests_settings.py
  webapp/publisher/snaps/settings_views.py
Labels: Review: Code +1

#4617 Add delete package endpoint
  webapp/authentication.py
  webapp/publisher/snaps/views.py
Labels: Review: Code +1, Review: QA +1

#4621 feat: Move beta store to store page
  static/js/store/components/App/App.tsx
  static/js/store/components/Packages/Packages.tsx
  static/js/store/types/shared.ts
  templates/store/beta.html
  templates/store/store.html
  tests/store/tests_get_store_view.py
  webapp/store/views.py
Labels: Review: Code +1, Review: QA +1

#4622 Modify Github PR template for testing
  .github/pull_request_template.md
Labels: Review: Code +1, Review: QA +1

#4624 fix: Remove featured category query param for search queries
  jest.config.js
  static/js/store/components/Packages/Packages.tsx
  static/js/store/components/Packages/__tests__/Packages.test.tsx
Labels: Review: Code +1, Review: QA +1

#4625 fix: Update markdown for PR template for checkboxes
  .github/pull_request_template.md
Labels: Review: Code +1

#4631 fix: Update homepage search to use the new store page results
  redirects.yaml
  templates/404.html
  templates/410.html
  templates/home/_featured-snaps.html
  templates/partials/search-bar.html
  templates/store/search.html
  tests/store/tests_search.py
  webapp/store/views.py
Labels: Review: Code +1, Review: QA +1

#4633 fix: workflow-typo
  .github/workflows/coverage.yml
Labels: Review: Code +1

#4634 ci: Remove unused workflows
  .github/workflows/docs-links.yaml
  .github/workflows/main.yml
  .github/workflows/run-percy.yml
Labels: Review: Code +1

#4635 fix: tics upload workflow
  .github/workflows/coverage.yml
Labels: Review: Code +1

#4628 Bump StoreAPI minor version
  requirements.txt
  webapp/authentication.py
Labels: Review: Code +1

#4632 fix: Update .jira_sync_config.yaml
  .github/.jira_sync_config.yaml
Labels: Review: Code +1

#4636 Fix tics workflow
  .github/workflows/coverage.yml
Labels: Review: Code +1

#4637 Fix tics workflow
  .github/workflows/coverage.yml
Labels: Review: Code +1

#4638 Fix tics workflow
  .github/workflows/coverage.yml
Labels: Review: Code +1

#4642 set coverage threshold
  codecov.yml
Labels: Review: Code +1

#4641 fix: Expand category filters if selected not visible
  package.json
  static/js/store/components/Packages/Packages.tsx
  static/js/store/components/Packages/__tests__/Packages.test.tsx
  static/js/store/mocks/index.ts
  static/js/store/mocks/test-categories.ts
  yarn.lock
Labels: Review: Code +1, Review: QA +1

#4643 ci: dotrun-run pr check
  .github/workflows/pr.yml
Labels: Review: Code +1, Review: QA +1

#4644 ci: lint and test based on changed files
  .github/workflows/pr.yml
Labels: Review: Code +1

#4646 chore: Restructure store to match standardised architecture
  static/js/public/store-categories.js
  static/js/public/store.js
  static/js/store/components/App/App.tsx
  static/js/store/pages/Packages/Packages.tsx
  static/js/store/pages/Packages/__tests__/Packages.test.tsx
  static/js/store/pages/Packages/index.ts
  static/js/store/types/components/Category.d.ts
  static/js/store/types/components/Package.d.ts
  static/js/store/types/index.d.ts
  static/js/store/utils/getArchitectures.ts
  static/js/store/utils/getCategoryOrder.ts
  static/js/store/utils/index.ts
  templates/store/store.html
  webpack.config.entry.js
  webpack.config.rules.js
Labels: Review: Code +1, Review: QA +1

#4655 ci: add python coverage upload to tics
  .github/workflows/coverage.yml
  jest.config.js
Labels: Review: Code needed

#4657 docs: add links to coverage reports
  README.md
Labels: Review: Code +1

#4658 fix: Convert base JS to TypeScript to fix compiler errors
  static/js/base/base.js
  static/js/base/dropdown-menu-toggle.ts
  static/js/base/ga.ts
  static/js/base/polyfills.js
  static/js/global.d.ts
Labels: Review: Code +1

#4660 fix: Fix compiler errors in brand store JS
  static/js/brand-store/brand-store.tsx
  static/js/brand-store/components/AccountDetails/AccountDetails.tsx
  static/js/brand-store/components/App/App.tsx
  static/js/brand-store/components/AppPagination/AppPagination.tsx
  static/js/brand-store/components/Members/InviteModal.tsx
  static/js/brand-store/components/Members/InvitesTable.tsx
  static/js/brand-store/components/Members/Members.tsx
  static/js/brand-store/components/Members/MembersTable.tsx
  static/js/brand-store/components/Model/CreatePolicyForm.test.tsx
  static/js/brand-store/components/Model/CreatePolicyForm.tsx
  static/js/brand-store/components/Model/Model.test.tsx
  static/js/brand-store/components/Model/Model.tsx
  static/js/brand-store/components/Model/ModelBreadcrumb.tsx
  static/js/brand-store/components/Model/ModelNav.test.tsx
  static/js/brand-store/components/Model/ModelNav.tsx
  static/js/brand-store/components/Model/Policies.test.tsx
  static/js/brand-store/components/Model/Policies.tsx
  static/js/brand-store/components/Model/PoliciesFilter.test.tsx
  static/js/brand-store/components/Model/PoliciesFilter.tsx
  static/js/brand-store/components/Model/PoliciesTable.test.tsx
  static/js/brand-store/components/Model/PoliciesTable.tsx
  static/js/brand-store/components/Models/CreateModelForm.test.tsx
  static/js/brand-store/components/Models/CreateModelForm.tsx
  static/js/brand-store/components/Models/Models.test.tsx
  static/js/brand-store/components/Models/Models.tsx
  static/js/brand-store/components/Models/ModelsFilter.test.tsx
  static/js/brand-store/components/Models/ModelsFilter.tsx
  static/js/brand-store/components/Models/ModelsTable.test.tsx
  static/js/brand-store/components/Models/ModelsTable.tsx
  static/js/brand-store/components/Navigation/Logo.tsx
  static/js/brand-store/components/Navigation/Navigation.tsx
  static/js/brand-store/components/Publisher/Publisher.tsx
  static/js/brand-store/components/Reviewer/Reviewer.tsx
  static/js/brand-store/components/ReviewerAndPublisher/ReviewerAndPublisher.tsx
  static/js/brand-store/components/Settings/Settings.test.tsx
  static/js/brand-store/components/Settings/Settings.tsx
  static/js/brand-store/components/SigningKeys/CreateSigningKeyForm.tsx
  static/js/brand-store/components/SigningKeys/DeactivateSigningKeyModal.tsx
  static/js/brand-store/components/SigningKeys/SigningKeys.tsx
  static/js/brand-store/components/SigningKeys/SigningKeysFilter.tsx
  static/js/brand-store/components/SigningKeys/SigningKeysTable.tsx
  static/js/brand-store/components/Snaps/IncludedSnapsTable.tsx
  static/js/brand-store/components/Snaps/PublishedSnapsTable.tsx
  static/js/brand-store/components/Snaps/Snaps.tsx
  static/js/brand-store/components/Snaps/SnapsFilter.tsx
  static/js/brand-store/components/Snaps/SnapsSearch.tsx
  static/js/brand-store/components/StoreNotFound/StoreNotFound.tsx
  static/js/brand-store/slices/membersSlice.ts
  static/js/store/pages/Packages/__tests__/Packages.test.tsx
Labels: Review: Code +1

#4661 fix: Fix compiler warnings in libs JS
  static/js/libs/debounce.ts
  static/js/libs/iframeSize.ts
  static/js/libs/mobile.ts
Labels: Review: Code +1

#4663 fix: Made dropdown js an isoloated module to fix compiler error
  static/js/base/dropdown-menu-toggle.ts
Labels: Review: Code +1

#4664 fix: Fix compiler errors in publisher collaborators JS
  static/js/publisher/collaboration/components/App/App.tsx
  static/js/publisher/collaboration/index.tsx
Labels: Review: Code +1

#4665 fix: Fix compiler errors in publisher builds JS
  static/js/publisher/builds/components/repoConnect.js
  static/js/publisher/builds/repoDisconnect.js
  templates/publisher/_repo-disconnect-modal.html
Labels: Review: Code +1

#4666 fix: Fix compiler errors in publisher form JS
  static/js/publisher/form/banner.js
Labels: Review: Code +1

#4667 fix: Fix compiler warnings in publisher listing JS
  static/js/publisher/listing/components/CategoriesInput/CategoriesInput.test.tsx
  static/js/publisher/listing/components/CategoriesInput/CategoriesInput.tsx
  static/js/publisher/listing/components/ImageUpload/ImageUpload.tsx
  static/js/publisher/listing/components/LicenseInputs/LicenseInputs.tsx
  static/js/publisher/listing/components/LicenseInputs/LicenseSearch.tsx
  static/js/publisher/listing/components/ListingDescriptionField/ListingDescriptionField.tsx
  static/js/publisher/listing/components/ListingFormInput/ListingFormInput.tsx
  static/js/publisher/listing/components/MetricsInputs/MetricsInputs.test.tsx
  static/js/publisher/listing/components/MetricsInputs/MetricsInputs.tsx
  static/js/publisher/listing/components/MultipleInputs/MultipleInputs.tsx
  static/js/publisher/listing/components/PreviewForm/PreviewForm.tsx
  static/js/publisher/listing/components/Screenshots/Screenshot.tsx
  static/js/publisher/listing/components/Screenshots/ScreenshotList.tsx
  static/js/publisher/listing/components/Screenshots/Screenshots.tsx
  static/js/publisher/listing/components/UrlInput/UrlInput.tsx
  static/js/publisher/listing/index.tsx
  static/js/publisher/listing/sections/AdditionalInformationSection/AdditionalInformationSection.tsx
  static/js/publisher/listing/sections/ContactInformationSection/ContactInformationSection.tsx
  static/js/publisher/listing/sections/ListingDetailsSection/ListingDetailsSection.tsx
Labels: Review: Code +1

#4668 fix: Fix compiler errors in publisher market JS
  static/js/publisher/market/categories.ts
  static/js/publisher/market/lightbox.js
  static/js/publisher/market/lightbox.ts
  static/js/publisher/market/storageCommands.test.js
  static/js/publisher/market/storageCommands.ts
Labels: Review: Code +1

#4669 fix: Fix compiler warnings in repoDisconnect JS
  static/js/publisher/builds/repoDisconnect.ts
Labels: Review: Code +1
