Repository canonical/snapcraft.io, pull requests merged in 2024-07, with the labels that each got.

#4724 feat: Show domain verified status on snap page
  package.json
  templates/store/snap-details/_details.html
  yarn.lock
Labels: Review: Code +1, Review: UX +1, Review: Design +1, Review: QA +1

#4729 fix: refactor add track logic with track guardrails
  static/js/publisher/release/components/releasesHeading.js
  static/js/publisher/release/helpers.test.js
  static/js/publisher/release/helpers.ts
Labels: Review: Code +1, Review: QA +1

#4732 fix: fix coding standard violations in /static/js/publisher/release.tsx
  static/js/global.d.ts
  static/js/publisher/release.tsx
  static/js/publisher/types/releaseTypes.d.ts
Labels: Review: Code +1

#4733 fix: Fix DNS validation breaking snap page with no domain
  static/js/publisher/listing/components/PrimaryDomainInput/PrimaryDomainInput.tsx
  static/js/publisher/listing/components/PrimaryDomainInput/__tests__/PrimaryDomainInput.test.tsx
  webapp/publisher/snaps/listing_views.py
Labels: Review: Code +1, Review: QA +1

#4734 Enable all tests for primary domain
  static/js/publisher/listing/components/PrimaryDomainInput/PrimaryDomainInput.tsx
  static/js/publisher/listing/components/PrimaryDomainInput/__tests__/PrimaryDomainInput.test.tsx
Labels: Review: Code +1

#4735 chore: Bump canonicalwebteam.discourse to 5.6.0 and vanilla to 4.14.0
  package.json
  requirements.txt
  templates/_header.html
  yarn.lock
Labels: Review: Code +1, Review: QA +1

#4737 chore: Increase test coverage for libs JS
  static/js/libs/__tests__/events.test.ts
  static/js/libs/colours.js
  static/js/public/search.js
  webpack.config.entry.js
  webpack.config.rules.js
Labels: Review: Code +1

#4738 chore: Bumps canonicalwebteam.discourse version
  requirements.txt
Labels: Review: Code +1

#4739 chore: Increase code coverage in store JS
  package.json
  static/js/store/mocks/index.ts
  static/js/store/mocks/test-categories.ts
  static/js/store/pages/Packages/Packages.tsx
  static/js/store/pages/Packages/__tests__/Packages.test.tsx
  yarn.lock
Labels: Review: Code +1

#4741 chore: Increase code coverage for store JS
  static/js/store/pages/Packages/__tests__/Packages.test.tsx
Labels: Review: Code +1

#4742 chore: Increase code coverage for base JS
  static/js/base/__tests__/ga.test.ts
Labels: Review: Code +1

#4744 fix: Fix remaining JS compiler warnings from TiCS
  static/js/publisher/form.ts
  static/js/publisher/preview.ts
  static/js/publisher/release/components/releasesHeading.js
  static/js/store/pages/Packages/Packages.tsx
Labels: Review: Code +1

#4745 fix: Reduce code duplication
  static/js/brand-store/components/Filter/Filter.tsx
  static/js/brand-store/components/Filter/__tests__/Filter.test.tsx
  static/js/brand-store/components/Filter/index.ts
  static/js/brand-store/components/Model/Policies.tsx
  static/js/brand-store/components/Model/PoliciesFilter.test.tsx
  static/js/brand-store/components/Models/Models.tsx
  static/js/brand-store/components/Models/ModelsFilter.tsx
  static/js/brand-store/components/SigningKeys/SigningKeys.tsx
  static/js/brand-store/components/SigningKeys/SigningKeysFilter.tsx
  static/js/brand-store/utils/getPolicies.ts
  static/js/brand-store/utils/index.ts
  static/js/publisher/form/banner.js
  static/js/publisher/form/icon.js
  static/js/publisher/form/media.js
  static/js/publisher/listing/components/App/App.tsx
  static/js/publisher/settings/components/App/App.tsx
  static/js/publisher/shared/RenderErrors/RenderErrors.tsx
  static/js/publisher/shared/RenderErrors/__tests__/RenderErrors.test.tsx
  static/js/publisher/shared/RenderErrors/index.ts
  static/js/publisher/shared/SaveStateNotifications/SaveStateNotifications.tsx
  static/js/publisher/shared/SaveStateNotifications/__tests__/SaveStateNotifications.test.tsx
  static/js/publisher/shared/SaveStateNotifications/index.ts
Labels: Review: Code +1

#4746 fix: Fix JS compiler warning from TiCS dashboard
  static/js/publisher/settings/components/App/App.tsx
Labels: Review: Code +1

#4748 fix: Fix coding standards warnings from TiCS dashboard
  static/js/brand-store/components/AccountDetails/AccountDetails.tsx
  static/js/brand-store/components/App/App.tsx
  static/js/brand-store/components/AppPagination/AppPagination.tsx
  static/js/brand-store/components/Filter/Filter.tsx
  static/js/brand-store/components/Members/InviteModal.tsx
  static/js/brand-store/components/Members/InvitesTable.tsx
  static/js/brand-store/components/Members/Members.tsx
  static/js/brand-store/components/Members/MembersTable.tsx
  static/js/brand-store/components/Model/CreatePolicyForm.tsx
  static/js/brand-store/components/Model/ModelNav.tsx
  static/js/brand-store/components/Model/Policies.tsx
  static/js/brand-store/components/Model/PoliciesTable.tsx
  static/js/brand-store/components/Models/CreateModelForm.tsx
  static/js/brand-store/components/Models/Models.tsx
  static/js/brand-store/components/Models/ModelsTable.tsx
  static/js/brand-store/components/Navigation/Logo.tsx
  static/js/brand-store/components/Navigation/Navigation.tsx
  static/js/brand-store/components/Publisher/Publisher.tsx
  static/js/brand-store/components/Reviewer/Reviewer.tsx
  static/js/brand-store/components/ReviewerAndPublisher/ReviewerAndPublisher.tsx
  static/js/brand-store/components/Settings/Settings.tsx
  static/js/brand-store/components/SigningKeys/CreateSigningKeyForm.tsx
  static/js/brand-store/components/SigningKeys/DeactivateSigningKeyModal.tsx
  static/js/brand-store/components/SigningKeys/SigningKeys.tsx
  static/js/brand-store/components/SigningKeys/SigningKeysTable.tsx
  static/js/brand-store/components/Snaps/PublishedSnapsTable.tsx
  static/js/brand-store/components/Snaps/Snaps.tsx
  static/js/brand-store/components/Snaps/SnapsFilter.tsx
  static/js/brand-store/components/Snaps/SnapsSearch.tsx
  static/js/brand-store/components/StoreNotFound/StoreNotFound.tsx
Labels: Review: Code +1

#4750 fix: Fix base JS code standard warnings
  static/js/base/dropdown-menu-toggle.ts
  static/js/base/ga.ts
Labels: Review: Code +1

#4751 fix: Fix libs JS coding standards warnings from TiCS
  static/js/libs/debounce.ts
  static/js/libs/iframeSize.ts
  static/js/libs/mobile.ts
Labels: Review: Code +1

#4752 fix: Fix store JS coding standards warnings from TiCS
  static/js/store/components/App/App.tsx
  static/js/store/components/Banner/Banner.tsx
  static/js/store/pages/Packages/Packages.tsx
  static/js/store/utils/getArchitectures.ts
  static/js/store/utils/getCategoryOrder.ts
Labels: Review: Code +1

#4754 fix: sentry - allow all errors
  webapp/handlers.py
Labels: Review: Code +1

#4753 fix: Fix padding issue on brand store status bar
  static/sass/_snapcraft_l-application.scss
Labels: Review: Code +1, Review: QA +1

#4755 fix: Fix base JS coding standards warnings from TiCS dashboard
  static/js/base/ga.ts
Labels: Review: Code needed

#4756 fix: Fix TiCS coding standards warnings in public JS
  static/js/public/about/listing.ts
  static/js/public/accordion.ts
  static/js/public/featured-snaps.ts
  static/js/public/first-snap-flow.ts
  static/js/public/fsf-language-select.ts
  static/js/public/ga-scroll-event.ts
  static/js/public/modal.ts
  static/js/public/nps.ts
Labels: Review: Code +1

#4749 fix: Self-serve track creation bug fixes
  requirements.txt
  static/js/publisher/release/components/releasesHeading.js
  static/js/publisher/release/helpers.test.js
  static/js/publisher/release/helpers.ts
  static/sass/_snapcraft_release.scss
  webapp/publisher/snaps/views.py
Labels: Review: Code +1, Review: UX +1, Review: QA +1

#4757 fix: Fix libs JS coding standards warnings
  static/js/libs/debounce.ts
Labels: Review: Code +1

#4758 fix: Fix store JS coding standards warning
  static/js/store/pages/Packages/Packages.tsx
Labels: Review: Code +1

#4759 fix: FIx coding stanards warnings in public JS
  static/js/public/accordion.ts
  static/js/public/first-snap-flow.ts
  static/js/public/ga-scroll-event.ts
Labels: Review: Code +1

#4760 fix: Fix coding standards warnings in public JS
  static/js/public/snap-details/channelMap.ts
  static/js/public/snap-details/embeddedCard.ts
  static/js/public/snap-details/videos.ts
  static/js/publisher/publicise.ts
Labels: Review: Code needed

#4761 fix: coverage.yml
  .github/workflows/coverage.yml
Labels: Review: Code +1

#4762 fix: fix pagination for featured snaps on snap store
  static/js/store/pages/Packages/Packages.tsx
  static/js/store/pages/Packages/__tests__/Packages.test.tsx
Labels: Review: Code +1, Review: QA +1

#4763 fix: Only show members and settings pages in user has admin role
  static/js/brand-store/components/App/App.tsx
  static/js/brand-store/components/Model/Model.test.tsx
  static/js/brand-store/components/Model/Policies.test.tsx
  static/js/brand-store/components/Navigation/Navigation.tsx
  static/js/brand-store/components/Navigation/__tests__/Navigation.test.tsx
Labels: Review: Code +1, Review: QA +1

#4766 fix: Add types for React
  package.json
  yarn.lock
Labels: Review: Code +1

#4768 fix: Update tsconfig to ignore deprecations
  tsconfig.json
Labels: Review: Code +1

#4771 chore: Convert remaining base js files to ts files
  static/js/base/base.ts
  static/js/base/contactForm.ts
  static/js/base/cookie-policy.ts
  static/js/base/global-nav.ts
  static/js/base/navigation.ts
  static/js/cookie-policy.d.ts
  static/js/global-nav.d.ts
  webpack.config.entry.js
  webpack.config.rules.js
  yarn.lock
Labels: Review: Code +1

#4772 fix: Fix 500 for verify endpoint
  static/js/publisher/listing/components/PrimaryDomainInput/PrimaryDomainInput.tsx
  webapp/store/snap_details_views.py
Labels: Review: Code +1, Review: QA +1

#4773 chore: Convert remaining libs JS to TypeScript
  static/js/libs/__tests__/arrays.test.ts
  static/js/libs/__tests__/events.test.ts
  static/js/libs/__tests__/shallowDiff.test.ts
  static/js/libs/arrays.ts
  static/js/libs/events.ts
  static/js/libs/formHelpers.ts
  static/js/libs/mouse.ts
  static/js/libs/shallowDiff.ts
  static/js/libs/throttle.ts
  static/js/public/snap-details/channelMap.ts
  static/js/publisher/metrics/metrics.ts
Labels: Review: Code +1

#4774 chore: Conver public JS to TypeScript
  package.json
  static/js/public/about/index.ts
  static/js/public/blog.ts
  static/js/public/brand-store.js
  static/js/public/distro-install.ts
  static/js/public/expandable-area.ts
  static/js/public/fsf.ts
  static/js/public/homepage.ts
  static/js/public/newsletter.ts
  static/js/public/publisher-details.ts
  static/js/public/scroll-to.ts
  static/js/public/snap-details/blog-posts.ts
  static/js/public/snap-details/reportSnap.js
  static/js/public/snap-details/reportSnap.ts
  static/js/public/store-details.ts
  webpack.config.entry.js
  webpack.config.rules.js
  yarn.lock
Labels: Review: Code +1

#4775 fix: Fix public JS compiler warnings
  static/js/config/swiper.config.ts
  static/js/public/featured-snaps.ts
  static/js/public/snap-details/reportSnap.ts
  static/js/public/snap-details/screenshots.ts
  templates/store/snap-details.html
Labels: Review: Code +1

#4776 chore: Convert libs JS to TS
  static/js/libs/fileValidation.ts
Labels: Review: Code +1

#4779 chore: update URL for request track to pre-fill new forum request
  static/js/publisher/release/components/releasesHeading.js
Labels: Review: Code +1, Review: QA +1

#4780 chore: Convert publisher JS to TypeScript
  static/js/publisher/build-status.js
  static/js/publisher/build-status.ts
  static/js/publisher/builds/helpers.ts
  static/js/publisher/listing/components/App/App.tsx
  static/js/publisher/publisher.ts
  static/js/publisher/tour.tsx
  static/js/publisher/tour/tour.tsx
  static/js/publisher/tour/tourOverlay.tsx
  webpack.config.entry.js
  webpack.config.rules.js
Labels: Review: Code +1

#4781 chore: Convert publisher tour JS to TypeScript
  static/js/publisher/tour.tsx
  static/js/publisher/tour/__mocks__/constants.ts
  static/js/publisher/tour/constants.ts
  static/js/publisher/tour/helpers.ts
  static/js/publisher/tour/metricsEvents.test.ts
  static/js/publisher/tour/metricsEvents.ts
  static/js/publisher/tour/tour.test.tsx
  static/js/publisher/tour/tour.tsx
  static/js/publisher/tour/tourBar.tsx
  static/js/publisher/tour/tourOverlay.test.tsx
  static/js/publisher/tour/tourOverlay.tsx
  static/js/publisher/tour/tourOverlayMask.tsx
  static/js/publisher/tour/tourStepCard.test.tsx
  static/js/publisher/tour/tourStepCard.tsx
Labels: Review: Code +1

#4782 fix: Update model routes to use account ID
  static/js/brand-store/components/Navigation/Navigation.tsx
Labels: Review: Code +1, Review: QA +1

#4783 fix: Refactor models service to use account ID
  static/js/brand-store/atoms/index.ts
  static/js/brand-store/components/Model/CreatePolicyForm.tsx
  static/js/brand-store/components/Model/Model.tsx
  static/js/brand-store/components/Model/Policies.tsx
  static/js/brand-store/components/Model/PoliciesTable.tsx
  static/js/brand-store/components/Models/CreateModelForm.tsx
  static/js/brand-store/components/Models/Models.tsx
  static/js/brand-store/components/Navigation/Navigation.tsx
  static/js/brand-store/components/SigningKeys/CreateSigningKeyForm.tsx
  static/js/brand-store/components/SigningKeys/SigningKeys.tsx
  static/js/brand-store/components/SigningKeys/SigningKeysTable.tsx
  static/js/brand-store/hooks/index.ts
Labels: Review: Code +1, Review: QA +1

#4787 Convert map JS to TypeScript
  static/js/libs/events.ts
  static/js/public/snap-details/map.ts
Labels: Review: Code +1
