Repository canonical/snapcraft.io, pull requests merged in 2024-01, with the labels that each got.

#4494 Add temp cookie to login
  webapp/login/views.py
  webapp/snapcraft/views.py
Labels: Review: Code +1, Review: QA +1

#4487 Handle categories
  package.json
  static/js/store/components/Packages/Packages.tsx
  yarn.lock
Labels: Review: Code +1, Review: QA +1

#4499 Fix search pagination
  static/js/store/components/Banner/Banner.tsx
Labels: Review: Code +1, Review: QA +1

#4495 update snapcraft docs to new full width vanilla layout
  static/sass/styles.scss
  templates/_base-layout.html
  templates/_docs_layout.html
  templates/_footer.html
  templates/_header.html
  templates/_header_docs_macros.html
  templates/_header_macros.html
  templates/docs/document.html
Labels: Review: Code +1, Review: QA +1, Docs

#4503 Update discourse
  requirements.txt
Labels: Review: Code +1, Review: QA +1

#4504 Update discourse version
  requirements.txt
Labels: Review: Code +1, Review: QA +1

#4505 fix: First login error and loop
  webapp/admin/views.py
  webapp/decorators.py
  webapp/login/views.py
  webapp/snapcraft/views.py
Labels: Review: Code +1, Review: QA +1

#4506 Fix selected brandstore not persisting
  templates/publisher/register-snap.html
Labels: Review: Code +1, Review: QA +1

#4512 feat: update node from 16 to 20
  Dockerfile
Labels: Review: Code +1, Review: QA +1

#4514 feat: bump node in workflow to 20
  .github/workflows/pr.yml
Labels: Review: Code +1

#4515 chore: update canonicalwebteam.launchpad version and humanize version
  requirements.txt
Labels: Review: Code +1

#4516 chore: update react-components
  jest.config.js
  package.json
  yarn.lock
Labels: Review: QA +1, Review: Code +1 (with changes)

#4519 chore: make lint-python use requirements versions
  .github/workflows/pr.yml
  yarn.lock
Labels: Review: Code needed, Review: QA needed
