Repository canonical/snapcraft.io, pull requests merged in 2025-07, with the labels that each got.

#5189 fix: refactor revisions to include releases
  static/js/publisher/pages/Releases/actions/__tests__/defaultTrack.test.js
  static/js/publisher/pages/Releases/actions/__tests__/releases.test.js
  static/js/publisher/pages/Releases/actions/releases.ts
  static/js/publisher/pages/Releases/components/releasesTable/cellViews.js
  static/js/publisher/pages/Releases/components/releasesTable/releaseCell.js
  static/js/publisher/pages/Releases/components/revisionsList.js
  static/js/publisher/pages/Releases/components/revisionsListRow.js
  static/js/publisher/pages/Releases/releasesController.js
  static/js/publisher/pages/Releases/releasesState.js
  static/js/publisher/pages/Releases/selectors/__tests__/selectors.test.js
  static/js/publisher/pages/Releases/selectors/index.ts
  static/js/publisher/test-utils/mockReleasedChannels.ts
  static/js/publisher/test-utils/mockReleases.ts
  static/js/publisher/test-utils/mockReleasesData.ts
  static/js/publisher/test-utils/mockRevisions.ts
  static/js/publisher/test-utils/mockRevisionsMap.ts
Labels: Review: Code +1 (with changes)

#5193 feat: allow progressive rerelease
  static/js/publisher/pages/Releases/actions/pendingReleases.js
  static/js/publisher/pages/Releases/actions/releases.ts
  static/js/publisher/pages/Releases/api/releases.js
  static/js/publisher/pages/Releases/components/releasesTable/cellViews.js
  static/js/publisher/pages/Releases/components/releasesTable/channelHeading.tsx
  static/js/publisher/pages/Releases/components/releasesTable/droppableRow.tsx
  static/js/publisher/pages/Releases/components/releasesTable/row.tsx
  static/js/publisher/pages/Releases/helpers.ts
Labels: Review: Code +1, Review: QA +1

#5196 fix:Added handlers for errors separately
  requirements.txt
  tests/publisher/tests_get_package_metadata.py
  webapp/publisher/snaps/views.py
Labels: Review: Code +1, Review: QA +1

#5199 fix: Fix empty included stores list
  static/js/publisher/pages/Snaps/Snaps.tsx
  static/js/publisher/types/shared.ts
Labels: Review: Code +1, Review: QA +1

#5202 chore: Install Jotai and add Provider
  package.json
  static/js/publisher/brand-store.tsx
  static/js/publisher/publisher.tsx
  yarn.lock
Labels: Review: QA +1, Review: Code +1 (with changes)

#5201 feat: Improved progressive release experience
  static/js/publisher/pages/Releases/actions/__tests__/pendingReleases.test.js
  static/js/publisher/pages/Releases/actions/pendingReleases.js
  static/js/publisher/pages/Releases/components/progressiveBar.js
  static/js/publisher/pages/Releases/components/progressiveBarControl.js
  static/js/publisher/pages/Releases/components/releasesConfirmDetails/cancelProgressiveRow.js
  static/js/publisher/pages/Releases/components/releasesConfirmDetails/index.js
  static/js/publisher/pages/Releases/components/revisionsList.js
  static/js/publisher/pages/Releases/reducers/__tests__/pendingReleases.test.js
  static/js/publisher/pages/Releases/reducers/pendingReleases.ts
  static/js/publisher/pages/Releases/selectors/__tests__/selectors.test.js
  static/js/publisher/pages/Releases/selectors/index.ts
  static/sass/_snapcraft_p-progressive-bar.scss
Labels: Review: Code +1, Review: QA +1

#5209 chore: Convert publisher state from Recoil to Jotai
  static/js/publisher/components/Navigation/Navigation.tsx
  static/js/publisher/pages/AccountDetails/AccountDetails.tsx
  static/js/publisher/pages/AccountDetails/__tests__/AccountDetails.test.tsx
  static/js/publisher/state/publisherState.ts
  static/js/publisher/test-utils/JotaiTestProvider.tsx
  static/js/publisher/test-utils/index.ts
  static/js/publisher/test-utils/publisher-response.ts
Labels: Review: Code needed, Review: QA needed

#5210 chore: Convert builds state from Recoil to Jotai
  static/js/publisher/pages/Builds/Builds.tsx
  static/js/publisher/pages/Builds/DisconnectRepoActions.tsx
  static/js/publisher/pages/Builds/RepoConnected.tsx
  static/js/publisher/pages/Builds/RepoNotConnected.tsx
  static/js/publisher/pages/Builds/RepoSelector.tsx
  static/js/publisher/state/atoms.ts
  static/js/publisher/state/buildsState.ts
Labels: Review: Code +1, Review: QA +1

#5212 chore: Remove remaining traces of Recoil
  package.json
  static/js/publisher/brand-store.tsx
  static/js/publisher/components/Filter/__tests__/Filter.test.tsx
  static/js/publisher/components/PrimaryNav/PrimaryNav.tsx
  static/js/publisher/pages/AccountDetails/__tests__/AccountDetails.test.tsx
  static/js/publisher/pages/BrandStoreSettings/__tests__/BrandStoreSettings.test.tsx
  static/js/publisher/pages/Builds/__tests__/Builds.test.tsx
  static/js/publisher/pages/Members/__tests__/Members.test.tsx
  static/js/publisher/pages/Model/__tests__/CreatePolicyForm.test.tsx
  static/js/publisher/pages/Model/__tests__/Model.test.tsx
  static/js/publisher/pages/Model/__tests__/Policies.test.tsx
  static/js/publisher/pages/Model/__tests__/PoliciesTable.test.tsx
  static/js/publisher/pages/Models/__tests__/CreateModelForm.test.tsx
  static/js/publisher/pages/Models/__tests__/Models.test.tsx
  static/js/publisher/pages/Models/__tests__/ModelsTable.test.tsx
  static/js/publisher/pages/PublisherSettings/__tests__/PublisherSettings.test.tsx
  static/js/publisher/pages/PublisherSettings/__tests__/PublisherSettingsForm.test.tsx
  static/js/publisher/pages/RegisterNameDispute/__tests__/RegisterNameDisputeForm.test.tsx
  static/js/publisher/pages/RegisterSnap/__tests__/RegisterSnap.test.tsx
  static/js/publisher/pages/RequestReservedName/__tests__/RequestReservedName.test.tsx
  static/js/publisher/pages/SigningKeys/__tests__/CreateSigningKeyForm.test.tsx
  static/js/publisher/pages/SigningKeys/__tests__/DeactivateSigningKeyModal.test.tsx
  static/js/publisher/pages/SigningKeys/__tests__/SigningKeys.test.tsx
  static/js/publisher/pages/SigningKeys/__tests__/SigningKeysTable.test.tsx
  static/js/publisher/pages/Snaps/__tests__/Snaps.test.tsx
  static/js/publisher/publisher.tsx
  static/js/publisher/routes/brand-store-root.tsx
  static/js/publisher/test-utils/RecoilObserver.tsx
  static/js/publisher/test-utils/index.ts
  static/js/publisher/utils/getPolicies.ts
  yarn.lock
Labels: Review: Code +1, Review: QA +1

#5214 fix: Fix issue where paginated tables weren't sorting all items
  static/js/publisher/components/AppPagination/AppPagination.tsx
  static/js/publisher/components/AppPagination/index.ts
  static/js/publisher/hooks/index.ts
  static/js/publisher/hooks/useSortTableData.tsx
  static/js/publisher/pages/Model/PoliciesTable.tsx
  static/js/publisher/pages/Models/ModelsTable.tsx
  static/js/publisher/pages/SigningKeys/SigningKeysTable.tsx
  static/js/publisher/pages/SigningKeys/__tests__/SigningKeysTable.test.tsx
  static/sass/styles.scss
Labels: Review: Code +1, Review: QA +1

#5216 chore: Upgrade react-joyride to next version for React 19 upgrade
  package.json
  yarn.lock
Labels: Review: Code +1, Review: QA +1

#5218 WD-23838 - update store_api package
  requirements.txt
Labels: Review: Code +1, Review: QA +1

#5223 Snap details header abstracted to Jinja macros
  templates/partials/_star_developer.html
  templates/partials/_verified_developer.html
  templates/store/_developer_info.jinja
  templates/store/_package_header.jinja
  templates/store/_publisher_info.jinja
  templates/store/_snap-header-developer-information.html
  templates/store/_snap-header-information.html
  templates/store/snap-details.html
  templates/store/snap-details/_package_heading_data.jinja
  templates/store/snap-details/_snap_heading_data.html
  templates/store/snap-distro-install.html
Labels: Review: Code +1, Review: QA +1

#5225 fix: show failed revisions different than empty ones
  static/js/publisher/pages/Releases/actions/__tests__/releases.test.js
  static/js/publisher/pages/Releases/actions/failedRevisions.ts
  static/js/publisher/pages/Releases/actions/releases.ts
  static/js/publisher/pages/Releases/components/releasesTable/cellViews.js
  static/js/publisher/pages/Releases/components/releasesTable/releaseCell.js
  static/js/publisher/pages/Releases/reducers/failedRevisions.ts
  static/js/publisher/pages/Releases/reducers/index.js
  static/js/publisher/pages/Releases/releasesController.js
  static/js/publisher/pages/Releases/releasesState.js
  static/sass/_snapcraft_release.scss
Labels: Review: Code +1, Review: QA +1

#5226 fix: use correct type conversion for None -> bool
  webapp/publisher/snaps/settings_views.py
Labels: Review: Code +1, Review: QA +1

#5230 fix: update react-router-dom version
  package.json
  yarn.lock
Labels: Review: Code +1, Review: QA +1

#5236 fix: prevent path traversal in directory_exists
  tests/tests_helpers.py
  webapp/first_snap/views.py
  webapp/helpers.py
Labels: Review: Code +1, Review: QA +1

#5242 fix:escape version values in select dropdown to prevent xss
  templates/docs/document.html
Labels: Review: Code +1

#5244 chore: Move store endpoint to endpoints section of app
  tests/endpoints/tests_get_store.py
  webapp/admin/views.py
  webapp/endpoints/views.py
Labels: Review: Code +1, Review: QA +1

#5245 fix: deleted a cookie that isnt used
  webapp/login/views.py
Labels: Review: Code +1, Review: QA +1

#5247 fix: avoid exposing internal errors
  webapp/publisher/snaps/release_views.py
  webapp/publisher/snaps/views.py
Labels: Review: Code needed

#5248 chore: Move models endpoint to the endpoints section of app
  tests/admin/tests_models.py
  tests/endpoints/tests_models.py
  tests/endpoints/tests_signing_keys.py
  webapp/admin/views.py
  webapp/app.py
  webapp/endpoints/models.py
Labels: Review: Code +1, Review: QA +1

#5250 fix: reduce GITHUB_TOKEN scope for the jobs
  .github/workflows/coverage.yml
  .github/workflows/pr.yml
Labels: Review: Code +1, Review: QA +1
