Repository canonical/snapcraft.io, pull requests merged in 2025-02, with the labels that each got.

#5006 fix: use orgs github name to connect them to github
  static/js/publisher/pages/Builds/RepoSelector.tsx
  static/js/publisher/types/index.ts
Labels: Review: Code +1

#5009 chore: Refactor in preparation for explore page
  static/js/store/components/App/App.tsx
  static/js/store/components/App/index.ts
  static/js/store/components/EmptyResultSection/EmptyResultSection.tsx
  static/js/store/components/EmptyResultSection/index.ts
  static/js/store/components/PackageFilter/PackageFilter.tsx
  static/js/store/components/PackageList/PackageList.tsx
  static/js/store/hooks/index.ts
  static/js/store/hooks/usePackages.ts
  static/js/store/index.tsx
  static/js/store/layouts/Root.tsx
  static/js/store/pages/Packages/Packages.tsx
  static/js/store/pages/Packages/index.ts
  static/js/store/pages/Store/Store.tsx
  static/js/store/pages/Store/__tests__/Store.test.tsx
  static/js/store/pages/Store/index.ts
  static/js/store/types/Category.ts
  static/js/store/types/Package.ts
  static/js/store/types/Packages.ts
  static/js/store/types/components/Category.d.ts
  static/js/store/types/index.d.ts
  static/js/store/types/index.ts
Labels: Review: Code +1, Review: QA +1

#5007 Clean custom styling related to closed Vanilla issues
  static/js/publisher/pages/Builds/LoggedOut.tsx
  static/sass/_patterns_first-snap-flow.scss
  static/sass/_snapcraft_p-navigation.scss
  static/sass/_snapcraft_release.scss
  static/sass/styles-embedded.scss
  static/sass/styles.scss
  templates/_header.html
  templates/partials/_snap-details-video-layout.html
Labels: Review: Code +1, Review: QA +1

#5010 Add error message and code
  webapp/publisher/snaps/build_views.py
Labels: Review: Code +1

#5011 fix parameter that is sent to build endpoint
  static/js/publisher/pages/Builds/RepoSelector.tsx
Labels: Review: Code +1

#5012 chore: Remove old Vanilla 2.0 related workarounds
  static/sass/_patterns_logo-links.scss
  static/sass/_snapcraft_release.scss
  static/sass/_utilities_flex.scss
  static/sass/styles.scss
  templates/first-snap/install-snapcraft.html
  templates/publisher/_header.html
  templates/publisher/_noscript.html
Labels: Review: Code +1, Review: QA +1

#5013 chore: Clean-up button style overrides
  static/sass/_button-overrides.scss
  static/sass/_pattern_p-button-group.scss
  static/sass/_patterns_button_spinner.scss
  static/sass/_patterns_carousel.scss
  static/sass/_patterns_maas_modal.scss
  static/sass/styles.scss
  templates/first-snap/upload.html
  templates/publisher/_repo-disconnect-modal.html
Labels: Review: Code +1, Review: QA +1

#5015 chore: Clean custom icons
  static/js/publisher/components/Navigation/Navigation.tsx
  static/js/publisher/components/PrimaryNav/PrimaryNav.tsx
  static/js/publisher/components/Tour/TourStep.tsx
  static/sass/_patterns_icons.scss
  static/sass/_snapcraft_l-application.scss
  static/sass/_snapcraft_market.scss
  static/sass/_snapcraft_p-build.scss
  static/sass/_snapcraft_patterns_icons.scss
  static/sass/_snapcraft_release.scss
  static/sass/_snapcraft_store.scss
  static/sass/_snapcraft_tour.scss
  static/sass/styles.scss
Labels: Review: Code +1, Review: QA +1

#5019 fix: Update mattermost icon on snapcrafters publisher page
  webapp/store/content/publishers/snapcrafters-snaps.yaml
Labels: Review: Code +1, Review: QA +1

#5023 chore: Change icon in brand stores navigation
  static/js/publisher/components/Navigation/Navigation.tsx
  static/sass/styles.scss
Labels: Review: Code +1, Review: QA +1

#5020 Cleaning up some remains of Vanilla overrides
  static/js/base/ga.ts
  static/sass/_patterns_sticky_footer.scss
  static/sass/_patterns_strip_slanted.scss
  static/sass/_snapcraft_p-form-validation.scss
  static/sass/_utilities_margin-sizing.scss
  static/sass/_utilities_no-limit.scss
  static/sass/styles.scss
  templates/_base-layout.html
  templates/_footer.html
  templates/first-snap/_install-linux.html
  templates/first-snap/_install-macos.html
  templates/first-snap/_install-windows.html
  templates/first-snap/build-and-test.html
  templates/publisher/register-snap.html
Labels: Review: Code +1, Review: QA +1

#5024 fix: snapcrafters icons
  webapp/store/content/publishers/snapcrafters-snaps.yaml
Labels: Review: Code +1, Review: QA +1

#5025 fix: Fix listing preview issues
  static/js/publisher/pages/Listing/ListingForm/ListingForm.tsx
  static/js/publisher/pages/Listing/PreviewForm/PreviewForm.tsx
  templates/store/snap-details.html
  tests/publisher/snaps/test_post_preview.py
  webapp/publisher/snaps/listing_views.py
Labels: Review: Code +1, Review: QA +1

#5017 CVE API implementation
  HACKING.md
  tests/publisher/cve/__init__.py
  tests/publisher/cve/test_cve_filter_data.py
  tests/publisher/cve/test_cve_get_by_revision.py
  tests/publisher/cve/test_cve_paginate_data.py
  tests/publisher/cve/test_cve_sort_data.py
  tests/publisher/cve/test_cve_user_access.py
  webapp/publisher/cve/cve_helper.py
  webapp/publisher/cve/cve_views.py
  webapp/publisher/snaps/views.py
Labels: Review: Code +1, Review: QA +1

#5026 chore: Add tests for publisher build page
  static/js/publisher/pages/Build/__tests__/Build.test.tsx
Labels: Review: Code +1, Review: QA +1

#5027 chore: Add tests for publisher builds page
  jest.config.js
  package.json
  static/js/publisher/pages/Builds/__tests__/Builds.test.tsx
  yarn.lock
Labels: Review: Code +1, Review: QA +1

#5028 chore: Add tests to brand store snaps
  static/js/publisher/pages/Snaps/SnapsFilter.tsx
  static/js/publisher/pages/Snaps/__tests__/Snaps.test.tsx
  static/js/publisher/test-utils/RecoilObserver.tsx
  static/js/publisher/test-utils/brand-store-requests.ts
  static/js/publisher/test-utils/brand-store-responses.ts
  static/js/publisher/test-utils/index.ts
  static/js/publisher/types/shared.ts
Labels: Review: Code needed, Review: QA needed

#5029 chore: Add tests for publisher listing page
  static/js/publisher/pages/Listing/ListingDetails/ImageUpload.tsx
  static/js/publisher/pages/Listing/ListingDetails/ListingDetails.tsx
  static/js/publisher/pages/Listing/__tests__/Listing.test.tsx
Labels: Review: Code +1, Review: QA +1

#5033 chore: Add validation sets link to brand store nav
  static/js/base/navigation.ts
  static/js/publisher/components/Navigation/Navigation.tsx
  static/js/publisher/components/PrimaryNav/PrimaryNav.tsx
  templates/_header.html
  webapp/login/views.py
Labels: Review: Code +1, Review: QA +1

#5035 chore: Add store selector to publisher pages
  static/js/publisher/components/Navigation/Navigation.tsx
  static/js/publisher/components/PrimaryNav/PrimaryNav.tsx
  static/js/publisher/components/StoreSelector/StoreSelector.tsx
  static/js/publisher/components/StoreSelector/index.ts
Labels: Review: Code +1, Review: UX +1, Review: QA +1

#5036 chore: Move publisher snaps to application layout
  static/js/publisher/components/EmptySnapList/EmptySnapList.tsx
  static/js/publisher/components/EmptySnapList/index.ts
  static/js/publisher/components/NewSnapNotification/NewSnapNotification.tsx
  static/js/publisher/components/NewSnapNotification/index.ts
  static/js/publisher/components/PrimaryNav/PrimaryNav.tsx
  static/js/publisher/components/PublishedSnapList/PublishedSnapList.tsx
  static/js/publisher/components/PublishedSnapList/SnapNameEntry.tsx
  static/js/publisher/components/PublishedSnapList/__tests__/PublishedSnapList.test.tsx
  static/js/publisher/components/PublishedSnapList/index.ts
  static/js/publisher/components/PublishedSnapSection/PublishedSnapSection.tsx
  static/js/publisher/components/PublishedSnapSection/__tests__/PublishedSnapSection.test.tsx
  static/js/publisher/components/PublishedSnapSection/index.ts
  static/js/publisher/components/PublisherMetrics/PublisherMetrics.tsx
  static/js/publisher/components/PublisherMetrics/index.ts
  static/js/publisher/components/RegisteredSnaps/RegisteredSnaps.tsx
  static/js/publisher/components/RegisteredSnaps/__tests__/RegisteredSnaps.test.tsx
  static/js/publisher/components/RegisteredSnaps/index.ts
  static/js/publisher/hooks/__tests__/useFetchAccountSnaps.test.ts
  static/js/publisher/hooks/__tests__/useFetchPublishedSnapMetrics.test.tsx
  static/js/publisher/hooks/index.ts
  static/js/publisher/hooks/useFetchAccountSnaps.ts
  static/js/publisher/hooks/useFetchPublishedSnapMetrics.ts
  static/js/publisher/pages/AccountSnaps/AccountSnaps.tsx
  static/js/publisher/pages/AccountSnaps/__tests__/AccountSnaps.test.tsx
  static/js/publisher/pages/AccountSnaps/index.ts
  static/js/publisher/publisher.tsx
  static/js/publisher/types/constants.ts
  static/js/publisher/types/index.ts
  static/js/snap-pages/hooks/index.ts
  static/js/snap-pages/index.tsx
  static/js/snap-pages/routes/root.tsx
  static/js/snap-pages/types/index.d.ts
  templates/publisher/account-snaps.html
  tests/publisher/tests_account_snaps.py
  webapp/publisher/snaps/views.py
  webpack.config.entry.js
Labels: Review: QA +1, Review: UX -1, Review: Code +1 (with changes)

#5039 fix: Remove unused metrics template
  templates/publisher/metrics.html
Labels: Review: Code +1

#5041 fix: Fix register snap link
  static/js/publisher/components/PublishedSnapList/PublishedSnapList.tsx
Labels: Review: Code +1, Review: QA +1

#5040 chore: Update design of published snaps page
  static/js/publisher/components/PublishedSnapList/PublishedSnapList.tsx
  static/js/publisher/components/PublishedSnapSection/PublishedSnapSection.tsx
  static/js/publisher/components/PublisherMetrics/PublisherMetrics.tsx
  static/js/publisher/components/RegisteredSnaps/RegisteredSnaps.tsx
  static/js/publisher/pages/AccountSnaps/AccountSnaps.tsx
  static/js/publisher/pages/Snaps/Snaps.tsx
  static/sass/_snapcraft_metrics.scss
  static/sass/styles.scss
Labels: Review: Code +1, Review: UX +1, Review: QA +1
