Repository canonical/snapcraft.io, pull requests merged in 2025-09, with the labels that each got.

#5339 fix Cypress test timeouts in GH action
  cypress.config.ts
Labels: Review: Code +1, Review: QA +1

#5331 feature: Vite dev server integration (part 1)
  .env
  tests/tests_vite_integration.py
  vite.config.js
  webapp/config.py
  webapp/handlers.py
  webapp/template_utils.py
  webapp/vite_integration/__init__.py
  webapp/vite_integration/exceptions.py
  webapp/vite_integration/impl/__init__.py
  webapp/vite_integration/impl/base.py
  webapp/vite_integration/impl/dev.py
  webapp/vite_integration/impl/prod.py
  webapp/vite_integration/types.py
Labels: Review: Code +1

#5345 fix: add DASHBOARD_API_URL env var for auth on staging-api env
  konf/staging-api.snapcraft.io.yaml
Labels: Review: Code +1, Review: QA +1

#5349 feature: Vite dev server integration (part 3)
  Dockerfile
  package.json
  templates/_base-layout.html
  templates/_layout-embedded.html
  tests/tests_vite_integration.py
  vite.config.js
  webapp/handlers.py
  webapp/template_utils.py
  webapp/vite_integration/impl/base.py
  webapp/vite_integration/impl/dev.py
  webapp/vite_integration/impl/prod.py
Labels: Review: Code +1, Review: QA +1

#5355 fix: improve variable names
  webapp/vite_integration/impl/prod.py
Labels: Review: Code +1

#5357 WD-24362 - Fix test so that it works offline
  tests/store/tests_publisher.py
Labels: Review: Code +1, Review: QA +1

#5358 chore: cleanup package.json
  package.json
  static/js/public/first-snap-flow.ts
  yarn.lock
Labels: Review: Code +1, Review: QA +1

#5379 fix: Fix footer position on docs page
  static/sass/_snapcraft_p-docs.scss
Labels: Review: Code +1, Review: QA +1

#5377 fix: Fix template link on builds page
  static/js/publisher/pages/Builds/RepoSelector.tsx
  webapp/endpoints/publisher/builds.py
Labels: Review: Code needed, Review: QA needed

#5389 WD-27333 - Fix bug in docs global navigation
  templates/_base-layout.html
  templates/_docs_layout.html
  templates/_header_docs_macros.html
  templates/_header_macros.html
Labels: Review: Code +1, Review: QA +1

#5347 feat(github): Autofill repository name when setting up GitHub builds
  static/js/publisher/pages/Builds/RepoSelector.tsx
  static/js/publisher/pages/Builds/__tests__/RepoSelector.test.tsx
Labels: Review: QA +1, Review: Code +1 (with changes)

#5392 fix: use correct dashboard env var name
  HACKING.md
  konf/staging-api.snapcraft.io.yaml
  requirements.txt
Labels: Review: Code +1

#5393 refactor(code): update validateRepo function name
  static/js/publisher/pages/Builds/RepoSelector.tsx
Labels: Review: Code +1, Review: QA +1
