Repository canonical/snapcraft.io, pull requests merged in 2025-05, with the labels that each got.

#5120 chore: Add tests for publisher metrics
  static/js/publisher/pages/Metrics/ActiveDeviceMetricFilter.tsx
  static/js/publisher/pages/Metrics/__tests__/ActiveDeviceMetrics.test.tsx
  static/js/publisher/pages/Metrics/__tests__/Metrics.test.tsx
  static/js/publisher/pages/Metrics/__tests__/TerritoryMetrics.test.tsx
  static/js/publisher/test-utils/index.ts
  static/js/publisher/test-utils/mockActiveDeviceMetrics.ts
  static/js/publisher/test-utils/mockTerritoryMetrics.ts
Labels: Review: Code +1, Review: QA +1

#5121 refactor(home): remove blog posts from homepage
  package.json
  templates/index.html
  yarn.lock
Labels: Review: Code +1, Review: QA +1

#5122 fix: remove skype image from homepage
  templates/index.html
Labels: Review: Code +1, Review: QA +1

#5123 chore: Move releases tests to test directories
  static/js/publisher/pages/Releases/__tests__/helpers.test.js
  static/js/publisher/pages/Releases/actions/__tests__/architectures.test.js
  static/js/publisher/pages/Releases/actions/__tests__/availableRevisionsSelect.test.js
  static/js/publisher/pages/Releases/actions/__tests__/branches.test.js
  static/js/publisher/pages/Releases/actions/__tests__/channelMap.test.js
  static/js/publisher/pages/Releases/actions/__tests__/currentTrack.test.js
  static/js/publisher/pages/Releases/actions/__tests__/defaultTrack.test.js
  static/js/publisher/pages/Releases/actions/__tests__/gaEventTracking.test.js
  static/js/publisher/pages/Releases/actions/__tests__/globalNotification.test.js
  static/js/publisher/pages/Releases/actions/__tests__/history.test.js
  static/js/publisher/pages/Releases/actions/__tests__/modal.test.js
  static/js/publisher/pages/Releases/actions/__tests__/pendingCloses.test.js
  static/js/publisher/pages/Releases/actions/__tests__/pendingReleases.test.js
  static/js/publisher/pages/Releases/actions/__tests__/releases.test.js
  static/js/publisher/pages/Releases/actions/__tests__/revisions.test.js
  static/js/publisher/pages/Releases/reducers/__tests__/architectures.test.js
  static/js/publisher/pages/Releases/reducers/__tests__/availableRevisionsSelect.test.js
  static/js/publisher/pages/Releases/reducers/__tests__/branches.test.js
  static/js/publisher/pages/Releases/reducers/__tests__/channelMap.test.js
  static/js/publisher/pages/Releases/reducers/__tests__/currentTrack.test.js
  static/js/publisher/pages/Releases/reducers/__tests__/defaultTrack.test.js
  static/js/publisher/pages/Releases/reducers/__tests__/globalNotification.test.js
  static/js/publisher/pages/Releases/reducers/__tests__/history.test.js
  static/js/publisher/pages/Releases/reducers/__tests__/modal.test.js
  static/js/publisher/pages/Releases/reducers/__tests__/pendingCloses.test.js
  static/js/publisher/pages/Releases/reducers/__tests__/pendingReleases.test.js
  static/js/publisher/pages/Releases/reducers/__tests__/releases.test.js
  static/js/publisher/pages/Releases/reducers/__tests__/revisions.test.js
  static/js/publisher/pages/Releases/selectors/__tests__/selectors.test.js
Labels: Review: Code +1, Review: QA +1

#5124 chore: Add tests for publishers releases
  static/js/publisher/pages/Releases/__tests__/releasesState.test.js
  static/js/publisher/pages/Releases/components/__tests__/TrackInfo.test.tsx
  static/js/publisher/test-utils/index.ts
  static/js/publisher/test-utils/mockReleasedChannels.ts
  static/js/publisher/test-utils/mockReleases.ts
  static/js/publisher/test-utils/mockReleasesData.ts
  static/js/publisher/test-utils/mockRevisions.ts
  static/js/publisher/test-utils/mockRevisionsMap.ts
Labels: Review: Code +1, Review: QA +1

#5129 fix: Add lodash to resolutions to fix security patch
  package.json
  yarn.lock
Labels: Review: Code +1

#5131 fix: Update lodash version in resolutions
  package.json
  yarn.lock
Labels: Review: Code +1

#5134 add documentation.ubuntu.com/snapcraft redirects
  redirects.yaml
Labels: Review: Code +1, Review: QA +1, Don't merge

#5136 Wd 18956/stores filter
  static/js/publisher/components/StoreSelector/StoreSelector.tsx
  static/sass/_snapcraft_l-application.scss
Labels: Review: Code +1, Review: QA +1

#5137 fix: Fix instructions for installing dotrun
  README.md
Labels: Review: Code +1

#5138 update new redirects to include `/?`
  redirects.yaml
Labels: Review: Code +1, Review: QA +1

#5140 reorder redirects that are not working in prod
  redirects.yaml
Labels: Review: Code +1

#5118 WD-21811 - snap icon causes Internal Server Error
  static/js/publisher/pages/Listing/AdditionalInformation/__tests__/AdditionalInformation.test.tsx
  static/js/publisher/pages/Listing/AdditionalInformation/__tests__/LicenseInputs.test.tsx
  static/js/publisher/pages/Listing/AdditionalInformation/__tests__/LicenseSearch.test.tsx
  static/js/publisher/pages/Listing/ContactInformation/ContactFields.tsx
  static/js/publisher/pages/Listing/ContactInformation/__tests__/ContactFields.test.tsx
  static/js/publisher/pages/Listing/ContactInformation/__tests__/ContactInformation.test.tsx
  static/js/publisher/pages/Listing/ListingDetails/ListingDetails.tsx
  static/js/publisher/pages/Listing/ListingDetails/__tests__/ImageUpload.test.tsx
  static/js/publisher/pages/Listing/ListingDetails/__tests__/ListingDetails.test.tsx
  static/js/publisher/pages/Listing/ListingForm/ListingForm.tsx
  static/js/publisher/pages/Listing/ListingForm/__tests__/ListingForm.test.tsx
  static/js/publisher/pages/Listing/PreviewForm/PreviewForm.tsx
  static/js/publisher/pages/Listing/PreviewForm/__tests__/PreviewForm.test.tsx
  static/js/publisher/pages/Listing/__tests__/Listing.test.tsx
  static/js/publisher/test-utils/mockListingData.ts
  templates/store/snap-details/_snap_heading_data.html
  webapp/publisher/snaps/logic.py
Labels: Review: Code +1, Review: QA +1

#5144 remove trailing slash from broken redirects
  redirects.yaml
Labels: Review: Code +1

#5153 fix: Fix releases data disappearing on second mount
  static/js/publisher/publisher.tsx
Labels: Review: Code needed, Review: QA needed
