Repository canonical/snapcraft.io, pull requests merged in 2025-01, with the labels that each got.

#4964 Fix eslint and jest tests
  .eslintignore
  .eslintrc.js
  eslint.config.mjs
  jest.config.js
  jest.setup.js
  package.json
  static/js/brand-store/slices/brandStoreSlice.ts
  static/js/brand-store/slices/currentStoreSlice.ts
  static/js/brand-store/slices/invitesSlice.ts
  static/js/public/first-snap-flow.ts
  static/js/public/snap-details/lightbox.ts
  static/js/public/snap-details/reportSnap.ts
  static/js/publisher-pages/pages/Listing/ContactInformation/PrimaryDomainInput.tsx
  static/js/publisher-pages/pages/Metrics/ActiveDeviceMetrics.tsx
  static/js/publisher-pages/pages/Metrics/TerritoryMetrics.tsx
  static/sass/_patterns_logo-links.scss
  static/sass/_snapcraft_release.scss
  yarn.lock
Labels: Review: Code +1, Review: QA +1

#4961 chore: Change URL format for brand store API
  static/js/brand-store/components/Members/InvitesTable.tsx
  static/js/brand-store/components/Members/Members.tsx
  static/js/brand-store/components/Model/CreatePolicyForm.tsx
  static/js/brand-store/components/Model/Model.tsx
  static/js/brand-store/components/Model/PoliciesTable.tsx
  static/js/brand-store/components/Models/CreateModelForm.tsx
  static/js/brand-store/components/Settings/Settings.tsx
  static/js/brand-store/components/SigningKeys/CreateSigningKeyForm.tsx
  static/js/brand-store/components/SigningKeys/SigningKeysTable.tsx
  static/js/brand-store/components/Snaps/Snaps.tsx
  static/js/brand-store/hooks/index.ts
  static/js/brand-store/slices/brandStoreSlice.ts
  static/js/brand-store/slices/currentStoreSlice.ts
  static/js/brand-store/slices/invitesSlice.ts
  static/js/brand-store/slices/membersSlice.ts
  static/js/brand-store/slices/snapsSlice.ts
  static/js/brand-store/utils/getPolicies.ts
  tests/admin/test_brand_store.py
  tests/admin/tests_models.py
  tests/admin/tests_policies.py
  tests/admin/tests_signing_keys.py
  webapp/admin/views.py
Labels: Review: Code +1, Review: QA +1

#4969 fix python lint and test jobs
  .github/workflows/pr.yml
  package.json
  webapp/api/github.py
Labels: Review: Code +1, Review: QA +1

#4959 feat: migrate snaps page to react
  static/js/publisher-pages/pages/Metrics/metrics/metrics.ts
  static/js/snap-pages/components/EmptySnapList/EmptySnapList.tsx
  static/js/snap-pages/components/EmptySnapList/index.ts
  static/js/snap-pages/components/NewSnapNotification/NewSnapNotification.tsx
  static/js/snap-pages/components/NewSnapNotification/index.ts
  static/js/snap-pages/components/PublishedSnapList/PublishedSnapList.tsx
  static/js/snap-pages/components/PublishedSnapList/SnapNameEntry.tsx
  static/js/snap-pages/components/PublishedSnapList/__tests__/PublishedSnapList.test.tsx
  static/js/snap-pages/components/PublishedSnapList/index.ts
  static/js/snap-pages/components/PublishedSnapSection/PublishedSnapSection.tsx
  static/js/snap-pages/components/PublishedSnapSection/__tests__/PublishedSnapSection.test.tsx
  static/js/snap-pages/components/PublishedSnapSection/index.ts
  static/js/snap-pages/components/PublisherMetrics/PublisherMetrics.tsx
  static/js/snap-pages/components/PublisherMetrics/index.ts
  static/js/snap-pages/components/RegisteredSnaps/RegisteredSnaps.tsx
  static/js/snap-pages/components/RegisteredSnaps/__tests__/RegisteredSnaps.test.tsx
  static/js/snap-pages/components/RegisteredSnaps/index.ts
  static/js/snap-pages/hooks/__tests__/useFetchAccountSnaps.test.ts
  static/js/snap-pages/hooks/__tests__/useFetchPublishedSnapMetrics.test.tsx
  static/js/snap-pages/hooks/index.ts
  static/js/snap-pages/hooks/useFetchAccountSnaps.ts
  static/js/snap-pages/hooks/useFetchPublishedSnapMetrics.ts
  static/js/snap-pages/index.tsx
  static/js/snap-pages/pages/AccountSnaps/AccountSnaps.tsx
  static/js/snap-pages/pages/AccountSnaps/__tests__/AccountSnaps.test.tsx
  static/js/snap-pages/pages/AccountSnaps/index.ts
  static/js/snap-pages/routes/root.tsx
  static/js/snap-pages/types/constants.ts
  static/js/snap-pages/types/index.d.ts
  static/sass/_snapcraft_metrics.scss
  static/sass/_snapcraft_p-snap-list.scss
  static/sass/styles.scss
  templates/publisher/account-snaps.html
  tests/publisher/tests_account_snaps.py
  webapp/publisher/snaps/views.py
  webpack.config.entry.js
Labels: Review: Code +1, Review: QA +1

#4973 fix: Fix bug where snaps weren't loading when adding to store
  static/js/brand-store/pages/Snaps/SnapsSearch.tsx
Labels: Review: Code +1, Review: QA +1

#4972 chore: Refactor brand store state management
  static/js/brand-store/components/Navigation/Navigation.tsx
  static/js/brand-store/pages/AccountDetails/AccountDetails.tsx
  static/js/brand-store/pages/AccountDetails/__tests__/AccountDetails.test.tsx
  static/js/brand-store/pages/Model/CreatePolicyForm.tsx
  static/js/brand-store/pages/Model/Model.tsx
  static/js/brand-store/pages/Model/Policies.tsx
  static/js/brand-store/pages/Model/PoliciesTable.tsx
  static/js/brand-store/pages/Models/CreateModelForm.tsx
  static/js/brand-store/pages/Models/Models.tsx
  static/js/brand-store/pages/Models/ModelsTable.tsx
  static/js/brand-store/pages/SigningKeys/CreateSigningKeyForm.tsx
  static/js/brand-store/pages/SigningKeys/SigningKeys.tsx
  static/js/brand-store/pages/SigningKeys/SigningKeysTable.tsx
  static/js/brand-store/routes/App/App.tsx
  static/js/brand-store/state/atoms/index.ts
  static/js/brand-store/state/brandStoreState.ts
  static/js/brand-store/state/modelsState.ts
  static/js/brand-store/state/policiesState.ts
  static/js/brand-store/state/publisherState.ts
  static/js/brand-store/state/selectors/index.ts
  static/js/brand-store/state/signingKeysState.ts
  static/js/brand-store/utils/getFilteredModels.test.ts
  static/js/brand-store/utils/getFilteredModels.ts
  static/js/brand-store/utils/getFilteredPolicies.test.ts
  static/js/brand-store/utils/getFilteredPolicies.ts
  static/js/brand-store/utils/getFilteredSigningKeys.test.ts
  static/js/brand-store/utils/getFilteredSigningKeys.ts
  static/js/brand-store/utils/index.ts
Labels: Review: Code +1, Review: QA +1

#4974 Github integration issue - Part 1
  webapp/api/github.py
Labels: Review: Code +1

#4976 chore: Remove RTK from brand store settings
  static/js/brand-store/pages/Settings/Settings.tsx
  static/js/brand-store/pages/Settings/__tests__/Settings.test.tsx
Labels: Review: Code +1, Review: QA +1

#4979 fix: Fix metrics view
  webapp/publisher/snaps/metrics_views.py
Labels: Review: Code +1, Review: QA +1

#4978 chore: Remove RTK from stores navigation
  static/js/brand-store/brand-store.tsx
  static/js/brand-store/components/Navigation/Navigation.tsx
  static/js/brand-store/components/Navigation/__tests__/Navigation.test.tsx
  static/js/brand-store/hooks/index.ts
  static/js/brand-store/hooks/useBrandStores.tsx
  static/js/brand-store/pages/Snaps/Snaps.tsx
  static/js/brand-store/routes/App/App.tsx
Labels: Review: Code +1, Review: QA +1

#4980 chore: Remove RTK from brand store snaps
  static/js/brand-store/hooks/index.ts
  static/js/brand-store/hooks/useBrandStores.ts
  static/js/brand-store/hooks/useMembers.ts
  static/js/brand-store/hooks/useSnaps.ts
  static/js/brand-store/pages/Snaps/Snaps.tsx
Labels: Review: Code +1, Review: QA +1

#4982 chore: Remove Redux Toolkit from the brand store
  package.json
  static/js/brand-store/brand-store.tsx
  static/js/brand-store/hooks/index.ts
  static/js/brand-store/pages/AccountDetails/__tests__/AccountDetails.test.tsx
  static/js/brand-store/pages/Model/__tests__/Model.test.tsx
  static/js/brand-store/pages/Model/__tests__/Policies.test.tsx
  static/js/brand-store/pages/Models/__tests__/Models.test.tsx
  static/js/brand-store/state/selectors/index.ts
  static/js/brand-store/state/slices/brandStoreSlice.ts
  static/js/brand-store/state/slices/currentStoreSlice.ts
  static/js/brand-store/state/slices/invitesSlice.ts
  static/js/brand-store/state/slices/membersSlice.ts
  static/js/brand-store/state/slices/snapsSlice.ts
  static/js/brand-store/state/store/index.ts
  static/js/brand-store/types/shared.ts
  yarn.lock
Labels: Review: Code +1, Review: QA +1

#4984 chore: Rename publisher and brand store settings components
  static/js/brand-store/pages/BrandStoreSettings/BrandStoreSettings.tsx
  static/js/brand-store/pages/BrandStoreSettings/index.ts
  static/js/brand-store/pages/Settings/index.ts
  static/js/brand-store/routes/App/App.tsx
  static/js/publisher/index.tsx
  static/js/publisher/pages/PublisherSettings/PublisherSettings.tsx
  static/js/publisher/pages/PublisherSettings/PublisherSettingsForm.tsx
  static/js/publisher/pages/PublisherSettings/UnregisterSnapModal.tsx
  static/js/publisher/pages/PublisherSettings/__tests__/UnregisterSnapModal.test.tsx
  static/js/publisher/pages/PublisherSettings/index.ts
  static/js/publisher/pages/Settings/index.ts
Labels: Review: Code needed, Review: QA needed

#4988 Fix (or silence) Sass warnings
  package.json
  static/sass/_patterns_first-snap-flow.scss
  static/sass/_snapcraft_p-build.scss
  static/sass/_snapcraft_p-progressive-bar.scss
  static/sass/styles.scss
  webpack.config.rules.js
Labels: Review: Code +1, Review: QA +1

#4991 chore: Add tests for brand store settings page
  package.json
  static/js/publisher/hooks/__tests__/useActiveDeviceMetrics.test.tsx
  static/js/publisher/pages/BrandStoreSettings/BrandStoreSettings.tsx
  static/js/publisher/pages/BrandStoreSettings/__tests__/BrandStoreSettings.test.tsx
  yarn.lock
Labels: Review: Code +1, Review: QA +1

#4997 fix: Fix issue with metrics endpoints returning 404
  tests/publisher/snaps/tests_get_metrics.py
  webapp/publisher/snaps/metrics_views.py
Labels: Review: Code +1, Review: QA +1

#4998 fix: Make publisher pages 404 with no permissions
  webapp/publisher/snaps/build_views.py
  webapp/publisher/snaps/metrics_views.py
  webapp/publisher/snaps/publicise_views.py
  webapp/publisher/snaps/release_views.py
Labels: Review: Code +1, Review: QA +1

#4999 chore: Add relevant page titles to snap publisher pages
  static/js/publisher/pages/Build/Build.tsx
  static/js/publisher/pages/Builds/Builds.tsx
  static/js/publisher/pages/Listing/Listing.tsx
  static/js/publisher/pages/Metrics/Metrics.tsx
  static/js/publisher/pages/Publicise/Publicise.tsx
  static/js/publisher/pages/PublisherSettings/PublisherSettings.tsx
  static/js/publisher/pages/Releases/Releases.tsx
Labels: Review: Code +1, Review: QA +1

#5001 chore: Add tests to publisher utils
  static/js/publisher/utils/__tests__/getSettingsFormData.test.ts
  static/js/publisher/utils/__tests__/setPageTitle.test.ts
Labels: Review: Code needed

#5000 Fix top navigation alignment
  package.json
  static/js/base/global-nav.ts
  static/sass/styles.scss
  templates/_header.html
  yarn.lock
Labels: Review: Code +1, Review: QA +1

#5002 Update yarn.lock
  yarn.lock
Labels: Review: Code +1

#5003 chore: Add tests for publisher hooks
  static/js/publisher/hooks/__tests__/useBrandStores.test.ts
  static/js/publisher/hooks/__tests__/useInvites.test.tsx
  static/js/publisher/hooks/__tests__/useLatestActiveDevicesMetric.test.ts
  static/js/publisher/hooks/__tests__/useMembers.test.ts
  static/js/publisher/hooks/__tests__/useSnaps.test.ts
Labels: Review: Code +1, Review: QA +1
