Repository canonical/snapcraft.io, pull requests merged in 2025-04, with the labels that each got.

#5072 chore: Remove links from registered snap names list
  static/js/publisher/components/RegisteredSnaps/RegisteredSnaps.tsx
Labels: Review: Code +1, Review: QA +1

#5064 chore: Apply application layout to register snap page
  static/js/publisher/pages/Listing/Listing.tsx
  static/js/publisher/pages/RegisterSnap/RegisterSnap.tsx
  static/js/publisher/pages/RegisterSnap/RegisterSnapForm.tsx
  static/js/publisher/pages/RegisterSnap/RegistrationError.tsx
  static/js/publisher/pages/RegisterSnap/__tests__/RegisterSnap.test.tsx
  static/js/publisher/pages/RegisterSnap/index.ts
  static/js/publisher/pages/RegisterSnap/local-types.ts
  static/js/publisher/pages/RequestReservedName/RequestReservedName.tsx
  static/js/publisher/publisher.tsx
  static/js/publisher/types/shared.ts
  static/js/publisher/utils/__tests__/filterAvailableStores.test.ts
  static/js/publisher/utils/filterAvailableStores.ts
  static/js/publisher/utils/index.ts
  templates/publisher/register-snap.html
  tests/publisher/tests_register_name.py
  webapp/publisher/snaps/views.py
Labels: Review: Code +1, Review: QA +1

#5076 fix: don't index unlisted snaps
  templates/store/snap-distro-install.html
Labels: Review: Code +1, Review: QA +1

#5078 chore: Delete unused type and move constants file
  static/js/publisher/components/PublishedSnapList/PublishedSnapList.tsx
  static/js/publisher/components/PublishedSnapSection/PublishedSnapSection.tsx
  static/js/publisher/components/RegisteredSnaps/RegisteredSnaps.tsx
  static/js/publisher/constants/index.ts
  static/js/publisher/types/constants.ts
  static/js/publisher/types/shared.ts
Labels: Review: Code needed, Review: QA needed

#5079 fix: Fix welcome heading when publisher has no snaps
  static/js/publisher/components/PublishedSnapList/PublishedSnapList.tsx
Labels: Review: Code +1, Review: QA +1

#5088 fix: Address Signing Keys compiler warnings from TiCS dashboard
  static/js/publisher/pages/SigningKeys/SigningKeys.tsx
Labels: Review: Code +1, Review: QA +1

#5089 fix: Address register snap compiler warnings from TiCS dashboard
  static/js/publisher/pages/RegisterSnap/RegistrationError.tsx
Labels: Review: Code needed, Review: QA needed

#5090 chore: Update security.txt for SSDLC
  security.md
  security.txt
Labels: Review: Code +1

#5091 fix: Fix compiler warnings from the TiCS dashboard
  static/js/publisher/components/UpdateMetadataModal/UpdateMetadataModal.tsx
  static/js/publisher/pages/Listing/ListingForm/ListingForm.tsx
  static/js/publisher/pages/Metrics/metrics/graphs/activeDevicesGraph/rendering.ts
  static/js/publisher/pages/PublisherSettings/PublisherSettingsForm.tsx
  static/js/publisher/pages/Releases/constants.ts
  static/js/publisher/types/index.ts
  static/js/publisher/utils/getSettingsChanges.ts
  static/js/publisher/utils/getSettingsData.ts
  static/js/publisher/utils/getSettingsFormData.ts
Labels: Review: Code +1

#5092 fix: Address public and libs compiler warnings from TiCS dashboard
  static/js/libs/__tests__/shallowDiff.test.ts
  static/js/libs/shallowDiff.ts
Labels: Review: Code +1

#5094 fix: Address coding standards warnings from TiCS dashboard
  static/js/config/swiper.config.ts
  static/js/publisher/components/AppPagination/AppPagination.tsx
  static/js/publisher/components/EmptySnapList/EmptySnapList.tsx
  static/js/publisher/components/Filter/Filter.tsx
  static/js/publisher/components/NewSnapNotification/NewSnapNotification.tsx
  static/js/publisher/components/PublishedSnapList/PublishedSnapList.tsx
  static/js/publisher/components/PublishedSnapList/SnapNameEntry.tsx
  static/js/publisher/components/PublishedSnapSection/PublishedSnapSection.tsx
  static/js/publisher/components/PublisherMetrics/PublisherMetrics.tsx
  static/js/publisher/components/RegisteredSnaps/RegisteredSnaps.tsx
  static/js/publisher/components/SaveAndPreview/SaveAndPreview.tsx
  static/js/publisher/components/SaveStateNotifications/SaveStateNotifications.tsx
  static/js/publisher/components/SearchAutocomplete/SearchAutocomplete.tsx
  static/js/publisher/components/SectionNav/SectionNav.tsx
  static/js/publisher/components/StoreSelector/StoreSelector.tsx
  static/js/publisher/components/Tour/Tour.tsx
  static/js/publisher/components/Tour/TourStep.tsx
  static/js/publisher/components/UpdateMetadataModal/UpdateMetadataModal.tsx
  static/js/publisher/publisher.tsx
  static/js/store/components/Banner/Banner.tsx
  static/js/store/components/PackageFilter/PackageFilter.tsx
  static/js/store/components/PackageList/PackageList.tsx
  static/js/store/components/SearchInput/SearchInput.tsx
  static/js/store/hooks/usePackages.ts
  static/js/store/index.tsx
  static/js/store/utils/getArchitectures.ts
Labels: Review: Code +1

#5095 fix: Fix incorrect notification when registering snap name in the global store
  static/js/publisher/pages/RegisterSnap/RegistrationError.tsx
  static/js/publisher/pages/RegisterSnap/__tests__/RegisterSnapError.test.tsx
Labels: Review: Code +1, Review: QA +1

#5093 Allow access to CVE API for Canonical publishers
  webapp/publisher/cve/cve_views.py
Labels: Review: Code +1, Review: QA +1

#5098 fix: Address code coverage warnings from TiCS dashboard for publisher utils
  static/js/publisher/utils/__tests__/getSettingsChanges.test.ts
  static/js/publisher/utils/__tests__/getSettingsData.test.ts
  static/js/publisher/utils/getSettingsChanges.ts
Labels: Review: Code +1, Review: QA +1

#5100 feat(CVEs): Adds the API endpoint to check CVEs availability for given snap
  tests/publisher/cve/test_has_cve.py
  tests/publisher/cve/test_has_cve_api.py
  webapp/publisher/cve/cve_helper.py
  webapp/publisher/cve/cve_views.py
  webapp/publisher/snaps/views.py
Labels: Review: Code needed, Review: QA needed

#5104 chore: Address TiCS coding standards warnings for base JS
  static/js/base/__tests__/ga.test.ts
  static/js/base/contactForm.ts
  static/js/base/dropdown-menu-toggle.ts
  static/js/base/ga.ts
  static/js/base/navigation.ts
  static/js/public/ga-scroll-event.ts
  static/js/public/snap-details/channelMap.ts
Labels: Review: Code +1, Review: QA +1

#5106 chore: Address TiCS coding standards warnings for public JS
  static/js/base/ga.ts
  static/js/public/scroll-to.ts
  static/js/public/snap-details/embeddedCard.ts
Labels: Review: Code +1, Review: QA +1

#5108 Add API endpoint to get revisions with CVEs data
  tests/publisher/cve/test_has_cve.py
  tests/publisher/cve/test_has_cve_api.py
  webapp/publisher/cve/cve_helper.py
  webapp/publisher/cve/cve_views.py
  webapp/publisher/snaps/views.py
Labels: Review: QA +1, Review: Code +1 (with changes)

#5109 chore: Address TiCS code coverage warnings for publisher utils
  static/js/publisher/utils/__tests__/getListingChanges.test.ts
  static/js/publisher/utils/getListingChanges.ts
Labels: Review: Code +1, Review: QA +1

#5110 chore: Add tests for publisher settings page
  static/js/publisher/pages/PublisherSettings/PublisherSettingsForm.tsx
  static/js/publisher/pages/PublisherSettings/__tests__/PublisherSettings.test.tsx
  static/js/publisher/pages/PublisherSettings/__tests__/PublisherSettingsForm.test.tsx
Labels: Review: Code +1, Review: QA +1

#5111 chore: Add tests for register name dispute component
  static/js/publisher/pages/RegisterNameDispute/__tests__/RegisterNameDispute.test.tsx
Labels: Review: Code +1, Review: QA +1

#5112 chore: Remove unnecessary JS file
  static/js/public/distro-install.ts
  static/js/public/scroll-to.ts
  static/sass/styles.scss
  templates/store/snap-distro-install.html
Labels: Review: Code +1, Review: QA +1

#5115 chore: Add tests for publisher members
  static/js/publisher/pages/Members/__tests__/InvitesTable.test.tsx
  static/js/publisher/pages/Members/__tests__/MembersTable.test.tsx
Labels: Review: Code needed, Review: QA needed

#5116 chore: Add publisher members tests
  static/js/publisher/pages/Members/__tests__/Members.test.tsx
  static/js/publisher/test-utils/brand-store-requests.ts
  static/js/publisher/test-utils/brand-store-responses.ts
Labels: Review: Code +1, Review: QA +1

#5117 Expose status of CVE in API response
  tests/publisher/cve/test_cve_get_by_revision.py
  webapp/publisher/cve/cve_helper.py
Labels: Review: Code +1, Review: QA +1

#5119 fix: ensure progressive releases show in release ui
  static/js/publisher/pages/Metrics/metrics/graphs/activeDevicesGraph/tooltips.ts
  static/js/publisher/pages/Releases/Releases.tsx
  static/js/publisher/pages/Releases/components/revisionsList.js
  static/js/publisher/pages/Releases/components/revisionsListRow.js
  static/js/publisher/pages/Releases/releasesState.js
Labels: Review: Code +1, Review: QA +1
