Repository canonical/snapcraft.io, pull requests merged in 2025-06, with the labels that each got.

#5158 chore: add missing redirect for robotics docs
  redirects.yaml
Labels: Review: Code +1, Review: QA +1

#5166 Remove search input color overrides
  static/sass/_snapcraft_l-application.scss
Labels: Review: Code +1, Review: QA +1

#5125 chore: Update releases UI actions
  static/js/publisher/pages/Releases/components/progressiveBarControl.js
  static/js/publisher/pages/Releases/components/releasesConfirm.tsx
  static/js/publisher/pages/Releases/components/releasesConfirmActions.js
  static/js/publisher/pages/Releases/components/releasesConfirmDetails/globalRow.js
  static/js/publisher/pages/Releases/components/releasesConfirmDetails/index.js
  static/js/publisher/pages/Releases/components/releasesConfirmDetails/progressiveRow.js
  static/js/publisher/pages/Releases/components/releasesConfirmDetails/progressiveRowGroup.js
  static/js/publisher/pages/Releases/components/releasesConfirmDetails/releaseRow.js
  static/js/publisher/pages/Releases/components/releasesConfirmDetails/releaseRowGroup.js
  static/js/publisher/pages/Releases/components/releasesConfirmDetails/types.js
  static/js/publisher/pages/Releases/components/releasesTable/cellViews.js
  static/sass/_snapcraft_p-release-details-row.scss
  static/sass/_snapcraft_release.scss
Labels: Review: Code +1, Review: QA +1

#5160 fix: Use brand account ID rather than store ID in model service requests
  static/js/publisher/components/Navigation/Navigation.tsx
  static/js/publisher/hooks/__tests__/usePolicies.test.tsx
  static/js/publisher/hooks/usePolicies.ts
  static/js/publisher/hooks/useSigningKeys.ts
  static/js/publisher/pages/Model/CreatePolicyForm.tsx
  static/js/publisher/pages/Model/Policies.tsx
  static/js/publisher/pages/Model/PoliciesTable.tsx
  static/js/publisher/pages/SigningKeys/SigningKeys.tsx
  static/js/publisher/pages/SigningKeys/SigningKeysTable.tsx
  static/js/publisher/utils/sortByDateDescending.ts
  tests/admin/tests_models.py
  webapp/admin/views.py
Labels: Review: Code needed, Review: QA +1

#5170 feat: Add template for explore page
  static/js/store/components/SearchInput/SearchInput.tsx
  static/js/store/index.tsx
  static/js/store/pages/Explore/Explore.tsx
  static/js/store/pages/Explore/index.ts
  webapp/store/views.py
Labels: Review: Code +1, Review: QA +1

#5172 WD-23027 - feat: add error to snap/listing page when save fails
  static/js/publisher/components/UpdateMetadataModal/UpdateMetadataModal.tsx
  static/js/publisher/hooks/__tests__/useMutateListingData.test.ts
  static/js/publisher/hooks/useMutateListingData.ts
  static/js/publisher/pages/Listing/ListingForm/ListingForm.tsx
  static/js/publisher/pages/Listing/ListingForm/__tests__/ListingForm.test.tsx
  static/js/publisher/types/index.ts
  webapp/publisher/snaps/listing_views.py
  webpack.config.rules.js
Labels: Review: Code +1, Review: QA +1

#5173 feat: Add explore page recommendation sections
  static/js/store/pages/Explore/CardsLoader.tsx
  static/js/store/pages/Explore/Explore.tsx
  static/js/store/pages/Explore/RecommendationsSection.tsx
  static/js/store/pages/Explore/__tests__/Explore.test.tsx
  static/js/store/pages/Explore/__tests__/RecommendationsSection.test.tsx
  static/js/store/test-utils/index.ts
  static/js/store/test-utils/mockRecommendations.ts
  static/js/store/types/CardData.ts
  static/js/store/types/RecommendationData.ts
  static/js/store/types/index.ts
  static/js/store/utils/__tests__/formatCardData.test.ts
  static/js/store/utils/formatCardData.ts
  static/js/store/utils/index.ts
  webapp/handlers.py
Labels: Review: Code needed, Review: QA needed

#5177 chore: Update store API package
  requirements.txt
Labels: Review: Code needed, Review: QA needed

#5188 fix: use global csrf token
  static/js/publisher/pages/Releases/Releases.tsx
  static/js/publisher/pages/Releases/actions/__tests__/releases.test.js
  static/js/publisher/pages/Releases/actions/defaultTrack.js
  static/js/publisher/pages/Releases/actions/releases.ts
  static/js/publisher/pages/Releases/api/releases.js
  static/js/publisher/pages/Releases/components/defaultTrackModifier.js
  static/js/publisher/types/releaseTypes.ts
Labels: Review: Code +1, Review: QA +1
